import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

// All recipe data inline to avoid import issues in edge runtime
const ALL_RECIPES = [
  // LOW-CARB BREAKFAST
  { name: "Turmeric Poached Egg", pack: "low-carb", category: "breakfast", servings: 2, prep_time_minutes: 10, cook_time_minutes: 5, calories_per_serving: 219, protein_g: 14, carbs_g: 12, fat_g: 15, dietary_tags: ["GF","DF","LC","V","Q","N"], instructions: "1. Toast pine nuts in a dry pan for 2 minutes.\n2. Heat oil, stir-fry spinach and tomatoes for 2 minutes.\n3. Boil water with vinegar and turmeric. Poach eggs for 3 minutes.\n4. Divide spinach into bowls, top with egg and pine nuts.", ingredients: [{ name: "Pine nuts", quantity: "2 tsp", calories: 38, protein_g: 1, carbs_g: 1, fat_g: 4 }, { name: "Fresh spinach", quantity: "400g", calories: 92, protein_g: 11, carbs_g: 14, fat_g: 1 }, { name: "Cherry tomatoes", quantity: "125g", calories: 22, protein_g: 1, carbs_g: 5, fat_g: 0 }, { name: "Olive oil", quantity: "1 tbsp", calories: 119, protein_g: 0, carbs_g: 0, fat_g: 14 }, { name: "Eggs", quantity: "2", calories: 156, protein_g: 12, carbs_g: 2, fat_g: 11 }] },
  { name: "Omelet with Cottage Cheese & Basil", pack: "low-carb", category: "breakfast", servings: 4, prep_time_minutes: 10, cook_time_minutes: 10, calories_per_serving: 200, protein_g: 15, carbs_g: 3, fat_g: 14, dietary_tags: ["GF","LC","V","Q"], instructions: "1. Beat eggs with water and season.\n2. Cook thin omelets in oil.\n3. Mix basil with cottage cheese.\n4. Fill omelets, roll up and serve.", ingredients: [{ name: "Eggs", quantity: "6 large", calories: 468, protein_g: 36, carbs_g: 6, fat_g: 33 }, { name: "Cottage cheese", quantity: "200g", calories: 164, protein_g: 22, carbs_g: 6, fat_g: 5 }, { name: "Fresh basil", quantity: "1 bunch", calories: 5, protein_g: 1, carbs_g: 0, fat_g: 0 }, { name: "Cherry tomatoes", quantity: "12", calories: 36, protein_g: 2, carbs_g: 8, fat_g: 0 }] },
  { name: "Herby Breakfast Sausages", pack: "low-carb", category: "breakfast", servings: 8, prep_time_minutes: 10, cook_time_minutes: 10, calories_per_serving: 56, protein_g: 7, carbs_g: 2, fat_g: 3, dietary_tags: ["GF","DF","LC","Q"], instructions: "1. Mix pork with sage and basil.\n2. Shape into 8 sausages.\n3. Cook in coconut oil until browned.", ingredients: [{ name: "Ground pork", quantity: "250g", calories: 350, protein_g: 50, carbs_g: 0, fat_g: 16 }, { name: "Sage", quantity: "2 tbsp", calories: 3, protein_g: 0, carbs_g: 0, fat_g: 0 }, { name: "Coconut oil", quantity: "1 tbsp", calories: 117, protein_g: 0, carbs_g: 0, fat_g: 14 }] },
  { name: "Avocado & Egg Paste", pack: "low-carb", category: "breakfast", servings: 2, prep_time_minutes: 10, cook_time_minutes: 0, calories_per_serving: 298, protein_g: 11, carbs_g: 9, fat_g: 24, dietary_tags: ["GF","DF","LC","MP","V","Q"], instructions: "1. Boil eggs, peel and chop.\n2. Cube avocado.\n3. Mix with coriander, lemon juice and olive oil.", ingredients: [{ name: "Eggs", quantity: "3, boiled", calories: 234, protein_g: 18, carbs_g: 3, fat_g: 16 }, { name: "Avocado", quantity: "1 ripe", calories: 234, protein_g: 3, carbs_g: 12, fat_g: 21 }, { name: "Lemon juice", quantity: "1 tsp", calories: 1, protein_g: 0, carbs_g: 0, fat_g: 0 }] },
  { name: "Cottage Cheese Protein Pancakes", pack: "low-carb", category: "breakfast", servings: 4, prep_time_minutes: 10, cook_time_minutes: 10, calories_per_serving: 162, protein_g: 12, carbs_g: 18, fat_g: 4, dietary_tags: ["V","Q"], instructions: "1. Mix cottage cheese with egg yolks and flour.\n2. Fold in whisked egg whites.\n3. Pan-fry pancakes for 3 minutes each side.", ingredients: [{ name: "Cottage cheese", quantity: "250g", calories: 205, protein_g: 28, carbs_g: 8, fat_g: 6 }, { name: "Eggs", quantity: "3", calories: 234, protein_g: 18, carbs_g: 3, fat_g: 16 }, { name: "Flour", quantity: "3 tbsp", calories: 150, protein_g: 4, carbs_g: 31, fat_g: 0 }] },
  { name: "Tropical Gluten Free Granola", pack: "low-carb", category: "breakfast", servings: 28, prep_time_minutes: 20, cook_time_minutes: 120, calories_per_serving: 173, protein_g: 4, carbs_g: 10, fat_g: 14, dietary_tags: ["GF","DF","V","N"], instructions: "1. Blend pineapple, dates, orange juice, vanilla and cinnamon.\n2. Mix with almonds, cashews, coconut and seeds.\n3. Bake at 250°F for 2 hours, stirring every 20 minutes.", ingredients: [{ name: "Pineapple", quantity: "165g", calories: 82, protein_g: 1, carbs_g: 22, fat_g: 0 }, { name: "Almonds", quantity: "400g", calories: 2292, protein_g: 84, carbs_g: 84, fat_g: 200 }, { name: "Cashew nuts", quantity: "150g", calories: 828, protein_g: 26, carbs_g: 44, fat_g: 66 }] },
  { name: "Smoked Mackerel & Egg Paste", pack: "low-carb", category: "breakfast", servings: 4, prep_time_minutes: 10, cook_time_minutes: 0, calories_per_serving: 268, protein_g: 18, carbs_g: 5, fat_g: 23, dietary_tags: ["GF","LC","MP","Q"], instructions: "1. Boil eggs, chop.\n2. Debone mackerel and chop.\n3. Mix with onion, gherkins, mayo and yogurt.", ingredients: [{ name: "Eggs", quantity: "4, boiled", calories: 312, protein_g: 24, carbs_g: 4, fat_g: 22 }, { name: "Smoked mackerel", quantity: "200g", calories: 440, protein_g: 38, carbs_g: 0, fat_g: 32 }, { name: "Mayonnaise", quantity: "2 tbsp", calories: 70, protein_g: 0, carbs_g: 2, fat_g: 6 }] },
  { name: "Egg Broccoli & Ham Muffins", pack: "low-carb", category: "breakfast", servings: 6, prep_time_minutes: 5, cook_time_minutes: 15, calories_per_serving: 102, protein_g: 10, carbs_g: 4, fat_g: 6, dietary_tags: ["GF","DF","LC","MP","Q"], instructions: "1. Boil broccoli, chop small.\n2. Beat eggs with garlic.\n3. Fill muffin tray with broccoli, ham and cheese. Pour in eggs.\n4. Bake 10-15 minutes at 180°C.", ingredients: [{ name: "Broccoli", quantity: "½ head", calories: 27, protein_g: 3, carbs_g: 5, fat_g: 0 }, { name: "Eggs", quantity: "5", calories: 390, protein_g: 30, carbs_g: 5, fat_g: 27 }, { name: "Ham", quantity: "4 slices", calories: 120, protein_g: 16, carbs_g: 4, fat_g: 4 }] },
  { name: "Egg, Bacon & Avocado Bowl", pack: "low-carb", category: "breakfast", servings: 1, prep_time_minutes: 5, cook_time_minutes: 5, calories_per_serving: 378, protein_g: 23, carbs_g: 14, fat_g: 32, dietary_tags: ["GF","DF","LC","HP","Q"], instructions: "1. Fry bacon until crisp, chop.\n2. Combine with eggs, avocado, onion and pepper.\n3. Season and serve.", ingredients: [{ name: "Bacon medallions", quantity: "2", calories: 70, protein_g: 10, carbs_g: 0, fat_g: 3 }, { name: "Eggs", quantity: "2, boiled", calories: 156, protein_g: 12, carbs_g: 2, fat_g: 11 }, { name: "Avocado", quantity: "½", calories: 117, protein_g: 1, carbs_g: 6, fat_g: 11 }] },
  { name: "Asian Scrambled Eggs", pack: "low-carb", category: "breakfast", servings: 1, prep_time_minutes: 5, cook_time_minutes: 5, calories_per_serving: 270, protein_g: 19, carbs_g: 5, fat_g: 14, dietary_tags: ["GF","DF","LC","V","Q"], instructions: "1. Separate eggs, mix yolks with soy sauce and coriander.\n2. Fry whites, add yolks off heat.\n3. Serve with sesame seeds and avocado.", ingredients: [{ name: "Eggs", quantity: "3", calories: 234, protein_g: 18, carbs_g: 3, fat_g: 16 }, { name: "Soy sauce", quantity: "few drops", calories: 3, protein_g: 0, carbs_g: 0, fat_g: 0 }, { name: "Avocado", quantity: "¼", calories: 58, protein_g: 1, carbs_g: 3, fat_g: 5 }] },
  // LOW-CARB SNACK
  { name: "Zucchini Fries", pack: "low-carb", category: "snack", servings: 4, prep_time_minutes: 20, cook_time_minutes: 15, calories_per_serving: 177, protein_g: 5, carbs_g: 14, fat_g: 12, dietary_tags: ["DF","LC","V"], instructions: "1. Cut zucchini into fry shapes.\n2. Dip in egg wash, roll in breadcrumbs.\n3. Bake at 220°C for 15 minutes.", ingredients: [{ name: "Zucchini", quantity: "500g", calories: 85, protein_g: 6, carbs_g: 16, fat_g: 2 }, { name: "Egg", quantity: "1", calories: 78, protein_g: 6, carbs_g: 1, fat_g: 5 }, { name: "Breadcrumbs", quantity: "4 tbsp", calories: 108, protein_g: 4, carbs_g: 20, fat_g: 2 }] },
  // LOW-CARB LUNCH
  { name: "Tofu Caesar Summer Rolls", pack: "low-carb", category: "lunch", servings: 4, prep_time_minutes: 15, cook_time_minutes: 10, calories_per_serving: 191, protein_g: 5, carbs_g: 8, fat_g: 10, dietary_tags: ["LC","V"], instructions: "1. Pan-fry tofu until golden.\n2. Soften rice paper. Fill with tofu, avocado, Parmesan and lettuce.\n3. Roll tightly. Serve with Caesar dressing.", ingredients: [{ name: "Firm tofu", quantity: "100g", calories: 76, protein_g: 8, carbs_g: 2, fat_g: 5 }, { name: "Avocado", quantity: "½", calories: 117, protein_g: 1, carbs_g: 6, fat_g: 11 }, { name: "Rice paper wrappers", quantity: "4", calories: 120, protein_g: 0, carbs_g: 28, fat_g: 0 }] },
  { name: "Sweetcorn Fritters", pack: "low-carb", category: "breakfast", servings: 8, prep_time_minutes: 10, cook_time_minutes: 18, calories_per_serving: 97, protein_g: 3, carbs_g: 15, fat_g: 3, dietary_tags: ["GF","DF","LC","V","Q"], instructions: "1. Mix sweetcorn with coriander and lemon zest.\n2. Mix buckwheat flour with water for batter.\n3. Combine and fry in coconut oil.", ingredients: [{ name: "Sweetcorn", quantity: "280g", calories: 240, protein_g: 8, carbs_g: 48, fat_g: 4 }, { name: "Buckwheat flour", quantity: "120g", calories: 400, protein_g: 12, carbs_g: 80, fat_g: 4 }] },
  { name: "Simple Summer Slaw", pack: "low-carb", category: "lunch", servings: 4, prep_time_minutes: 15, cook_time_minutes: 0, calories_per_serving: 115, protein_g: 3, carbs_g: 10, fat_g: 7, dietary_tags: ["GF","DF","LC","V","Q"], instructions: "1. Shred cabbage, carrots and apple.\n2. Mix dressing with apple cider vinegar and mustard.\n3. Toss and serve.", ingredients: [{ name: "Red cabbage", quantity: "¼ head", calories: 28, protein_g: 1, carbs_g: 7, fat_g: 0 }, { name: "White cabbage", quantity: "¼ head", calories: 22, protein_g: 1, carbs_g: 5, fat_g: 0 }, { name: "Carrots", quantity: "2", calories: 50, protein_g: 1, carbs_g: 12, fat_g: 0 }] },
  { name: "Roasted Butternut & Feta Salad", pack: "low-carb", category: "lunch", servings: 2, prep_time_minutes: 15, cook_time_minutes: 30, calories_per_serving: 336, protein_g: 15, carbs_g: 28, fat_g: 18, dietary_tags: ["GF","LC","V","N"], instructions: "1. Roast butternut with balsamic and oil at 200°C for 30 minutes.\n2. Combine with quinoa, rocket, feta, pomegranate and pine nuts.\n3. Dress and serve.", ingredients: [{ name: "Butternut squash", quantity: "500g", calories: 225, protein_g: 5, carbs_g: 60, fat_g: 0 }, { name: "Feta cheese", quantity: "75g", calories: 198, protein_g: 11, carbs_g: 3, fat_g: 16 }, { name: "Quinoa", quantity: "80g", calories: 288, protein_g: 10, carbs_g: 50, fat_g: 4 }] },
  { name: "Spicy Chicken Lettuce Cups", pack: "low-carb", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 10, calories_per_serving: 250, protein_g: 30, carbs_g: 8, fat_g: 10, dietary_tags: ["GF","DF","LC","HP","Q"], instructions: "1. Stir-fry chicken mince with garlic and chili.\n2. Add soy sauce and fish sauce.\n3. Serve in lettuce cups with herbs.", ingredients: [{ name: "Chicken mince", quantity: "300g", calories: 390, protein_g: 54, carbs_g: 0, fat_g: 18 }, { name: "Iceberg lettuce", quantity: "1 head", calories: 14, protein_g: 1, carbs_g: 3, fat_g: 0 }, { name: "Soy sauce", quantity: "2 tbsp", calories: 16, protein_g: 2, carbs_g: 2, fat_g: 0 }] },
  { name: "Mediterranean Stuffed Peppers", pack: "low-carb", category: "lunch", servings: 4, prep_time_minutes: 15, cook_time_minutes: 25, calories_per_serving: 220, protein_g: 12, carbs_g: 18, fat_g: 12, dietary_tags: ["GF","LC","V"], instructions: "1. Halve peppers, remove seeds.\n2. Fill with quinoa, feta, olives and sun-dried tomatoes.\n3. Bake at 190°C for 25 minutes.", ingredients: [{ name: "Bell peppers", quantity: "4", calories: 124, protein_g: 4, carbs_g: 24, fat_g: 0 }, { name: "Quinoa", quantity: "100g", calories: 120, protein_g: 4, carbs_g: 21, fat_g: 2 }, { name: "Feta cheese", quantity: "100g", calories: 264, protein_g: 14, carbs_g: 4, fat_g: 21 }] },
  { name: "Thai Coconut Soup", pack: "low-carb", category: "lunch", servings: 4, prep_time_minutes: 10, cook_time_minutes: 20, calories_per_serving: 280, protein_g: 20, carbs_g: 12, fat_g: 18, dietary_tags: ["GF","DF","LC"], instructions: "1. Sauté lemongrass, ginger and garlic.\n2. Add coconut milk and broth.\n3. Simmer with prawns and mushrooms.\n4. Serve with lime and coriander.", ingredients: [{ name: "Coconut milk", quantity: "400ml", calories: 760, protein_g: 8, carbs_g: 12, fat_g: 76 }, { name: "Prawns", quantity: "300g", calories: 300, protein_g: 60, carbs_g: 0, fat_g: 4 }, { name: "Mushrooms", quantity: "150g", calories: 33, protein_g: 5, carbs_g: 5, fat_g: 0 }] },
  // LOW-CARB DINNER
  { name: "Salmon Cakes with Green Salad", pack: "low-carb", category: "dinner", servings: 6, prep_time_minutes: 15, cook_time_minutes: 12, calories_per_serving: 278, protein_g: 18, carbs_g: 8, fat_g: 19, dietary_tags: ["GF","LC","HP"], instructions: "1. Mix salmon with egg, spring onion, capers and lemon.\n2. Shape into cakes.\n3. Pan-fry 4-6 minutes per side.\n4. Serve with green salad.", ingredients: [{ name: "Salmon", quantity: "400g", calories: 832, protein_g: 80, carbs_g: 0, fat_g: 56 }, { name: "Egg", quantity: "1", calories: 78, protein_g: 6, carbs_g: 1, fat_g: 5 }, { name: "Spring onion", quantity: "2", calories: 10, protein_g: 1, carbs_g: 2, fat_g: 0 }] },
  { name: "Cod with Creamy Zoodles", pack: "low-carb", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 340, protein_g: 35, carbs_g: 10, fat_g: 18, dietary_tags: ["GF","LC","HP","Q"], instructions: "1. Pan-fry cod in olive oil for 4 minutes per side.\n2. Spiralize zucchini.\n3. Toss zoodles in cream cheese and lemon.\n4. Serve fish on zoodles.", ingredients: [{ name: "Cod fillets", quantity: "2 x 200g", calories: 360, protein_g: 80, carbs_g: 0, fat_g: 2 }, { name: "Zucchini", quantity: "2, spiralized", calories: 34, protein_g: 2, carbs_g: 6, fat_g: 1 }, { name: "Cream cheese", quantity: "2 tbsp", calories: 100, protein_g: 2, carbs_g: 2, fat_g: 10 }] },
  { name: "Jerk Chicken with Cauliflower Rice", pack: "low-carb", category: "dinner", servings: 4, prep_time_minutes: 15, cook_time_minutes: 25, calories_per_serving: 320, protein_g: 35, carbs_g: 12, fat_g: 14, dietary_tags: ["GF","DF","LC","HP"], instructions: "1. Coat chicken in jerk seasoning.\n2. Grill or bake for 20-25 minutes.\n3. Pulse cauliflower in processor.\n4. Sauté cauliflower rice and serve.", ingredients: [{ name: "Chicken thighs", quantity: "600g", calories: 690, protein_g: 84, carbs_g: 0, fat_g: 36 }, { name: "Jerk seasoning", quantity: "3 tbsp", calories: 30, protein_g: 1, carbs_g: 6, fat_g: 0 }, { name: "Cauliflower", quantity: "1 head", calories: 146, protein_g: 11, carbs_g: 29, fat_g: 2 }] },
  { name: "Sesame & Ginger Beef Stir Fry", pack: "low-carb", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 12, calories_per_serving: 380, protein_g: 35, carbs_g: 15, fat_g: 20, dietary_tags: ["DF","LC","HP","Q"], instructions: "1. Slice beef thin, marinate in soy, ginger and sesame oil.\n2. Stir-fry vegetables.\n3. Sear beef on high heat.\n4. Combine and serve.", ingredients: [{ name: "Sirloin steak", quantity: "300g", calories: 510, protein_g: 62, carbs_g: 0, fat_g: 28 }, { name: "Mixed vegetables", quantity: "300g", calories: 75, protein_g: 5, carbs_g: 15, fat_g: 1 }, { name: "Sesame oil", quantity: "1 tbsp", calories: 120, protein_g: 0, carbs_g: 0, fat_g: 14 }] },
  { name: "Lemon Garlic Prawns", pack: "low-carb", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 8, calories_per_serving: 250, protein_g: 30, carbs_g: 5, fat_g: 12, dietary_tags: ["GF","DF","LC","HP","Q"], instructions: "1. Sauté garlic in olive oil.\n2. Add prawns, cook 2-3 minutes per side.\n3. Add lemon juice, parsley and chili flakes.\n4. Serve with salad.", ingredients: [{ name: "King prawns", quantity: "400g", calories: 400, protein_g: 80, carbs_g: 0, fat_g: 5 }, { name: "Garlic", quantity: "4 cloves", calories: 16, protein_g: 1, carbs_g: 4, fat_g: 0 }, { name: "Olive oil", quantity: "2 tbsp", calories: 238, protein_g: 0, carbs_g: 0, fat_g: 28 }] },
  { name: "Turkey Stuffed Zucchini Boats", pack: "low-carb", category: "dinner", servings: 4, prep_time_minutes: 15, cook_time_minutes: 25, calories_per_serving: 280, protein_g: 30, carbs_g: 12, fat_g: 12, dietary_tags: ["GF","LC","HP"], instructions: "1. Halve zucchini, scoop out centres.\n2. Brown turkey mince with onion and garlic.\n3. Fill zucchini with turkey mix, top with cheese.\n4. Bake at 190°C for 20 minutes.", ingredients: [{ name: "Zucchini", quantity: "4 large", calories: 68, protein_g: 5, carbs_g: 13, fat_g: 1 }, { name: "Turkey mince", quantity: "400g", calories: 440, protein_g: 88, carbs_g: 0, fat_g: 8 }, { name: "Mozzarella", quantity: "100g", calories: 280, protein_g: 22, carbs_g: 2, fat_g: 22 }] },
  { name: "Chicken & Vegetable Stew", pack: "low-carb", category: "dinner", servings: 4, prep_time_minutes: 15, cook_time_minutes: 35, calories_per_serving: 310, protein_g: 35, carbs_g: 20, fat_g: 10, dietary_tags: ["GF","DF","LC","HP","MP"], instructions: "1. Brown chicken pieces.\n2. Sauté onion, garlic, carrots and celery.\n3. Add stock and tomatoes. Simmer 25 minutes.\n4. Add kale and cook 5 more minutes.", ingredients: [{ name: "Chicken breast", quantity: "500g", calories: 550, protein_g: 120, carbs_g: 0, fat_g: 6 }, { name: "Carrots", quantity: "3", calories: 75, protein_g: 2, carbs_g: 18, fat_g: 0 }, { name: "Chicken stock", quantity: "500ml", calories: 15, protein_g: 1, carbs_g: 1, fat_g: 0 }] },
  { name: "Aubergine & Halloumi Stack", pack: "low-carb", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 320, protein_g: 18, carbs_g: 12, fat_g: 24, dietary_tags: ["GF","LC","V","Q"], instructions: "1. Slice and grill aubergine.\n2. Grill halloumi slices.\n3. Layer with tomato, basil and balsamic glaze.\n4. Serve warm.", ingredients: [{ name: "Aubergine", quantity: "1 large", calories: 55, protein_g: 2, carbs_g: 13, fat_g: 0 }, { name: "Halloumi", quantity: "200g", calories: 580, protein_g: 34, carbs_g: 4, fat_g: 48 }, { name: "Tomato", quantity: "1 large", calories: 22, protein_g: 1, carbs_g: 5, fat_g: 0 }] },
  // LOW-CARB TREATS
  { name: "Healthy Ferrero Rocher", pack: "low-carb", category: "treats", servings: 12, prep_time_minutes: 30, cook_time_minutes: 0, calories_per_serving: 120, protein_g: 3, carbs_g: 8, fat_g: 9, dietary_tags: ["GF","DF","V","N"], instructions: "1. Toast and chop hazelnuts.\n2. Blend dates, cocoa and coconut oil.\n3. Wrap around whole hazelnuts.\n4. Roll in chopped hazelnuts. Chill.", ingredients: [{ name: "Hazelnuts", quantity: "100g", calories: 628, protein_g: 15, carbs_g: 17, fat_g: 61 }, { name: "Medjool dates", quantity: "8", calories: 533, protein_g: 4, carbs_g: 144, fat_g: 0 }, { name: "Cocoa powder", quantity: "3 tbsp", calories: 36, protein_g: 3, carbs_g: 9, fat_g: 3 }] },
  { name: "Mocha Truffles", pack: "low-carb", category: "treats", servings: 14, prep_time_minutes: 20, cook_time_minutes: 0, calories_per_serving: 95, protein_g: 2, carbs_g: 10, fat_g: 6, dietary_tags: ["GF","DF","V","N"], instructions: "1. Blend dates, almonds, cocoa and espresso.\n2. Roll into small balls.\n3. Roll in cocoa powder. Chill.", ingredients: [{ name: "Medjool dates", quantity: "10", calories: 667, protein_g: 5, carbs_g: 180, fat_g: 0 }, { name: "Almonds", quantity: "100g", calories: 575, protein_g: 21, carbs_g: 22, fat_g: 50 }, { name: "Cocoa powder", quantity: "3 tbsp", calories: 36, protein_g: 3, carbs_g: 9, fat_g: 3 }] },
  { name: "Vegan Crème Brûlée", pack: "low-carb", category: "treats", servings: 4, prep_time_minutes: 15, cook_time_minutes: 45, calories_per_serving: 280, protein_g: 4, carbs_g: 18, fat_g: 22, dietary_tags: ["GF","DF","V"], instructions: "1. Heat coconut cream with vanilla.\n2. Mix with cornflour and maple syrup.\n3. Pour into ramekins, bake in water bath at 160°C for 40 minutes.\n4. Chill, then caramelize sugar on top.", ingredients: [{ name: "Coconut cream", quantity: "400ml", calories: 760, protein_g: 8, carbs_g: 16, fat_g: 76 }, { name: "Maple syrup", quantity: "3 tbsp", calories: 156, protein_g: 0, carbs_g: 40, fat_g: 0 }, { name: "Cornflour", quantity: "2 tbsp", calories: 60, protein_g: 0, carbs_g: 15, fat_g: 0 }] },
  { name: "Avocado Chocolate Mousse", pack: "low-carb", category: "treats", servings: 4, prep_time_minutes: 10, cook_time_minutes: 0, calories_per_serving: 240, protein_g: 3, carbs_g: 22, fat_g: 18, dietary_tags: ["GF","DF","LC","V","Q"], instructions: "1. Blend avocado, cocoa, maple syrup and vanilla until smooth.\n2. Divide into bowls.\n3. Chill for 30 minutes. Top with berries.", ingredients: [{ name: "Avocado", quantity: "2 ripe", calories: 468, protein_g: 6, carbs_g: 24, fat_g: 42 }, { name: "Cocoa powder", quantity: "4 tbsp", calories: 48, protein_g: 4, carbs_g: 12, fat_g: 4 }, { name: "Maple syrup", quantity: "3 tbsp", calories: 156, protein_g: 0, carbs_g: 40, fat_g: 0 }] },
  { name: "Coconut Energy Balls", pack: "low-carb", category: "treats", servings: 12, prep_time_minutes: 15, cook_time_minutes: 0, calories_per_serving: 110, protein_g: 3, carbs_g: 10, fat_g: 7, dietary_tags: ["GF","DF","V","N"], instructions: "1. Blend dates, oats, coconut and almond butter.\n2. Roll into 12 balls.\n3. Roll in desiccated coconut. Chill.", ingredients: [{ name: "Medjool dates", quantity: "8", calories: 533, protein_g: 4, carbs_g: 144, fat_g: 0 }, { name: "Oats", quantity: "100g", calories: 370, protein_g: 12, carbs_g: 66, fat_g: 7 }, { name: "Desiccated coconut", quantity: "50g", calories: 330, protein_g: 3, carbs_g: 12, fat_g: 33 }] },
  // HIGH-PROTEIN BREAKFAST
  { name: "Spanish Zucchini Tortilla", pack: "high-protein", category: "breakfast", servings: 2, prep_time_minutes: 10, cook_time_minutes: 20, calories_per_serving: 300, protein_g: 22, carbs_g: 8, fat_g: 20, dietary_tags: ["GF","HP","V","Q"], instructions: "1. Sauté zucchini in olive oil.\n2. Beat eggs, pour over zucchini.\n3. Cook on low heat until set.\n4. Flip and cook other side.", ingredients: [{ name: "Eggs", quantity: "6", calories: 468, protein_g: 36, carbs_g: 6, fat_g: 33 }, { name: "Zucchini", quantity: "2 medium", calories: 34, protein_g: 2, carbs_g: 6, fat_g: 1 }, { name: "Olive oil", quantity: "2 tbsp", calories: 238, protein_g: 0, carbs_g: 0, fat_g: 28 }] },
  { name: "Omelette Wraps", pack: "high-protein", category: "breakfast", servings: 4, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 280, protein_g: 24, carbs_g: 5, fat_g: 18, dietary_tags: ["GF","HP","Q"], instructions: "1. Make thin omelettes.\n2. Fill with turkey, spinach and cheese.\n3. Roll up and serve.", ingredients: [{ name: "Eggs", quantity: "8", calories: 624, protein_g: 48, carbs_g: 8, fat_g: 44 }, { name: "Turkey slices", quantity: "200g", calories: 220, protein_g: 44, carbs_g: 0, fat_g: 4 }, { name: "Spinach", quantity: "100g", calories: 23, protein_g: 3, carbs_g: 4, fat_g: 0 }] },
  { name: "Egg & Turkey Stuffed Peppers", pack: "high-protein", category: "breakfast", servings: 4, prep_time_minutes: 10, cook_time_minutes: 20, calories_per_serving: 200, protein_g: 22, carbs_g: 8, fat_g: 8, dietary_tags: ["GF","DF","HP","Q"], instructions: "1. Halve peppers, remove seeds.\n2. Fill with turkey mince and egg.\n3. Bake at 190°C for 18-20 minutes.", ingredients: [{ name: "Bell peppers", quantity: "4", calories: 124, protein_g: 4, carbs_g: 24, fat_g: 0 }, { name: "Turkey mince", quantity: "200g", calories: 220, protein_g: 44, carbs_g: 0, fat_g: 4 }, { name: "Eggs", quantity: "4", calories: 312, protein_g: 24, carbs_g: 4, fat_g: 22 }] },
  { name: "Smoked Salmon, Feta & Asparagus Omelet", pack: "high-protein", category: "breakfast", servings: 2, prep_time_minutes: 10, cook_time_minutes: 10, calories_per_serving: 350, protein_g: 30, carbs_g: 4, fat_g: 24, dietary_tags: ["GF","HP","Q"], instructions: "1. Steam asparagus for 3 minutes.\n2. Make omelette with eggs.\n3. Fill with salmon, feta and asparagus.\n4. Fold and serve.", ingredients: [{ name: "Eggs", quantity: "4", calories: 312, protein_g: 24, carbs_g: 4, fat_g: 22 }, { name: "Smoked salmon", quantity: "100g", calories: 180, protein_g: 24, carbs_g: 0, fat_g: 9 }, { name: "Feta cheese", quantity: "50g", calories: 132, protein_g: 7, carbs_g: 2, fat_g: 11 }] },
  { name: "High Protein Blueberry Pancakes", pack: "high-protein", category: "breakfast", servings: 1, prep_time_minutes: 5, cook_time_minutes: 10, calories_per_serving: 380, protein_g: 30, carbs_g: 40, fat_g: 10, dietary_tags: ["HP","V","Q"], instructions: "1. Blend oats, egg, protein powder and milk.\n2. Fold in blueberries.\n3. Pan-fry for 2-3 minutes each side.\n4. Serve with yogurt.", ingredients: [{ name: "Oats", quantity: "40g", calories: 148, protein_g: 5, carbs_g: 26, fat_g: 3 }, { name: "Egg", quantity: "1", calories: 78, protein_g: 6, carbs_g: 1, fat_g: 5 }, { name: "Protein powder", quantity: "1 scoop", calories: 120, protein_g: 24, carbs_g: 3, fat_g: 1 }] },
  { name: "Eggs Fried on Tomatoes with Tuna", pack: "high-protein", category: "breakfast", servings: 1, prep_time_minutes: 5, cook_time_minutes: 10, calories_per_serving: 320, protein_g: 35, carbs_g: 8, fat_g: 16, dietary_tags: ["GF","DF","HP","Q"], instructions: "1. Sauté tomatoes until softened.\n2. Add tuna, make wells.\n3. Crack eggs into wells.\n4. Cover and cook until set.", ingredients: [{ name: "Eggs", quantity: "2", calories: 156, protein_g: 12, carbs_g: 2, fat_g: 11 }, { name: "Tinned tuna", quantity: "80g", calories: 100, protein_g: 22, carbs_g: 0, fat_g: 1 }, { name: "Cherry tomatoes", quantity: "200g", calories: 36, protein_g: 2, carbs_g: 8, fat_g: 0 }] },
  { name: "Summer Smoothie Protein Bowl", pack: "high-protein", category: "breakfast", servings: 2, prep_time_minutes: 10, cook_time_minutes: 0, calories_per_serving: 320, protein_g: 28, carbs_g: 35, fat_g: 8, dietary_tags: ["GF","HP","V","Q"], instructions: "1. Blend frozen berries, protein powder, yogurt and banana.\n2. Pour into bowls.\n3. Top with granola, seeds and fresh fruit.", ingredients: [{ name: "Frozen berries", quantity: "200g", calories: 90, protein_g: 2, carbs_g: 20, fat_g: 1 }, { name: "Protein powder", quantity: "2 scoops", calories: 240, protein_g: 48, carbs_g: 6, fat_g: 2 }, { name: "Greek yogurt", quantity: "200g", calories: 118, protein_g: 20, carbs_g: 8, fat_g: 0 }] },
  { name: "Spinach Shakshuka", pack: "high-protein", category: "breakfast", servings: 2, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 280, protein_g: 18, carbs_g: 12, fat_g: 18, dietary_tags: ["GF","HP","V","Q"], instructions: "1. Sauté onion and garlic.\n2. Add tomatoes and spinach.\n3. Make wells, crack in eggs.\n4. Cover and cook until eggs are set.", ingredients: [{ name: "Eggs", quantity: "4", calories: 312, protein_g: 24, carbs_g: 4, fat_g: 22 }, { name: "Spinach", quantity: "200g", calories: 46, protein_g: 6, carbs_g: 7, fat_g: 1 }, { name: "Tinned tomatoes", quantity: "400g", calories: 80, protein_g: 4, carbs_g: 16, fat_g: 0 }] },
  { name: "Salmon Tartar with Avocado and Mango", pack: "high-protein", category: "breakfast", servings: 1, prep_time_minutes: 15, cook_time_minutes: 0, calories_per_serving: 420, protein_g: 30, carbs_g: 22, fat_g: 24, dietary_tags: ["GF","DF","HP","Q"], instructions: "1. Dice salmon finely.\n2. Mix with soy sauce, lime and sesame oil.\n3. Layer with avocado and mango.\n4. Serve chilled.", ingredients: [{ name: "Fresh salmon", quantity: "150g", calories: 312, protein_g: 30, carbs_g: 0, fat_g: 21 }, { name: "Avocado", quantity: "½", calories: 117, protein_g: 1, carbs_g: 6, fat_g: 11 }, { name: "Mango", quantity: "½", calories: 68, protein_g: 1, carbs_g: 18, fat_g: 0 }] },
  { name: "Egg White & Veggie Frittata", pack: "high-protein", category: "breakfast", servings: 4, prep_time_minutes: 10, cook_time_minutes: 20, calories_per_serving: 140, protein_g: 18, carbs_g: 8, fat_g: 4, dietary_tags: ["GF","HP","LC","V","Q"], instructions: "1. Sauté vegetables.\n2. Pour whisked egg whites and whole eggs over.\n3. Top with feta, bake at 190°C for 15 minutes.", ingredients: [{ name: "Egg whites", quantity: "10", calories: 170, protein_g: 36, carbs_g: 2, fat_g: 0 }, { name: "Whole eggs", quantity: "2", calories: 156, protein_g: 12, carbs_g: 2, fat_g: 11 }, { name: "Feta cheese", quantity: "50g", calories: 132, protein_g: 7, carbs_g: 2, fat_g: 11 }] },
  // HIGH-PROTEIN LUNCH
  { name: "Tuna Salad Lettuce Wraps", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 0, calories_per_serving: 280, protein_g: 32, carbs_g: 8, fat_g: 14, dietary_tags: ["GF","DF","HP","LC","Q"], instructions: "1. Mix tuna with celery, onion and mayo.\n2. Spoon onto lettuce leaves.\n3. Wrap and serve.", ingredients: [{ name: "Tinned tuna", quantity: "200g", calories: 250, protein_g: 55, carbs_g: 0, fat_g: 2 }, { name: "Iceberg lettuce", quantity: "1 head", calories: 14, protein_g: 1, carbs_g: 3, fat_g: 0 }, { name: "Mayonnaise", quantity: "1 tbsp", calories: 94, protein_g: 0, carbs_g: 0, fat_g: 10 }] },
  { name: "Chicken, Orange and Walnut Salad", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 15, cook_time_minutes: 10, calories_per_serving: 380, protein_g: 35, carbs_g: 18, fat_g: 20, dietary_tags: ["GF","DF","HP","N"], instructions: "1. Grill chicken breast, slice.\n2. Segment oranges.\n3. Toss with mixed leaves, walnuts and dressing.", ingredients: [{ name: "Chicken breast", quantity: "300g", calories: 330, protein_g: 72, carbs_g: 0, fat_g: 4 }, { name: "Orange", quantity: "1 large", calories: 86, protein_g: 2, carbs_g: 22, fat_g: 0 }, { name: "Walnuts", quantity: "30g", calories: 196, protein_g: 5, carbs_g: 4, fat_g: 20 }] },
  { name: "Salmon & Peach Salad", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 12, calories_per_serving: 360, protein_g: 32, carbs_g: 15, fat_g: 20, dietary_tags: ["GF","DF","HP","Q"], instructions: "1. Pan-fry salmon for 4 minutes per side.\n2. Slice peaches.\n3. Arrange over mixed leaves with avocado.\n4. Drizzle with balsamic.", ingredients: [{ name: "Salmon fillets", quantity: "2 x 150g", calories: 468, protein_g: 52, carbs_g: 0, fat_g: 28 }, { name: "Peach", quantity: "2", calories: 78, protein_g: 2, carbs_g: 18, fat_g: 0 }, { name: "Avocado", quantity: "½", calories: 117, protein_g: 1, carbs_g: 6, fat_g: 11 }] },
  { name: "Tuna & Broccoli Salad with Honey Vinaigrette", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 5, calories_per_serving: 300, protein_g: 30, carbs_g: 14, fat_g: 14, dietary_tags: ["GF","DF","HP","Q"], instructions: "1. Steam broccoli for 4 minutes.\n2. Mix tuna, broccoli, onion and tomatoes.\n3. Dress with honey vinaigrette.", ingredients: [{ name: "Tinned tuna", quantity: "200g", calories: 250, protein_g: 55, carbs_g: 0, fat_g: 2 }, { name: "Broccoli", quantity: "1 head", calories: 55, protein_g: 4, carbs_g: 11, fat_g: 1 }, { name: "Honey", quantity: "1 tbsp", calories: 64, protein_g: 0, carbs_g: 17, fat_g: 0 }] },
  { name: "Grilled Chicken & Pineapple Salad", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 12, calories_per_serving: 350, protein_g: 38, carbs_g: 20, fat_g: 14, dietary_tags: ["GF","DF","HP","Q"], instructions: "1. Grill chicken and pineapple rings.\n2. Slice and arrange on mixed leaves.\n3. Dress with lime and chili.", ingredients: [{ name: "Chicken breast", quantity: "300g", calories: 330, protein_g: 72, carbs_g: 0, fat_g: 4 }, { name: "Pineapple", quantity: "200g", calories: 100, protein_g: 1, carbs_g: 26, fat_g: 0 }, { name: "Mixed leaves", quantity: "100g", calories: 20, protein_g: 2, carbs_g: 4, fat_g: 0 }] },
  { name: "Waldorf Chicken Salad", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 15, cook_time_minutes: 0, calories_per_serving: 340, protein_g: 32, carbs_g: 18, fat_g: 16, dietary_tags: ["GF","HP","N"], instructions: "1. Shred cooked chicken.\n2. Mix with apple, celery, grapes and walnuts.\n3. Dress with yogurt and lemon.\n4. Serve on lettuce.", ingredients: [{ name: "Cooked chicken", quantity: "300g", calories: 330, protein_g: 72, carbs_g: 0, fat_g: 4 }, { name: "Apple", quantity: "1", calories: 95, protein_g: 0, carbs_g: 25, fat_g: 0 }, { name: "Walnuts", quantity: "30g", calories: 196, protein_g: 5, carbs_g: 4, fat_g: 20 }] },
  { name: "Tuna & Quinoa Toss Salad", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 380, protein_g: 35, carbs_g: 32, fat_g: 12, dietary_tags: ["GF","DF","HP"], instructions: "1. Cook quinoa per instructions.\n2. Mix with tuna, cucumber, tomatoes and olives.\n3. Dress with lemon and olive oil.", ingredients: [{ name: "Tinned tuna", quantity: "200g", calories: 250, protein_g: 55, carbs_g: 0, fat_g: 2 }, { name: "Quinoa", quantity: "100g", calories: 120, protein_g: 4, carbs_g: 21, fat_g: 2 }, { name: "Cucumber", quantity: "½", calories: 8, protein_g: 0, carbs_g: 2, fat_g: 0 }] },
  { name: "Salmon & Couscous Salad", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 420, protein_g: 34, carbs_g: 35, fat_g: 16, dietary_tags: ["HP"], instructions: "1. Cook couscous per instructions.\n2. Pan-fry salmon for 4 minutes per side.\n3. Flake salmon over couscous with herbs and lemon.", ingredients: [{ name: "Salmon fillets", quantity: "2 x 150g", calories: 468, protein_g: 52, carbs_g: 0, fat_g: 28 }, { name: "Couscous", quantity: "100g", calories: 350, protein_g: 12, carbs_g: 72, fat_g: 1 }, { name: "Fresh herbs", quantity: "handful", calories: 5, protein_g: 0, carbs_g: 1, fat_g: 0 }] },
  { name: "Prawn & Mango Salad", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 15, cook_time_minutes: 5, calories_per_serving: 320, protein_g: 32, carbs_g: 22, fat_g: 12, dietary_tags: ["GF","DF","HP","Q"], instructions: "1. Arrange mixed leaves on plates.\n2. Top with prawns, mango and avocado.\n3. Drizzle with lime juice and chili.", ingredients: [{ name: "King prawns", quantity: "300g", calories: 300, protein_g: 60, carbs_g: 0, fat_g: 4 }, { name: "Mango", quantity: "1", calories: 135, protein_g: 1, carbs_g: 35, fat_g: 1 }, { name: "Avocado", quantity: "1", calories: 234, protein_g: 3, carbs_g: 12, fat_g: 21 }] },
  { name: "Spicy Tuna Stuffed Avocado", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 0, calories_per_serving: 340, protein_g: 28, carbs_g: 10, fat_g: 22, dietary_tags: ["GF","DF","HP","LC","Q"], instructions: "1. Mix tuna with onion, lemon and sriracha.\n2. Halve avocados.\n3. Fill with tuna mix.", ingredients: [{ name: "Tinned tuna", quantity: "160g", calories: 200, protein_g: 44, carbs_g: 0, fat_g: 2 }, { name: "Avocado", quantity: "2", calories: 468, protein_g: 6, carbs_g: 24, fat_g: 42 }, { name: "Sriracha", quantity: "1 tsp", calories: 5, protein_g: 0, carbs_g: 1, fat_g: 0 }] },
  { name: "Chicken & Quinoa Power Bowl", pack: "high-protein", category: "lunch", servings: 2, prep_time_minutes: 10, cook_time_minutes: 20, calories_per_serving: 460, protein_g: 42, carbs_g: 38, fat_g: 16, dietary_tags: ["GF","DF","HP"], instructions: "1. Cook quinoa and roast sweet potato.\n2. Grill and slice chicken.\n3. Assemble bowls with kale, drizzle tahini.", ingredients: [{ name: "Chicken breast", quantity: "300g", calories: 330, protein_g: 72, carbs_g: 0, fat_g: 4 }, { name: "Quinoa", quantity: "100g", calories: 368, protein_g: 14, carbs_g: 64, fat_g: 6 }, { name: "Sweet potato", quantity: "150g", calories: 129, protein_g: 2, carbs_g: 30, fat_g: 0 }] },
  // HIGH-PROTEIN DINNER
  { name: "Post-Workout Potato Pancakes with Cottage Cheese", pack: "high-protein", category: "dinner", servings: 1, prep_time_minutes: 10, cook_time_minutes: 12, calories_per_serving: 380, protein_g: 28, carbs_g: 42, fat_g: 10, dietary_tags: ["GF","HP","V","Q"], instructions: "1. Grate potato, mix with egg.\n2. Fry pancakes until golden.\n3. Top with cottage cheese and chives.", ingredients: [{ name: "Potato", quantity: "1 large", calories: 168, protein_g: 4, carbs_g: 38, fat_g: 0 }, { name: "Egg", quantity: "1", calories: 78, protein_g: 6, carbs_g: 1, fat_g: 5 }, { name: "Cottage cheese", quantity: "150g", calories: 123, protein_g: 17, carbs_g: 5, fat_g: 4 }] },
  { name: "Miso Salmon with Zucchini Noodles", pack: "high-protein", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 420, protein_g: 38, carbs_g: 12, fat_g: 24, dietary_tags: ["GF","DF","HP","LC","Q"], instructions: "1. Glaze salmon with miso and honey.\n2. Bake at 200°C for 12 minutes.\n3. Spiralize zucchini and toss with sesame.\n4. Serve together.", ingredients: [{ name: "Salmon fillets", quantity: "2 x 180g", calories: 560, protein_g: 62, carbs_g: 0, fat_g: 34 }, { name: "Miso paste", quantity: "2 tbsp", calories: 34, protein_g: 2, carbs_g: 4, fat_g: 1 }, { name: "Zucchini", quantity: "2", calories: 34, protein_g: 2, carbs_g: 6, fat_g: 1 }] },
  { name: "Moroccan Cod & Bulgur Salad", pack: "high-protein", category: "dinner", servings: 2, prep_time_minutes: 15, cook_time_minutes: 20, calories_per_serving: 380, protein_g: 36, carbs_g: 32, fat_g: 12, dietary_tags: ["DF","HP"], instructions: "1. Season cod with Moroccan spices.\n2. Pan-fry 4 minutes per side.\n3. Cook bulgur, mix with herbs, lemon and pomegranate.\n4. Serve together.", ingredients: [{ name: "Cod fillets", quantity: "2 x 200g", calories: 360, protein_g: 80, carbs_g: 0, fat_g: 2 }, { name: "Bulgur wheat", quantity: "100g", calories: 342, protein_g: 12, carbs_g: 76, fat_g: 1 }, { name: "Pomegranate", quantity: "½", calories: 66, protein_g: 1, carbs_g: 16, fat_g: 1 }] },
  { name: "Turkey & Broccoli Stir Fry", pack: "high-protein", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 20, calories_per_serving: 494, protein_g: 42, carbs_g: 56, fat_g: 16, dietary_tags: ["GF","DF","HP","Q"], instructions: "1. Cook noodles per package.\n2. Stir-fry turkey and broccoli.\n3. Add soy sauce and ginger.\n4. Toss with noodles.", ingredients: [{ name: "Black rice noodles", quantity: "100g", calories: 360, protein_g: 8, carbs_g: 78, fat_g: 1 }, { name: "Turkey fillet", quantity: "200g", calories: 220, protein_g: 46, carbs_g: 0, fat_g: 2 }, { name: "Broccoli", quantity: "1 head", calories: 55, protein_g: 4, carbs_g: 11, fat_g: 1 }] },
  { name: "Cajun Beef Lettuce Tacos", pack: "high-protein", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 380, protein_g: 38, carbs_g: 12, fat_g: 20, dietary_tags: ["GF","DF","HP","LC","Q"], instructions: "1. Brown beef with Cajun seasoning.\n2. Separate lettuce into cups.\n3. Fill with beef, tomatoes, avocado. Add lime.", ingredients: [{ name: "Lean beef mince", quantity: "300g", calories: 510, protein_g: 60, carbs_g: 0, fat_g: 30 }, { name: "Iceberg lettuce", quantity: "1 head", calories: 14, protein_g: 1, carbs_g: 3, fat_g: 0 }, { name: "Avocado", quantity: "½", calories: 117, protein_g: 1, carbs_g: 6, fat_g: 11 }] },
  { name: "Chicken & Sweet Potato Curry", pack: "high-protein", category: "dinner", servings: 4, prep_time_minutes: 15, cook_time_minutes: 30, calories_per_serving: 420, protein_g: 38, carbs_g: 35, fat_g: 14, dietary_tags: ["GF","DF","HP"], instructions: "1. Sauté onion, garlic and curry paste.\n2. Add chicken and cook 5 minutes.\n3. Add sweet potato and coconut milk. Simmer 20 minutes.\n4. Stir in spinach.", ingredients: [{ name: "Chicken breast", quantity: "500g", calories: 550, protein_g: 120, carbs_g: 0, fat_g: 6 }, { name: "Sweet potato", quantity: "300g", calories: 258, protein_g: 5, carbs_g: 60, fat_g: 0 }, { name: "Coconut milk", quantity: "200ml", calories: 380, protein_g: 4, carbs_g: 6, fat_g: 38 }] },
  { name: "Lemon Herb Chicken Skewers", pack: "high-protein", category: "dinner", servings: 4, prep_time_minutes: 15, cook_time_minutes: 12, calories_per_serving: 280, protein_g: 42, carbs_g: 5, fat_g: 10, dietary_tags: ["GF","DF","HP","LC","Q"], instructions: "1. Marinate chicken in lemon, garlic and herbs.\n2. Thread onto skewers with peppers.\n3. Grill 10-12 minutes.", ingredients: [{ name: "Chicken breast", quantity: "600g", calories: 660, protein_g: 144, carbs_g: 0, fat_g: 7 }, { name: "Lemon", quantity: "2", calories: 16, protein_g: 0, carbs_g: 5, fat_g: 0 }, { name: "Red bell pepper", quantity: "2", calories: 62, protein_g: 2, carbs_g: 12, fat_g: 0 }] },
  { name: "Baked Cod with Pesto Crust", pack: "high-protein", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 20, calories_per_serving: 310, protein_g: 40, carbs_g: 4, fat_g: 14, dietary_tags: ["GF","HP","LC","Q"], instructions: "1. Spread pesto on cod.\n2. Bake at 200°C for 18-20 minutes.\n3. Serve with green beans.", ingredients: [{ name: "Cod fillets", quantity: "2 x 200g", calories: 360, protein_g: 80, carbs_g: 0, fat_g: 2 }, { name: "Green pesto", quantity: "2 tbsp", calories: 160, protein_g: 4, carbs_g: 4, fat_g: 14 }, { name: "Green beans", quantity: "200g", calories: 62, protein_g: 4, carbs_g: 14, fat_g: 0 }] },
  { name: "Beef & Vegetable Stir Fry", pack: "high-protein", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 15, calories_per_serving: 450, protein_g: 40, carbs_g: 30, fat_g: 18, dietary_tags: ["DF","HP","Q"], instructions: "1. Cook rice noodles.\n2. Sear beef, stir-fry vegetables.\n3. Add soy sauce. Toss with noodles.", ingredients: [{ name: "Sirloin steak", quantity: "300g", calories: 510, protein_g: 62, carbs_g: 0, fat_g: 28 }, { name: "Mixed vegetables", quantity: "300g", calories: 75, protein_g: 5, carbs_g: 15, fat_g: 1 }, { name: "Rice noodles", quantity: "100g", calories: 360, protein_g: 3, carbs_g: 80, fat_g: 0 }] },
  { name: "Greek Chicken Traybake", pack: "high-protein", category: "dinner", servings: 4, prep_time_minutes: 15, cook_time_minutes: 35, calories_per_serving: 380, protein_g: 42, carbs_g: 18, fat_g: 16, dietary_tags: ["GF","HP"], instructions: "1. Toss chicken with olive oil, oregano and lemon.\n2. Roast with onion, tomatoes and olives at 200°C for 35 minutes.\n3. Crumble feta over.", ingredients: [{ name: "Chicken thighs", quantity: "8", calories: 920, protein_g: 112, carbs_g: 0, fat_g: 48 }, { name: "Feta cheese", quantity: "100g", calories: 264, protein_g: 14, carbs_g: 4, fat_g: 21 }, { name: "Kalamata olives", quantity: "100g", calories: 115, protein_g: 1, carbs_g: 6, fat_g: 11 }] },
  { name: "Turkey Meatballs in Tomato Sauce", pack: "high-protein", category: "dinner", servings: 4, prep_time_minutes: 15, cook_time_minutes: 25, calories_per_serving: 350, protein_g: 38, carbs_g: 20, fat_g: 12, dietary_tags: ["GF","DF","HP"], instructions: "1. Shape turkey mince into meatballs.\n2. Brown, then simmer in tomato sauce for 15 minutes.\n3. Serve with zucchini noodles.", ingredients: [{ name: "Turkey mince", quantity: "500g", calories: 550, protein_g: 110, carbs_g: 0, fat_g: 10 }, { name: "Tinned tomatoes", quantity: "400g", calories: 80, protein_g: 4, carbs_g: 16, fat_g: 0 }, { name: "Zucchini", quantity: "1", calories: 17, protein_g: 1, carbs_g: 3, fat_g: 0 }] },
  { name: "Harissa Chicken with Roasted Vegetables", pack: "high-protein", category: "dinner", servings: 4, prep_time_minutes: 15, cook_time_minutes: 35, calories_per_serving: 390, protein_g: 40, carbs_g: 22, fat_g: 16, dietary_tags: ["GF","DF","HP"], instructions: "1. Coat chicken in harissa.\n2. Toss vegetables in oil.\n3. Roast together at 200°C for 35 minutes.\n4. Serve with yogurt.", ingredients: [{ name: "Chicken breast", quantity: "600g", calories: 660, protein_g: 144, carbs_g: 0, fat_g: 7 }, { name: "Harissa paste", quantity: "3 tbsp", calories: 60, protein_g: 1, carbs_g: 6, fat_g: 3 }, { name: "Sweet potato", quantity: "300g", calories: 258, protein_g: 5, carbs_g: 60, fat_g: 0 }] },
  { name: "Baked Salmon with Asparagus", pack: "high-protein", category: "dinner", servings: 2, prep_time_minutes: 10, cook_time_minutes: 20, calories_per_serving: 420, protein_g: 40, carbs_g: 8, fat_g: 26, dietary_tags: ["GF","DF","HP","LC","Q"], instructions: "1. Place salmon and asparagus on tray.\n2. Drizzle with oil, scatter garlic and lemon.\n3. Bake at 200°C for 18-20 minutes.", ingredients: [{ name: "Salmon fillets", quantity: "2 x 180g", calories: 560, protein_g: 62, carbs_g: 0, fat_g: 34 }, { name: "Asparagus", quantity: "200g", calories: 40, protein_g: 4, carbs_g: 8, fat_g: 0 }, { name: "Lemon", quantity: "1", calories: 8, protein_g: 0, carbs_g: 3, fat_g: 0 }] },
  { name: "Jerk Chicken & Rice Bowl", pack: "high-protein", category: "dinner", servings: 2, prep_time_minutes: 15, cook_time_minutes: 25, calories_per_serving: 480, protein_g: 42, carbs_g: 48, fat_g: 12, dietary_tags: ["GF","DF","HP"], instructions: "1. Coat chicken in jerk seasoning.\n2. Grill chicken. Cook rice.\n3. Assemble with black beans and mango salsa.", ingredients: [{ name: "Chicken thighs", quantity: "400g", calories: 460, protein_g: 56, carbs_g: 0, fat_g: 24 }, { name: "Brown rice", quantity: "150g", calories: 540, protein_g: 12, carbs_g: 114, fat_g: 4 }, { name: "Black beans", quantity: "100g", calories: 130, protein_g: 9, carbs_g: 24, fat_g: 0 }] },
  // HIGH-PROTEIN SNACKS
  { name: "Cottage Cheese & Berry Bowl", pack: "high-protein", category: "snack", servings: 1, prep_time_minutes: 5, cook_time_minutes: 0, calories_per_serving: 220, protein_g: 24, carbs_g: 22, fat_g: 4, dietary_tags: ["GF","HP","V","Q"], instructions: "1. Spoon cottage cheese into bowl.\n2. Top with berries and pumpkin seeds.\n3. Drizzle with honey.", ingredients: [{ name: "Cottage cheese", quantity: "200g", calories: 164, protein_g: 22, carbs_g: 6, fat_g: 5 }, { name: "Mixed berries", quantity: "100g", calories: 45, protein_g: 1, carbs_g: 11, fat_g: 0 }, { name: "Pumpkin seeds", quantity: "1 tbsp", calories: 47, protein_g: 2, carbs_g: 1, fat_g: 4 }] },
  { name: "High Protein Energy Balls", pack: "high-protein", category: "snack", servings: 10, prep_time_minutes: 15, cook_time_minutes: 0, calories_per_serving: 120, protein_g: 8, carbs_g: 12, fat_g: 6, dietary_tags: ["GF","DF","HP","V","MP"], instructions: "1. Mix oats, protein powder, peanut butter, honey and chocolate chips.\n2. Roll into 10 balls.\n3. Refrigerate 30 minutes.", ingredients: [{ name: "Oats", quantity: "100g", calories: 370, protein_g: 12, carbs_g: 66, fat_g: 7 }, { name: "Protein powder", quantity: "2 scoops", calories: 240, protein_g: 48, carbs_g: 6, fat_g: 2 }, { name: "Peanut butter", quantity: "3 tbsp", calories: 282, protein_g: 12, carbs_g: 9, fat_g: 24 }] },
  { name: "Smoked Salmon & Cream Cheese Roll-Ups", pack: "high-protein", category: "snack", servings: 2, prep_time_minutes: 10, cook_time_minutes: 0, calories_per_serving: 220, protein_g: 22, carbs_g: 4, fat_g: 14, dietary_tags: ["GF","HP","LC","Q"], instructions: "1. Spread cream cheese on salmon slices.\n2. Add cucumber and dill.\n3. Roll up tightly.", ingredients: [{ name: "Smoked salmon", quantity: "150g", calories: 270, protein_g: 36, carbs_g: 0, fat_g: 14 }, { name: "Cream cheese", quantity: "60g", calories: 120, protein_g: 3, carbs_g: 2, fat_g: 12 }, { name: "Cucumber", quantity: "½", calories: 8, protein_g: 0, carbs_g: 2, fat_g: 0 }] },
  { name: "Chicken Satay Skewers", pack: "high-protein", category: "snack", servings: 4, prep_time_minutes: 15, cook_time_minutes: 10, calories_per_serving: 260, protein_g: 32, carbs_g: 8, fat_g: 12, dietary_tags: ["GF","DF","HP","Q","N"], instructions: "1. Make peanut sauce.\n2. Thread chicken onto skewers.\n3. Grill 8-10 minutes.\n4. Serve with sauce.", ingredients: [{ name: "Chicken breast", quantity: "400g", calories: 440, protein_g: 96, carbs_g: 0, fat_g: 5 }, { name: "Peanut butter", quantity: "2 tbsp", calories: 188, protein_g: 8, carbs_g: 6, fat_g: 16 }, { name: "Soy sauce", quantity: "2 tbsp", calories: 16, protein_g: 2, carbs_g: 2, fat_g: 0 }] },
  // HIGH-PROTEIN TREATS
  { name: "Protein Banana Ice Cream", pack: "high-protein", category: "treats", servings: 2, prep_time_minutes: 5, cook_time_minutes: 0, calories_per_serving: 180, protein_g: 15, carbs_g: 28, fat_g: 2, dietary_tags: ["GF","DF","HP","V","Q"], instructions: "1. Blend frozen bananas until crumbly.\n2. Add protein powder and almond milk.\n3. Blend until smooth. Serve immediately.", ingredients: [{ name: "Frozen bananas", quantity: "2 large", calories: 210, protein_g: 3, carbs_g: 54, fat_g: 1 }, { name: "Protein powder", quantity: "1 scoop", calories: 120, protein_g: 24, carbs_g: 3, fat_g: 1 }, { name: "Almond milk", quantity: "2-3 tbsp", calories: 8, protein_g: 0, carbs_g: 0, fat_g: 0 }] },
  { name: "Chocolate Protein Mousse", pack: "high-protein", category: "treats", servings: 2, prep_time_minutes: 10, cook_time_minutes: 0, calories_per_serving: 200, protein_g: 22, carbs_g: 12, fat_g: 8, dietary_tags: ["GF","HP","V","Q"], instructions: "1. Mix yogurt with cocoa and protein powder.\n2. Add honey.\n3. Top with shaved dark chocolate. Chill.", ingredients: [{ name: "Greek yogurt", quantity: "200g", calories: 118, protein_g: 20, carbs_g: 8, fat_g: 0 }, { name: "Cocoa powder", quantity: "2 tbsp", calories: 24, protein_g: 2, carbs_g: 6, fat_g: 2 }, { name: "Protein powder", quantity: "1 scoop", calories: 120, protein_g: 24, carbs_g: 3, fat_g: 1 }] },
  // HIGH-PROTEIN SMOOTHIES
  { name: "Berry Blast Protein Smoothie", pack: "high-protein", category: "smoothie", servings: 1, prep_time_minutes: 5, cook_time_minutes: 0, calories_per_serving: 280, protein_g: 30, carbs_g: 32, fat_g: 5, dietary_tags: ["GF","DF","HP","V","Q"], instructions: "1. Blend all ingredients until smooth.\n2. Serve immediately.", ingredients: [{ name: "Mixed berries", quantity: "150g", calories: 70, protein_g: 1, carbs_g: 16, fat_g: 1 }, { name: "Protein powder", quantity: "1 scoop", calories: 120, protein_g: 24, carbs_g: 3, fat_g: 1 }, { name: "Almond milk", quantity: "250ml", calories: 30, protein_g: 1, carbs_g: 1, fat_g: 3 }] },
  { name: "Tropical Protein Smoothie", pack: "high-protein", category: "smoothie", servings: 1, prep_time_minutes: 5, cook_time_minutes: 0, calories_per_serving: 310, protein_g: 28, carbs_g: 40, fat_g: 6, dietary_tags: ["GF","DF","HP","V","Q"], instructions: "1. Blend all ingredients until smooth.\n2. Serve immediately.", ingredients: [{ name: "Mango chunks", quantity: "100g", calories: 60, protein_g: 1, carbs_g: 15, fat_g: 0 }, { name: "Pineapple", quantity: "100g", calories: 50, protein_g: 1, carbs_g: 13, fat_g: 0 }, { name: "Protein powder", quantity: "1 scoop", calories: 120, protein_g: 24, carbs_g: 3, fat_g: 1 }] },
  { name: "Green Power Protein Smoothie", pack: "high-protein", category: "smoothie", servings: 1, prep_time_minutes: 5, cook_time_minutes: 0, calories_per_serving: 260, protein_g: 28, carbs_g: 28, fat_g: 6, dietary_tags: ["GF","DF","HP","V","Q"], instructions: "1. Blend all ingredients on high until smooth.\n2. Serve immediately.", ingredients: [{ name: "Spinach", quantity: "50g", calories: 12, protein_g: 1, carbs_g: 2, fat_g: 0 }, { name: "Banana", quantity: "1", calories: 105, protein_g: 1, carbs_g: 27, fat_g: 0 }, { name: "Protein powder", quantity: "1 scoop", calories: 120, protein_g: 24, carbs_g: 3, fat_g: 1 }] },
  { name: "Peanut Butter Chocolate Smoothie", pack: "high-protein", category: "smoothie", servings: 1, prep_time_minutes: 5, cook_time_minutes: 0, calories_per_serving: 350, protein_g: 32, carbs_g: 30, fat_g: 14, dietary_tags: ["GF","DF","HP","V","Q"], instructions: "1. Blend all ingredients until thick and creamy.\n2. Serve optionally topped with peanut butter.", ingredients: [{ name: "Protein powder (chocolate)", quantity: "1 scoop", calories: 120, protein_g: 24, carbs_g: 3, fat_g: 1 }, { name: "Peanut butter", quantity: "1 tbsp", calories: 94, protein_g: 4, carbs_g: 3, fat_g: 8 }, { name: "Banana", quantity: "1, frozen", calories: 105, protein_g: 1, carbs_g: 27, fat_g: 0 }] },
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceRoleKey);

    // Check if already seeded
    const { count } = await supabase
      .from("recipes")
      .select("*", { count: "exact", head: true })
      .eq("is_public", true)
      .is("user_id", null);

    if (count && count > 0) {
      return new Response(
        JSON.stringify({ message: `Already seeded with ${count} recipes. Skipping.` }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    let inserted = 0;
    let errors: string[] = [];

    for (const recipe of ALL_RECIPES) {
      const { data: recipeData, error: recipeError } = await supabase
        .from("recipes")
        .insert({
          name: recipe.name,
          pack: recipe.pack,
          category: recipe.category,
          servings: recipe.servings,
          prep_time_minutes: recipe.prep_time_minutes,
          cook_time_minutes: recipe.cook_time_minutes,
          calories_per_serving: recipe.calories_per_serving,
          protein_g: recipe.protein_g,
          carbs_g: recipe.carbs_g,
          fat_g: recipe.fat_g,
          dietary_tags: recipe.dietary_tags,
          instructions: recipe.instructions,
          is_public: true,
          user_id: null,
          image_url: null,
        })
        .select("id")
        .single();

      if (recipeError) {
        errors.push(`Recipe "${recipe.name}": ${recipeError.message}`);
        continue;
      }

      // Insert ingredients
      if (recipe.ingredients && recipe.ingredients.length > 0) {
        const ingredientRows = recipe.ingredients.map((ing: any, idx: number) => ({
          recipe_id: recipeData.id,
          name: ing.name,
          unit: ing.quantity,
          calories: ing.calories || null,
          protein_g: ing.protein_g || null,
          carbs_g: ing.carbs_g || null,
          fat_g: ing.fat_g || null,
          sort_order: idx,
        }));

        const { error: ingError } = await supabase
          .from("recipe_ingredients")
          .insert(ingredientRows);

        if (ingError) {
          errors.push(`Ingredients for "${recipe.name}": ${ingError.message}`);
        }
      }

      inserted++;
    }

    return new Response(
      JSON.stringify({
        message: `Seeded ${inserted} recipes successfully.`,
        total_attempted: ALL_RECIPES.length,
        errors: errors.length > 0 ? errors : undefined,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
