import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const RECIPES = [
  // === BREAKFASTS ===
  {
    name: 'Unbreakable Eggy Bread',
    description: 'Thick-cut French toast loaded with protein. Soaked in seasoned egg, pan-fried golden and served with a side of lean bacon.',
    instructions: '1. Beat eggs with a splash of milk, salt, pepper and a pinch of cinnamon.\n2. Soak thick slices of wholemeal bread in the egg mixture for 30 seconds each side.\n3. Heat a non-stick pan with a light spray of oil over medium heat.\n4. Cook each slice for 2-3 minutes per side until golden and set.\n5. Grill lean back bacon alongside.\n6. Serve stacked with bacon on top. Optional: drizzle of honey.',
    calories_per_serving: 380,
    protein_g: 32,
    carbs_g: 28,
    fat_g: 16,
    prep_time_minutes: 5,
    cook_time_minutes: 10,
    servings: 2,
    dietary_tags: ['high-protein'],
    category: 'Breakfast',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Eggs', quantity: 4, unit: 'large' },
      { name: 'Wholemeal Bread', quantity: 4, unit: 'slices' },
      { name: 'Milk', quantity: 50, unit: 'ml' },
      { name: 'Lean Back Bacon', quantity: 4, unit: 'rashers' },
      { name: 'Cinnamon', quantity: 0.5, unit: 'tsp' },
      { name: 'Salt', quantity: 1, unit: 'pinch' },
      { name: 'Cooking Spray', quantity: 1, unit: 'spray' },
    ],
  },
  {
    name: 'Unbreakable Chunky Egg',
    description: 'Soft-boiled eggs with thick-cut toast soldiers and butter. Simple, satisfying, protein-packed.',
    instructions: '1. Bring a pan of water to a rolling boil.\n2. Gently lower eggs in and boil for 6 minutes for a soft, runny yolk.\n3. While eggs cook, toast thick-cut wholemeal bread and cut into soldiers.\n4. Place eggs in egg cups, slice off the tops.\n5. Season with salt and pepper.\n6. Dip soldiers and enjoy.',
    calories_per_serving: 340,
    protein_g: 22,
    carbs_g: 30,
    fat_g: 14,
    prep_time_minutes: 2,
    cook_time_minutes: 6,
    servings: 1,
    dietary_tags: ['high-protein'],
    category: 'Breakfast',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Eggs', quantity: 3, unit: 'large' },
      { name: 'Wholemeal Bread', quantity: 2, unit: 'slices' },
      { name: 'Butter', quantity: 10, unit: 'g' },
      { name: 'Salt', quantity: 1, unit: 'pinch' },
      { name: 'Black Pepper', quantity: 1, unit: 'pinch' },
    ],
  },
  // === MAINS ===
  {
    name: 'Unbreakable Scouse',
    description: 'A hearty beef stew with root veg, slow-cooked until rich and tender. High protein, low fat, pure soul food.',
    instructions: '1. Dice beef into chunks and season with salt and pepper.\n2. Brown beef in a large pot with a spray of oil over high heat.\n3. Add diced onions and cook until softened.\n4. Add carrots, swede, turnip, and potatoes.\n5. Pour in beef stock, add bay leaves and thyme.\n6. Bring to a boil, then reduce to a simmer.\n7. Cover and cook for 2-3 hours until beef is melt-in-your-mouth tender.\n8. Season to taste. Serve with pickled beetroot and crusty bread.',
    calories_per_serving: 420,
    protein_g: 42,
    carbs_g: 35,
    fat_g: 10,
    prep_time_minutes: 20,
    cook_time_minutes: 180,
    servings: 4,
    dietary_tags: ['high-protein', 'low-fat'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Lean Beef Stewing Steak', quantity: 600, unit: 'g' },
      { name: 'Potato', quantity: 400, unit: 'g' },
      { name: 'Carrot', quantity: 200, unit: 'g' },
      { name: 'Swede', quantity: 200, unit: 'g' },
      { name: 'Onion', quantity: 2, unit: 'medium' },
      { name: 'Beef Stock', quantity: 800, unit: 'ml' },
      { name: 'Bay Leaves', quantity: 2, unit: 'leaves' },
      { name: 'Thyme', quantity: 1, unit: 'tsp' },
      { name: 'Salt', quantity: 1, unit: 'tsp' },
      { name: 'Black Pepper', quantity: 0.5, unit: 'tsp' },
    ],
  },
  {
    name: 'Unbreakable Chicken & Barley Soup',
    description: 'A thick, warming chicken and pearl barley soup. Packed with protein and slow-release carbs to keep you fuelled.',
    instructions: '1. Heat a large pot and add diced chicken breast. Cook until browned.\n2. Add diced onion, carrot, celery and cook for 5 minutes.\n3. Add pearl barley, chicken stock, thyme and bay leaf.\n4. Bring to a boil then simmer for 40-45 minutes until barley is tender.\n5. Season with salt and pepper.\n6. Serve with crusty wholemeal bread.',
    calories_per_serving: 350,
    protein_g: 38,
    carbs_g: 32,
    fat_g: 6,
    prep_time_minutes: 15,
    cook_time_minutes: 45,
    servings: 4,
    dietary_tags: ['high-protein', 'low-fat'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Chicken Breast', quantity: 500, unit: 'g' },
      { name: 'Pearl Barley', quantity: 150, unit: 'g' },
      { name: 'Carrot', quantity: 150, unit: 'g' },
      { name: 'Celery', quantity: 100, unit: 'g' },
      { name: 'Onion', quantity: 1, unit: 'medium' },
      { name: 'Chicken Stock', quantity: 1000, unit: 'ml' },
      { name: 'Thyme', quantity: 1, unit: 'tsp' },
      { name: 'Bay Leaves', quantity: 1, unit: 'leaf' },
    ],
  },
  {
    name: 'Unbreakable Pea, Lentil & Ham Soup',
    description: 'A thick, hearty pea and ham soup with added lentils for extra protein. A proper winter warmer.',
    instructions: '1. Soak split peas overnight or for at least 4 hours. Drain.\n2. In a large pot, add the gammon joint and cover with water. Bring to a boil and simmer for 1 hour.\n3. Remove gammon, shred the meat, discard fat and bone.\n4. Return shredded ham to the pot with split peas, red lentils, diced carrot, celery and onion.\n5. Add stock and simmer for 45-60 minutes until peas are soft and soup is thick.\n6. Season with pepper (ham provides salt). Serve hot.',
    calories_per_serving: 380,
    protein_g: 36,
    carbs_g: 40,
    fat_g: 8,
    prep_time_minutes: 20,
    cook_time_minutes: 120,
    servings: 6,
    dietary_tags: ['high-protein', 'low-fat'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Gammon Joint', quantity: 500, unit: 'g' },
      { name: 'Split Peas', quantity: 200, unit: 'g' },
      { name: 'Red Lentils', quantity: 100, unit: 'g' },
      { name: 'Carrot', quantity: 150, unit: 'g' },
      { name: 'Celery', quantity: 100, unit: 'g' },
      { name: 'Onion', quantity: 1, unit: 'medium' },
      { name: 'Chicken Stock', quantity: 1200, unit: 'ml' },
      { name: 'Black Pepper', quantity: 1, unit: 'tsp' },
    ],
  },
  {
    name: 'Unbreakable Sunday Roast Chicken',
    description: 'The classic Sunday roast with lean roast chicken, crispy roast potatoes, steamed veg and proper gravy.',
    instructions: '1. Preheat oven to 200°C.\n2. Season chicken breast with salt, pepper, garlic powder and a drizzle of olive oil.\n3. Roast for 25-30 minutes until cooked through.\n4. Par-boil potatoes for 10 minutes, drain and rough up edges. Spray with oil, season and roast for 40 minutes.\n5. Steam broccoli, carrots and peas.\n6. Make gravy from pan juices with a little flour and stock.\n7. Plate up and serve.',
    calories_per_serving: 480,
    protein_g: 45,
    carbs_g: 42,
    fat_g: 12,
    prep_time_minutes: 15,
    cook_time_minutes: 45,
    servings: 2,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Chicken Breast', quantity: 400, unit: 'g' },
      { name: 'Potato', quantity: 400, unit: 'g' },
      { name: 'Broccoli', quantity: 150, unit: 'g' },
      { name: 'Carrot', quantity: 100, unit: 'g' },
      { name: 'Frozen Peas', quantity: 80, unit: 'g' },
      { name: 'Chicken Stock', quantity: 200, unit: 'ml' },
      { name: 'Olive Oil', quantity: 1, unit: 'tbsp' },
      { name: 'Garlic Powder', quantity: 1, unit: 'tsp' },
      { name: 'Plain Flour', quantity: 1, unit: 'tbsp' },
    ],
  },
  {
    name: 'Unbreakable Sunday Roast Beef',
    description: 'Lean roast beef with Yorkshire pudding, roast potatoes and seasonal veg. The king of Sunday dinners.',
    instructions: '1. Preheat oven to 220°C.\n2. Season beef topside with salt, pepper and mustard powder. Sear in a hot pan.\n3. Roast for 20 mins per 500g + 20 mins for medium. Rest for 15 mins.\n4. Par-boil and roast potatoes as above.\n5. Make Yorkshire puddings: whisk eggs, flour and milk. Pour into hot oiled muffin tins. Bake at 220°C for 20 mins.\n6. Steam veg. Make gravy from pan juices.\n7. Carve beef thin and serve.',
    calories_per_serving: 520,
    protein_g: 48,
    carbs_g: 40,
    fat_g: 16,
    prep_time_minutes: 20,
    cook_time_minutes: 90,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Beef Topside', quantity: 800, unit: 'g' },
      { name: 'Potato', quantity: 600, unit: 'g' },
      { name: 'Eggs', quantity: 2, unit: 'large' },
      { name: 'Plain Flour', quantity: 100, unit: 'g' },
      { name: 'Milk', quantity: 150, unit: 'ml' },
      { name: 'Broccoli', quantity: 200, unit: 'g' },
      { name: 'Carrot', quantity: 150, unit: 'g' },
      { name: 'Beef Stock', quantity: 300, unit: 'ml' },
      { name: 'Mustard Powder', quantity: 1, unit: 'tsp' },
    ],
  },
  {
    name: 'Unbreakable Sunday Roast Lamb',
    description: 'Tender roast lamb leg with mint sauce, roast potatoes and greens. A proper Sunday treat.',
    instructions: '1. Preheat oven to 200°C.\n2. Score lamb leg and stud with garlic and rosemary. Season well.\n3. Roast for 25 mins per 500g for medium. Rest 15 mins.\n4. Roast potatoes as standard.\n5. Steam green beans, broccoli and peas.\n6. Make mint sauce: finely chop mint, mix with vinegar and a touch of sugar.\n7. Make gravy from pan juices. Carve and serve.',
    calories_per_serving: 510,
    protein_g: 44,
    carbs_g: 38,
    fat_g: 18,
    prep_time_minutes: 15,
    cook_time_minutes: 90,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Lamb Leg', quantity: 1000, unit: 'g' },
      { name: 'Potato', quantity: 600, unit: 'g' },
      { name: 'Garlic', quantity: 4, unit: 'cloves' },
      { name: 'Fresh Rosemary', quantity: 3, unit: 'sprigs' },
      { name: 'Fresh Mint', quantity: 20, unit: 'g' },
      { name: 'White Wine Vinegar', quantity: 2, unit: 'tbsp' },
      { name: 'Green Beans', quantity: 150, unit: 'g' },
      { name: 'Broccoli', quantity: 150, unit: 'g' },
    ],
  },
  {
    name: 'Unbreakable Hotpot',
    description: 'Lean lamb layered with sliced potatoes and onions, slow-baked until golden. Comfort food at its finest.',
    instructions: '1. Preheat oven to 170°C.\n2. Brown diced lean lamb in a hot pan. Set aside.\n3. Layer sliced onions, lamb, sliced carrots and seasoning in a casserole dish.\n4. Top with overlapping thin potato slices.\n5. Pour in lamb/beef stock until it just reaches the potatoes.\n6. Brush potato tops with a little melted butter.\n7. Cover and bake for 2 hours. Uncover for last 30 minutes to crisp potatoes.\n8. Serve with pickled red cabbage.',
    calories_per_serving: 440,
    protein_g: 38,
    carbs_g: 40,
    fat_g: 12,
    prep_time_minutes: 25,
    cook_time_minutes: 150,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Lean Lamb Neck Fillet', quantity: 500, unit: 'g' },
      { name: 'Potato', quantity: 600, unit: 'g' },
      { name: 'Onion', quantity: 2, unit: 'medium' },
      { name: 'Carrot', quantity: 150, unit: 'g' },
      { name: 'Lamb Stock', quantity: 500, unit: 'ml' },
      { name: 'Butter', quantity: 15, unit: 'g' },
      { name: 'Thyme', quantity: 1, unit: 'tsp' },
      { name: 'Bay Leaves', quantity: 2, unit: 'leaves' },
    ],
  },
  {
    name: 'Unbreakable Corned Beef Hash',
    description: 'Crispy pan-fried corned beef hash with onion, potato and a fried egg on top. A kitchen staple.',
    instructions: '1. Boil diced potatoes until just tender, drain.\n2. Heat a large frying pan with spray oil.\n3. Fry diced onion until soft.\n4. Add cubed corned beef and potatoes.\n5. Press down and cook without stirring for 5 minutes to get a crispy base.\n6. Flip sections and crisp the other side.\n7. Meanwhile, fry eggs.\n8. Serve hash topped with fried eggs, season with salt and pepper. Add HP sauce.',
    calories_per_serving: 420,
    protein_g: 30,
    carbs_g: 35,
    fat_g: 18,
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 2,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Corned Beef', quantity: 200, unit: 'g' },
      { name: 'Potato', quantity: 300, unit: 'g' },
      { name: 'Onion', quantity: 1, unit: 'medium' },
      { name: 'Eggs', quantity: 2, unit: 'large' },
      { name: 'Cooking Spray', quantity: 1, unit: 'spray' },
      { name: 'Black Pepper', quantity: 1, unit: 'pinch' },
    ],
  },
  {
    name: 'Unbreakable Chicken Scouse',
    description: 'A lighter take on the classic stew — chicken thigh with root veg. All the soul, extra lean.',
    instructions: '1. Dice chicken thighs (skin removed) and season.\n2. Brown in a large pot with spray oil.\n3. Add diced onion, carrot, swede, turnip and potato.\n4. Pour in chicken stock, add thyme and bay leaf.\n5. Bring to a boil then simmer for 1.5 hours.\n6. The potatoes will thicken the stew naturally.\n7. Season and serve with crusty bread.',
    calories_per_serving: 380,
    protein_g: 40,
    carbs_g: 32,
    fat_g: 8,
    prep_time_minutes: 15,
    cook_time_minutes: 90,
    servings: 4,
    dietary_tags: ['high-protein', 'low-fat'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Chicken Thigh (skinless)', quantity: 600, unit: 'g' },
      { name: 'Potato', quantity: 400, unit: 'g' },
      { name: 'Carrot', quantity: 150, unit: 'g' },
      { name: 'Swede', quantity: 150, unit: 'g' },
      { name: 'Onion', quantity: 2, unit: 'medium' },
      { name: 'Chicken Stock', quantity: 800, unit: 'ml' },
      { name: 'Thyme', quantity: 1, unit: 'tsp' },
    ],
  },
  {
    name: 'Unbreakable Liver & Onions',
    description: 'Pan-fried lamb liver with caramelised onions and rich gravy. Iron-packed and full of flavour.',
    instructions: '1. Slice liver and dust lightly with seasoned flour.\n2. In a large pan, slowly cook sliced onions in a little butter until deeply caramelised (20 mins).\n3. Remove onions and set aside.\n4. Flash-fry liver for 2 minutes each side (still pink inside).\n5. Add onions back, pour in stock and a splash of Worcestershire sauce.\n6. Simmer for 2 minutes to make gravy.\n7. Serve with mashed potato and steamed greens.',
    calories_per_serving: 400,
    protein_g: 38,
    carbs_g: 28,
    fat_g: 14,
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 2,
    dietary_tags: ['high-protein', 'iron-rich'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Lamb Liver', quantity: 300, unit: 'g' },
      { name: 'Onion', quantity: 2, unit: 'large' },
      { name: 'Plain Flour', quantity: 2, unit: 'tbsp' },
      { name: 'Butter', quantity: 15, unit: 'g' },
      { name: 'Beef Stock', quantity: 200, unit: 'ml' },
      { name: 'Worcestershire Sauce', quantity: 1, unit: 'tbsp' },
      { name: 'Potato', quantity: 300, unit: 'g' },
    ],
  },
  {
    name: 'Unbreakable Sausage & Mash',
    description: 'Lean turkey sausages with creamy mash and onion gravy. Comfort classic made lean.',
    instructions: '1. Grill or bake turkey sausages for 20 minutes until golden and cooked through.\n2. Boil potatoes until tender, drain and mash with a splash of milk and a knob of butter.\n3. For onion gravy: slowly cook sliced onions until caramelised. Add stock and a teaspoon of gravy granules. Simmer until thick.\n4. Serve sausages on mash, smothered in onion gravy.\n5. Add steamed peas or green beans on the side.',
    calories_per_serving: 410,
    protein_g: 35,
    carbs_g: 40,
    fat_g: 12,
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 2,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Turkey Sausages', quantity: 4, unit: 'sausages' },
      { name: 'Potato', quantity: 400, unit: 'g' },
      { name: 'Onion', quantity: 2, unit: 'medium' },
      { name: 'Chicken Stock', quantity: 200, unit: 'ml' },
      { name: 'Milk', quantity: 30, unit: 'ml' },
      { name: 'Butter', quantity: 10, unit: 'g' },
      { name: 'Gravy Granules', quantity: 1, unit: 'tsp' },
      { name: 'Frozen Peas', quantity: 100, unit: 'g' },
    ],
  },
  {
    name: 'Unbreakable Steak & Gravy',
    description: 'Pan-seared lean steak in a rich onion and mushroom gravy. Protein-loaded pub grub.',
    instructions: '1. Season steaks with salt and pepper.\n2. Heat a cast-iron pan to smoking hot. Sear steaks 3-4 minutes each side for medium.\n3. Rest steaks for 5 minutes.\n4. In the same pan, cook sliced mushrooms and onion until softened.\n5. Add beef stock and a splash of Worcestershire sauce. Simmer until reduced and thick.\n6. Slice steaks and pour gravy over. Serve with chips or mash.',
    calories_per_serving: 450,
    protein_g: 48,
    carbs_g: 15,
    fat_g: 20,
    prep_time_minutes: 5,
    cook_time_minutes: 20,
    servings: 2,
    dietary_tags: ['high-protein', 'low-carb'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Lean Sirloin Steak', quantity: 400, unit: 'g' },
      { name: 'Mushroom', quantity: 150, unit: 'g' },
      { name: 'Onion', quantity: 1, unit: 'medium' },
      { name: 'Beef Stock', quantity: 200, unit: 'ml' },
      { name: 'Worcestershire Sauce', quantity: 1, unit: 'tbsp' },
      { name: 'Salt', quantity: 1, unit: 'pinch' },
      { name: 'Black Pepper', quantity: 1, unit: 'pinch' },
    ],
  },
  {
    name: 'Unbreakable Cottage Pie',
    description: 'Lean beef mince with veg in rich gravy, topped with creamy mash and baked golden. Pure comfort.',
    instructions: '1. Preheat oven to 200°C.\n2. Brown lean mince in a pan, drain any fat.\n3. Add diced onion, carrot, celery and peas. Cook 5 mins.\n4. Add beef stock, tomato purée, Worcestershire sauce and herbs. Simmer 20 mins.\n5. Boil and mash potatoes with a splash of milk.\n6. Spoon mince into an oven dish, top with mash. Fork the surface.\n7. Bake 25-30 minutes until golden and bubbling.',
    calories_per_serving: 450,
    protein_g: 40,
    carbs_g: 38,
    fat_g: 14,
    prep_time_minutes: 20,
    cook_time_minutes: 50,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Lean Beef Mince (5% fat)', quantity: 500, unit: 'g' },
      { name: 'Potato', quantity: 600, unit: 'g' },
      { name: 'Carrot', quantity: 100, unit: 'g' },
      { name: 'Celery', quantity: 50, unit: 'g' },
      { name: 'Onion', quantity: 1, unit: 'medium' },
      { name: 'Frozen Peas', quantity: 80, unit: 'g' },
      { name: 'Beef Stock', quantity: 300, unit: 'ml' },
      { name: 'Tomato Purée', quantity: 2, unit: 'tbsp' },
      { name: 'Worcestershire Sauce', quantity: 1, unit: 'tbsp' },
      { name: 'Milk', quantity: 30, unit: 'ml' },
    ],
  },
  {
    name: 'Unbreakable Fish Pie',
    description: 'Cod, salmon and prawns in a creamy sauce, topped with cheesy mash and baked golden.',
    instructions: '1. Preheat oven to 200°C.\n2. Poach fish fillets in milk with a bay leaf for 8 minutes. Remove fish and flake.\n3. Make sauce: melt butter, stir in flour, gradually add the poaching milk. Stir until thick.\n4. Fold in flaked fish and prawns. Season.\n5. Pour into an oven dish.\n6. Top with mashed potato mixed with a handful of grated cheddar.\n7. Bake 25-30 minutes until golden.',
    calories_per_serving: 460,
    protein_g: 42,
    carbs_g: 35,
    fat_g: 16,
    prep_time_minutes: 20,
    cook_time_minutes: 40,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Cod Fillet', quantity: 300, unit: 'g' },
      { name: 'Salmon Fillet', quantity: 200, unit: 'g' },
      { name: 'Prawns', quantity: 150, unit: 'g' },
      { name: 'Potato', quantity: 600, unit: 'g' },
      { name: 'Milk', quantity: 300, unit: 'ml' },
      { name: 'Butter', quantity: 20, unit: 'g' },
      { name: 'Plain Flour', quantity: 2, unit: 'tbsp' },
      { name: 'Cheddar Cheese', quantity: 40, unit: 'g' },
      { name: 'Bay Leaves', quantity: 1, unit: 'leaf' },
    ],
  },
  {
    name: 'Unbreakable Chippy Fish',
    description: 'Baked cod in a crispy breadcrumb coating with oven chips and mushy peas. Chippy-style, oven-baked.',
    instructions: '1. Preheat oven to 220°C.\n2. Cut potatoes into chips, spray with oil, season and bake 30 mins.\n3. Coat cod fillets: dip in flour, then beaten egg, then wholemeal breadcrumbs.\n4. Place on a baking tray, spray with oil. Bake alongside chips for 15-18 minutes.\n5. Heat mushy peas in a pan.\n6. Serve fish with chips, mushy peas and a wedge of lemon.',
    calories_per_serving: 440,
    protein_g: 40,
    carbs_g: 45,
    fat_g: 10,
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 2,
    dietary_tags: ['high-protein', 'low-fat'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Cod Fillet', quantity: 300, unit: 'g' },
      { name: 'Potato', quantity: 400, unit: 'g' },
      { name: 'Wholemeal Breadcrumbs', quantity: 60, unit: 'g' },
      { name: 'Eggs', quantity: 1, unit: 'large' },
      { name: 'Plain Flour', quantity: 2, unit: 'tbsp' },
      { name: 'Mushy Peas', quantity: 200, unit: 'g' },
      { name: 'Lemon', quantity: 1, unit: 'wedge' },
      { name: 'Cooking Spray', quantity: 1, unit: 'spray' },
    ],
  },
  {
    name: 'Unbreakable Chicken & Leek Pie',
    description: 'A creamy chicken and leek filling in a light filo pastry top. All the pie, less of the fat.',
    instructions: '1. Preheat oven to 200°C.\n2. Cook diced chicken breast in a pan until golden. Set aside.\n3. In the same pan, cook sliced leeks until softened.\n4. Stir in flour, then gradually add chicken stock and milk. Stir until thick.\n5. Add chicken back in with a tablespoon of mustard. Season.\n6. Pour into a pie dish. Layer filo sheets on top, scrunching slightly. Spray with oil.\n7. Bake 20-25 minutes until golden and crispy.',
    calories_per_serving: 400,
    protein_g: 42,
    carbs_g: 30,
    fat_g: 10,
    prep_time_minutes: 15,
    cook_time_minutes: 30,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Chicken Breast', quantity: 500, unit: 'g' },
      { name: 'Leek', quantity: 2, unit: 'medium' },
      { name: 'Filo Pastry', quantity: 4, unit: 'sheets' },
      { name: 'Chicken Stock', quantity: 200, unit: 'ml' },
      { name: 'Milk', quantity: 100, unit: 'ml' },
      { name: 'Plain Flour', quantity: 2, unit: 'tbsp' },
      { name: 'Dijon Mustard', quantity: 1, unit: 'tbsp' },
      { name: 'Cooking Spray', quantity: 1, unit: 'spray' },
    ],
  },
  {
    name: 'Unbreakable Turkey & Veg Pot',
    description: 'A one-pot turkey mince stew with sweet potato, peppers and beans. Quick, lean and filling.',
    instructions: '1. Brown turkey mince in a large pot.\n2. Add diced onion, garlic, red pepper and cook 3 mins.\n3. Add cubed sweet potato, tinned tomatoes, kidney beans and stock.\n4. Season with paprika, cumin, salt and pepper.\n5. Simmer for 25-30 minutes until sweet potato is tender.\n6. Serve with rice or crusty bread.',
    calories_per_serving: 380,
    protein_g: 38,
    carbs_g: 35,
    fat_g: 8,
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 4,
    dietary_tags: ['high-protein', 'low-fat'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Turkey Mince', quantity: 500, unit: 'g' },
      { name: 'Sweet Potato', quantity: 300, unit: 'g' },
      { name: 'Red Pepper', quantity: 1, unit: 'medium' },
      { name: 'Onion', quantity: 1, unit: 'medium' },
      { name: 'Garlic', quantity: 2, unit: 'cloves' },
      { name: 'Tinned Tomatoes', quantity: 400, unit: 'g' },
      { name: 'Kidney Beans', quantity: 200, unit: 'g' },
      { name: 'Chicken Stock', quantity: 200, unit: 'ml' },
      { name: 'Paprika', quantity: 1, unit: 'tsp' },
      { name: 'Cumin', quantity: 0.5, unit: 'tsp' },
    ],
  },
  {
    name: 'Unbreakable Blind Scouse',
    description: 'The meatless classic — a veggie stew packed with root veg and lentils for protein. What you eat when the fridge is bare and you still show up.',
    instructions: '1. Dice onion, carrot, swede, turnip and potato.\n2. Heat a large pot with spray oil. Cook onions until softened.\n3. Add all veg and red lentils.\n4. Pour in vegetable stock, add thyme and bay leaf.\n5. Bring to a boil then simmer for 1 hour until thick and veg is tender.\n6. The lentils and potatoes will naturally thicken the stew.\n7. Season generously. Serve with crusty bread and pickled beetroot.',
    calories_per_serving: 320,
    protein_g: 18,
    carbs_g: 52,
    fat_g: 4,
    prep_time_minutes: 15,
    cook_time_minutes: 60,
    servings: 4,
    dietary_tags: ['high-protein', 'vegan', 'low-fat'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Potato', quantity: 400, unit: 'g' },
      { name: 'Carrot', quantity: 200, unit: 'g' },
      { name: 'Swede', quantity: 200, unit: 'g' },
      { name: 'Turnip', quantity: 150, unit: 'g' },
      { name: 'Red Lentils', quantity: 100, unit: 'g' },
      { name: 'Onion', quantity: 2, unit: 'medium' },
      { name: 'Vegetable Stock', quantity: 800, unit: 'ml' },
      { name: 'Thyme', quantity: 1, unit: 'tsp' },
      { name: 'Bay Leaves', quantity: 2, unit: 'leaves' },
    ],
  },
  {
    name: 'Unbreakable Meat Pie',
    description: 'Lean turkey and chicken pie with mushrooms in a herb gravy, topped with golden puff pastry.',
    instructions: '1. Preheat oven to 200°C.\n2. Cook diced turkey and chicken breast in a hot pan until golden.\n3. Add sliced mushrooms and cook 3 mins.\n4. Stir in flour, then add stock gradually. Add thyme and parsley.\n5. Simmer until thick. Pour into pie dishes.\n6. Top with puff pastry lids, brush with beaten egg.\n7. Bake 25 minutes until pastry is golden and puffed.',
    calories_per_serving: 430,
    protein_g: 42,
    carbs_g: 28,
    fat_g: 16,
    prep_time_minutes: 15,
    cook_time_minutes: 35,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Turkey Breast', quantity: 300, unit: 'g' },
      { name: 'Chicken Breast', quantity: 200, unit: 'g' },
      { name: 'Mushroom', quantity: 150, unit: 'g' },
      { name: 'Puff Pastry', quantity: 200, unit: 'g' },
      { name: 'Chicken Stock', quantity: 300, unit: 'ml' },
      { name: 'Plain Flour', quantity: 2, unit: 'tbsp' },
      { name: 'Eggs', quantity: 1, unit: 'large' },
      { name: 'Thyme', quantity: 1, unit: 'tsp' },
      { name: 'Parsley', quantity: 1, unit: 'tbsp' },
    ],
  },
  {
    name: 'Unbreakable Pan Haggerty',
    description: 'Layers of potato, onion and cheese baked until golden. Added chicken for protein.',
    instructions: '1. Preheat oven to 190°C.\n2. Slice potatoes and onions very thinly.\n3. Shred cooked chicken breast.\n4. Layer in a greased oven dish: potato, onion, chicken, grated cheese. Repeat.\n5. Finish with a potato and cheese layer on top.\n6. Pour in a little stock so it just reaches the top layer.\n7. Cover with foil and bake 45 mins. Remove foil, bake 15 more mins until golden.\n8. Rest 5 mins before serving.',
    calories_per_serving: 420,
    protein_g: 36,
    carbs_g: 35,
    fat_g: 14,
    prep_time_minutes: 15,
    cook_time_minutes: 60,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Potato', quantity: 600, unit: 'g' },
      { name: 'Chicken Breast (cooked)', quantity: 300, unit: 'g' },
      { name: 'Onion', quantity: 2, unit: 'medium' },
      { name: 'Cheddar Cheese', quantity: 80, unit: 'g' },
      { name: 'Chicken Stock', quantity: 100, unit: 'ml' },
      { name: 'Butter', quantity: 10, unit: 'g' },
    ],
  },
  {
    name: 'Unbreakable Lobscouse',
    description: 'The original sailor\'s stew — a lighter, cleaner lamb and root veg slow-cook. Simple, honest, filling.',
    instructions: '1. Dice lean lamb and season well.\n2. Brown in a pot with spray oil. Remove and set aside.\n3. Cook diced onion, carrot and celery for 5 mins.\n4. Return lamb, add diced potato and lamb stock.\n5. Add a splash of Worcestershire sauce, thyme and bay leaf.\n6. Simmer for 2 hours until lamb is very tender.\n7. Crush some potato against the side of the pot to thicken.\n8. Serve with pickled red cabbage and bread.',
    calories_per_serving: 400,
    protein_g: 40,
    carbs_g: 30,
    fat_g: 12,
    prep_time_minutes: 15,
    cook_time_minutes: 120,
    servings: 4,
    dietary_tags: ['high-protein'],
    category: 'Main',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Lean Lamb Leg', quantity: 500, unit: 'g' },
      { name: 'Potato', quantity: 400, unit: 'g' },
      { name: 'Carrot', quantity: 150, unit: 'g' },
      { name: 'Celery', quantity: 100, unit: 'g' },
      { name: 'Onion', quantity: 2, unit: 'medium' },
      { name: 'Lamb Stock', quantity: 800, unit: 'ml' },
      { name: 'Worcestershire Sauce', quantity: 1, unit: 'tbsp' },
      { name: 'Thyme', quantity: 1, unit: 'tsp' },
      { name: 'Bay Leaves', quantity: 2, unit: 'leaves' },
    ],
  },
  {
    name: 'Unbreakable Wet Nelly',
    description: 'Classic bread pudding reimagined with protein. Warm, sweet, and surprisingly high in protein.',
    instructions: '1. Preheat oven to 180°C.\n2. Tear bread into chunks and place in a bowl. Pour over warm milk and let soak 10 minutes.\n3. Mix in beaten eggs, protein powder, mixed spice, and dried fruit.\n4. Pour into a greased baking dish.\n5. Bake 35-40 minutes until set and golden.\n6. Serve warm with a drizzle of honey or a dollop of Greek yoghurt.',
    calories_per_serving: 340,
    protein_g: 28,
    carbs_g: 42,
    fat_g: 8,
    prep_time_minutes: 15,
    cook_time_minutes: 40,
    servings: 6,
    dietary_tags: ['high-protein'],
    category: 'Desserts',
    pack: 'High Protein',
    is_public: true,
    ingredients: [
      { name: 'Wholemeal Bread', quantity: 300, unit: 'g' },
      { name: 'Milk', quantity: 400, unit: 'ml' },
      { name: 'Eggs', quantity: 4, unit: 'large' },
      { name: 'Vanilla Protein Powder', quantity: 60, unit: 'g' },
      { name: 'Mixed Dried Fruit', quantity: 100, unit: 'g' },
      { name: 'Mixed Spice', quantity: 1, unit: 'tsp' },
      { name: 'Honey', quantity: 2, unit: 'tbsp' },
    ],
  },
];

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const results: string[] = [];

    for (const recipe of RECIPES) {
      const { ingredients, ...recipeData } = recipe;

      // Check if recipe already exists
      const { data: existing } = await supabase
        .from('recipes')
        .select('id')
        .eq('name', recipeData.name)
        .eq('is_public', true)
        .maybeSingle();

      if (existing) {
        results.push(`SKIP: ${recipeData.name} (exists)`);
        continue;
      }

      // Insert recipe (no user_id = system recipe)
      const { data: newRecipe, error: recipeErr } = await supabase
        .from('recipes')
        .insert({ ...recipeData, user_id: null })
        .select('id')
        .single();

      if (recipeErr) {
        results.push(`ERROR: ${recipeData.name} - ${recipeErr.message}`);
        continue;
      }

      // Insert ingredients
      if (ingredients && ingredients.length > 0) {
        const ingredientRows = ingredients.map((ing, idx) => ({
          recipe_id: newRecipe.id,
          name: ing.name,
          quantity: ing.quantity,
          unit: ing.unit,
          sort_order: idx,
        }));

        const { error: ingErr } = await supabase
          .from('recipe_ingredients')
          .insert(ingredientRows);

        if (ingErr) {
          results.push(`WARN: ${recipeData.name} ingredients failed - ${ingErr.message}`);
        }
      }

      results.push(`OK: ${recipeData.name}`);
    }

    return new Response(
      JSON.stringify({ success: true, results, total: RECIPES.length }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
