import type { UnitAssessment } from '../types';

export const level2Unit1Assessment: UnitAssessment = {
  unitNumber: 1,
  title: 'Understanding the Body — Unit Assessment',
  passMarkPercent: 80,
  questions: [
    {
      type: 'multiple_choice',
      question: 'Which plane of movement does a squat primarily occur in?',
      options: ['Frontal plane', 'Transverse plane', 'Sagittal plane', 'Coronal plane'],
      correctAnswer: 2,
      explanation: 'Squats involve flexion and extension at the hip and knee, which are forward-and-backward movements in the sagittal plane.',
    },
    {
      type: 'multiple_choice',
      question: 'What does the term "posterior" mean in anatomical language?',
      options: ['Towards the front', 'Towards the back', 'Towards the midline', 'Away from the midline'],
      correctAnswer: 1,
      explanation: 'Posterior refers to the back of the body. For example, the hamstrings are on the posterior side of the thigh.',
    },
    {
      type: 'multiple_choice',
      question: 'Which type of joint allows movement in all directions?',
      options: ['Hinge joint', 'Pivot joint', 'Ball-and-socket joint', 'Gliding joint'],
      correctAnswer: 2,
      explanation: 'Ball-and-socket joints (shoulder, hip) allow the greatest range of movement in all directions.',
    },
    {
      type: 'multiple_choice',
      question: 'What is an eccentric muscle contraction?',
      options: [
        'The muscle shortens under load',
        'The muscle produces force without changing length',
        'The muscle lengthens under load',
        'The muscle relaxes completely',
      ],
      correctAnswer: 2,
      explanation: 'Eccentric contraction occurs when a muscle lengthens while under tension — such as lowering a dumbbell during a bicep curl.',
    },
    {
      type: 'multiple_choice',
      question: 'Which muscle group is the antagonist to the quadriceps?',
      options: ['Calves', 'Glutes', 'Hamstrings', 'Hip flexors'],
      correctAnswer: 2,
      explanation: 'The hamstrings oppose the quadriceps. When the quads extend the knee, the hamstrings must relax, and vice versa.',
    },
    {
      type: 'multiple_choice',
      question: 'What is stroke volume?',
      options: [
        'The number of heartbeats per minute',
        'The amount of blood pumped per heartbeat',
        'The total blood volume in the body',
        'The speed at which blood flows through arteries',
      ],
      correctAnswer: 1,
      explanation: 'Stroke volume is the amount of blood the heart pumps out with each contraction. It increases with cardiovascular training.',
    },
    {
      type: 'multiple_choice',
      question: 'Which energy system is primarily used during a heavy single repetition on the deadlift?',
      options: ['Aerobic system', 'Anaerobic glycolysis', 'ATP-PC system', 'Lactic acid system'],
      correctAnswer: 2,
      explanation: 'Maximal efforts lasting under 10 seconds rely primarily on the ATP-PC (phosphocreatine) system for immediate energy.',
    },
    {
      type: 'multiple_choice',
      question: 'How long does the ATP-PC system typically provide energy for?',
      options: ['30-60 seconds', '2-5 minutes', '8-12 seconds', '15-30 minutes'],
      correctAnswer: 2,
      explanation: 'The ATP-PC system provides immediate, high-intensity energy for approximately 8-12 seconds before it needs to be replenished.',
    },
    {
      type: 'scenario',
      question: 'Based on this scenario, which training adjustment would be most appropriate?',
      scenario: 'A gym user performs 5 sets of 3 reps on bench press with 90 seconds rest between sets. They report that their performance drops significantly after the second set and they cannot complete their target reps.',
      options: [
        'Reduce the weight by 20%',
        'Increase rest periods to 3-5 minutes',
        'Switch to higher reps with lighter weight',
        'Add more warm-up sets',
      ],
      correctAnswer: 1,
      explanation: 'Heavy sets of 3 reps primarily use the ATP-PC system, which requires 2-5 minutes to fully recover. With only 90 seconds rest, the system hasn\'t replenished, leading to performance decline.',
    },
    {
      type: 'scenario',
      question: 'What is the most likely cause of this issue?',
      scenario: 'A trainee only performs bench press, bicep curls, and shoulder press in every session. After 6 months, they develop rounded shoulders and upper back pain.',
      options: [
        'They are not training heavy enough',
        'They have a muscular imbalance — too much anterior work, not enough posterior',
        'They need to stretch more before training',
        'Their nutrition is inadequate',
      ],
      correctAnswer: 1,
      explanation: 'All three exercises target anterior (front) muscles. Without balanced posterior work (rows, rear delt work, back exercises), the front muscles become dominant, pulling the shoulders forward and causing postural issues.',
    },
    {
      type: 'multiple_choice',
      question: 'What is a chronic adaptation of regular cardiovascular training?',
      options: [
        'Increased resting heart rate',
        'Decreased capillary density',
        'Increased stroke volume',
        'Decreased VO2 max',
      ],
      correctAnswer: 2,
      explanation: 'Regular cardiovascular training increases stroke volume — the heart becomes stronger and pumps more blood per beat, which lowers resting heart rate.',
    },
    {
      type: 'multiple_choice',
      question: 'Which of the following is a function of the skeletal system?',
      options: [
        'Producing hormones',
        'Storing fat for energy',
        'Protecting vital organs',
        'Regulating body temperature',
      ],
      correctAnswer: 2,
      explanation: 'The skeletal system protects vital organs — for example, the ribcage protects the lungs and heart, and the skull protects the brain.',
    },
  ],
};
