import type { UnitAssessment } from '../types';

export const level2Unit3Assessment: UnitAssessment = {
  unitNumber: 3,
  title: 'Unit 3 Assessment: Introduction to Exercise',
  passMarkPercent: 80,
  questions: [
    // ─── CHAPTER 1: Types of Training (6 questions) ──────────────
    {
      type: 'multiple_choice',
      question: 'Which type of training primarily develops muscular strength, hypertrophy, and muscular endurance through working against an external force?',
      options: [
        'Cardiovascular training',
        'Resistance training',
        'Flexibility training',
        'Balance training',
      ],
      correctAnswer: 1,
      explanation: 'Resistance training involves working muscles against an external force (weights, bands, bodyweight) and is the primary method for developing muscular strength, hypertrophy, and muscular endurance.',
    },
    {
      type: 'multiple_choice',
      question: 'What is EPOC, and which training type produces the greatest EPOC response?',
      options: [
        'Excess Post-exercise Oxygen Consumption — steady-state cardio',
        'Elevated Protein Oxidation Cycle — resistance training',
        'Excess Post-exercise Oxygen Consumption — HIIT',
        'Enhanced Peripheral Oxygen Capacity — flexibility training',
      ],
      correctAnswer: 2,
      explanation: 'EPOC (Excess Post-exercise Oxygen Consumption) refers to increased calorie burn after exercise. HIIT produces the greatest EPOC response due to its high metabolic demand.',
    },
    {
      type: 'multiple_choice',
      question: 'Which of the following is NOT a physiological benefit of cardiovascular training?',
      options: [
        'Increased capillary density in working muscles',
        'Reduced resting heart rate over time',
        'Increased maximal force production',
        'Improved cardiac output and stroke volume',
      ],
      correctAnswer: 2,
      explanation: 'Increased maximal force production is a benefit of resistance training, not cardiovascular training. Cardio training improves heart function, blood flow, and aerobic capacity.',
    },
    {
      type: 'scenario',
      question: 'Which training approach would be most appropriate and why?',
      scenario: 'You want to improve general health, lose body fat, and build some muscle. You have 4 days per week available to train.',
      options: [
        'Four HIIT sessions per week for maximum calorie burn',
        'Four steady-state cardio sessions of 60 minutes each',
        '2-3 resistance training sessions plus 1-2 cardiovascular sessions',
        'Four flexibility sessions to improve movement quality first',
      ],
      correctAnswer: 2,
      explanation: 'A balanced approach of 2-3 resistance sessions (for muscle building and metabolic rate) plus 1-2 cardio sessions (for cardiovascular health and fat loss) addresses all three goals. HIIT 4x/week would be excessive; cardio-only would not build muscle.',
    },
    {
      type: 'multiple_choice',
      question: 'Why is HIIT not suitable for daily use in most programmes?',
      options: [
        'It does not produce cardiovascular adaptations',
        'It only develops flexibility, not fitness',
        'It places high recovery demands on the body and can lead to overtraining',
        'It requires specialist equipment not available in most gyms',
      ],
      correctAnswer: 2,
      explanation: 'HIIT places significant stress on the neuromuscular and metabolic systems, requiring adequate recovery between sessions. Daily HIIT without sufficient recovery can lead to overtraining, fatigue, and injury.',
    },
    {
      type: 'multiple_choice',
      question: 'Which statement about flexibility training is correct?',
      options: [
        'Flexibility training is only needed for gymnasts and dancers',
        'Flexibility training reduces muscle stiffness and can decrease the risk of strains',
        'Flexibility training replaces the need for warm-ups before resistance training',
        'Flexibility training builds muscle mass when performed at high volumes',
      ],
      correctAnswer: 1,
      explanation: 'Flexibility training reduces muscle stiffness, improves movement quality, and decreases the risk of strains and overuse injuries. It is beneficial for all populations, not just athletes.',
    },

    // ─── CHAPTER 2: Warm-Up & Cool-Down (6 questions) ────────────
    {
      type: 'multiple_choice',
      question: 'What does the "R" in the RAMP warm-up protocol stand for?',
      options: [
        'Resistance',
        'Raise',
        'Recovery',
        'Range',
      ],
      correctAnswer: 1,
      explanation: 'R stands for Raise — the phase that elevates heart rate, blood flow, core temperature, and respiration rate through low-to-moderate intensity cardiovascular activity.',
    },
    {
      type: 'multiple_choice',
      question: 'Why is dynamic stretching preferred over static stretching during a warm-up?',
      options: [
        'Dynamic stretching is easier to perform',
        'Static stretching can temporarily reduce force production before training',
        'Dynamic stretching builds more muscle than static stretching',
        'Static stretching increases heart rate too much before training',
      ],
      correctAnswer: 1,
      explanation: 'Research shows static stretching before training can temporarily reduce strength and power output by 5-10%. Dynamic stretching increases blood flow, ROM, and neuromuscular readiness without this force-reduction effect.',
    },
    {
      type: 'multiple_choice',
      question: 'Which phase of RAMP involves exercises like glute bridges and band pull-aparts?',
      options: [
        'Raise',
        'Activate',
        'Mobilise',
        'Potentiate',
      ],
      correctAnswer: 1,
      explanation: 'The Activate phase targets key muscle groups that will be used in the main session, "waking up" muscles that may be underactive. Glute bridges and band pull-aparts are common activation exercises.',
    },
    {
      type: 'scenario',
      question: 'Design the Potentiate phase of your warm-up. Which approach is most appropriate?',
      scenario: 'You are preparing for a heavy lower body session starting with barbell back squats at 100kg working weight.',
      options: [
        '10 minutes of static hamstring stretches',
        'Bodyweight squats → goblet squats → empty bar squats → ramping sets (60kg → 80kg → 90kg)',
        'Sprint intervals on the treadmill for 5 minutes',
        'Upper body activation work with band pull-aparts',
      ],
      correctAnswer: 1,
      explanation: 'The Potentiate phase bridges into the main session with movements that progressively load the upcoming exercises. Starting with bodyweight and ramping up through goblet squats to progressively heavier barbell sets prepares the neuromuscular system specifically for heavy squats.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the primary purpose of a cool-down?',
      options: [
        'To build additional muscle through stretching',
        'To increase heart rate for extra calorie burn',
        'To gradually reduce heart rate and begin recovery processes',
        'To test maximal flexibility while muscles are warm',
      ],
      correctAnswer: 2,
      explanation: 'The cool-down facilitates the transition from exercise back to rest, gradually reducing heart rate, aiding removal of metabolic by-products, and initiating recovery through low-intensity activity and static stretching.',
    },
    {
      type: 'multiple_choice',
      question: 'Which physiological effect does NOT occur during an effective warm-up?',
      options: [
        'Increased synovial fluid production in joints',
        'Elevated core and muscle temperature',
        'Increased maximal muscle hypertrophy',
        'Enhanced nervous system activation',
      ],
      correctAnswer: 2,
      explanation: 'Muscle hypertrophy is a long-term adaptation to resistance training, not an acute effect of warming up. Warm-ups increase temperature, synovial fluid, blood flow, and nervous system readiness.',
    },

    // ─── CHAPTER 3: Resistance Training Fundamentals (6 questions) ─
    {
      type: 'multiple_choice',
      question: 'According to the rep range continuum, which rep range is most commonly associated with hypertrophy training?',
      options: [
        '1–5 reps',
        '6–12 reps',
        '15–25 reps',
        '30–50 reps',
      ],
      correctAnswer: 1,
      explanation: 'The 6-12 rep range at 65-85% of 1RM is most commonly associated with hypertrophy (muscle growth), balancing mechanical tension and metabolic stress for optimal muscle-building stimulus.',
    },
    {
      type: 'multiple_choice',
      question: 'In tempo notation 3-1-2-0, what does the "3" represent?',
      options: [
        'Three sets of the exercise',
        'A 3-second concentric (lifting) phase',
        'A 3-second eccentric (lowering) phase',
        'A 3-second pause at the top',
      ],
      correctAnswer: 2,
      explanation: 'In tempo notation, the first digit represents the eccentric (lowering) phase. So 3-1-2-0 means: 3 seconds lowering, 1 second pause at the bottom, 2 seconds lifting, 0 seconds pause at the top.',
    },
    {
      type: 'multiple_choice',
      question: 'Why are rest periods of 3–5 minutes recommended for strength training (1–5 reps)?',
      options: [
        'To allow the muscles to cool down completely',
        'To allow full ATP-PC recovery for maximal force production on the next set',
        'To increase metabolic stress and promote hypertrophy',
        'To reduce the total training volume of the session',
      ],
      correctAnswer: 1,
      explanation: 'Strength training relies heavily on the ATP-PC energy system, which takes 3-5 minutes to fully replenish. Shorter rest would compromise force production on subsequent sets.',
    },
    {
      type: 'scenario',
      question: 'What is the most likely issue and solution?',
      scenario: 'You are performing bench press with a target of 8-10 reps. You consistently complete 15 reps before feeling fatigued.',
      options: [
        'You are overtraining — reduce to 2 sessions per week',
        'The load is too light — increase weight so that 10 reps is genuinely challenging',
        'You should slow your tempo to 10-0-10-0',
        'You are naturally suited to endurance training and should switch to cardio',
      ],
      correctAnswer: 1,
      explanation: 'If you can easily complete 15 reps when targeting 8-10, the load is too light. The weight should be increased so that completing 10 reps is difficult but achievable with good form.',
    },
    {
      type: 'multiple_choice',
      question: 'What does RIR 2 mean in the context of resistance training?',
      options: [
        'You should rest for 2 minutes between sets',
        'You should perform 2 repetitions per set',
        'You could complete 2 more reps before reaching failure',
        'You have completed 2 rounds of the exercise',
      ],
      correctAnswer: 2,
      explanation: 'RIR (Reps in Reserve) indicates how many additional reps could be performed before failure. RIR 2 means you finish the set with approximately 2 reps remaining before you would fail.',
    },
    {
      type: 'multiple_choice',
      question: 'For a beginner starting resistance training, which set range per exercise is most appropriate?',
      options: [
        '1 set per exercise',
        '2–3 sets per exercise',
        '5–6 sets per exercise',
        '8–10 sets per exercise',
      ],
      correctAnswer: 1,
      explanation: 'Beginners respond well to lower training volumes. 2-3 sets per exercise provides sufficient stimulus for adaptation while allowing adequate recovery and technique practice.',
    },

    // ─── CHAPTER 4: Cardiovascular Training Principles (6 questions)
    {
      type: 'multiple_choice',
      question: 'What does the FITT principle stand for in cardiovascular training prescription?',
      options: [
        'Force, Intensity, Tension, Time',
        'Frequency, Intensity, Time, Type',
        'Flexibility, Interval, Training, Technique',
        'Fatigue, Interval, Threshold, Tempo',
      ],
      correctAnswer: 1,
      explanation: 'FITT stands for Frequency (how often), Intensity (how hard), Time (how long), and Type (what modality). It provides a simple framework for prescribing cardiovascular training.',
    },
    {
      type: 'multiple_choice',
      question: 'Heart rate Zone 2 (60–70% MHR) is primarily associated with which adaptation?',
      options: [
        'Maximal power output',
        'Anaerobic threshold development',
        'Aerobic base building and fat oxidation',
        'VO₂ max improvement',
      ],
      correctAnswer: 2,
      explanation: 'Zone 2 training develops the aerobic base, improves fat oxidation as a fuel source, and builds cardiac efficiency. It is characterised by a conversational pace and is the foundation of cardiovascular fitness.',
    },
    {
      type: 'scenario',
      question: 'How would you estimate your maximum heart rate and calculate your Zone 2 range?',
      scenario: 'You are 40 years old and want to train in heart rate Zone 2 for aerobic base building. You do not have a lab-tested MHR.',
      options: [
        'MHR = 220 - 40 = 180 bpm; Zone 2 = 108-126 bpm (60-70% of 180)',
        'MHR = 200 - 40 = 160 bpm; Zone 2 = 80-100 bpm (50-60% of 160)',
        'MHR = 220 + 40 = 260 bpm; Zone 2 = 156-182 bpm (60-70% of 260)',
        'MHR = 180 bpm (fixed); Zone 2 = 90-108 bpm (50-60% of 180)',
      ],
      correctAnswer: 0,
      explanation: 'The standard formula for estimating MHR is 220 minus age: 220 - 40 = 180 bpm. Zone 2 is 60-70% of MHR: 108-126 bpm. While this formula has limitations, it provides a practical starting point.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the "80/20 rule" in cardiovascular training?',
      options: [
        '80% of training should be resistance and 20% cardio',
        '80% of cardio should be low intensity and 20% high intensity',
        '80% of gains come from the first 20% of effort',
        '80% of the session should be warm-up and 20% working sets',
      ],
      correctAnswer: 1,
      explanation: 'The 80/20 rule suggests 80% of cardiovascular training should be at low intensity (Zone 2) and 20% at high intensity (Zones 4-5). This polarised approach is well-supported by research and used by elite endurance athletes.',
    },
    {
      type: 'multiple_choice',
      question: 'According to UK physical activity guidelines, what is the minimum recommended weekly moderate-intensity cardiovascular activity for adults?',
      options: [
        '75 minutes',
        '100 minutes',
        '150 minutes',
        '300 minutes',
      ],
      correctAnswer: 2,
      explanation: 'UK guidelines recommend at least 150 minutes of moderate-intensity cardiovascular activity per week (or 75 minutes of vigorous-intensity activity) alongside resistance training on at least two days.',
    },
    {
      type: 'multiple_choice',
      question: 'Using the Talk Test, which description indicates you are working at moderate intensity?',
      options: [
        'You can sing a song without difficulty',
        'You can speak in short sentences but not hold a full conversation',
        'You cannot say more than a word or two',
        'You can hold a comfortable, flowing conversation',
      ],
      correctAnswer: 1,
      explanation: 'At moderate intensity, you can speak in short sentences but would struggle to hold a full, flowing conversation. Comfortable conversation indicates low intensity; inability to speak indicates high/maximal intensity.',
    },

    // ─── CHAPTER 5: Flexibility & Mobility (6 questions) ─────────
    {
      type: 'multiple_choice',
      question: 'What is the key difference between flexibility and mobility?',
      options: [
        'Flexibility is active; mobility is passive',
        'Flexibility is the passive ability of a muscle to lengthen; mobility is the active ability to control movement through a range of motion',
        'Flexibility applies to muscles; mobility applies only to cardiovascular fitness',
        'There is no difference — the terms are interchangeable',
      ],
      correctAnswer: 1,
      explanation: 'Flexibility is passive muscle lengthening (e.g., someone pushing your leg into a stretch), while mobility is the active ability to move a joint through its ROM with control, requiring strength and coordination at end ranges.',
    },
    {
      type: 'multiple_choice',
      question: 'How long should a static stretch typically be held for optimal flexibility gains?',
      options: [
        '2–5 seconds',
        '15–30 seconds',
        '60–90 seconds',
        '3–5 minutes',
      ],
      correctAnswer: 1,
      explanation: 'Research supports holding static stretches for 15-30 seconds, with 2-4 repetitions per muscle group. This duration is sufficient to improve muscle length without excessive discomfort.',
    },
    {
      type: 'multiple_choice',
      question: 'What does PNF stretching involve?',
      options: [
        'Bouncing in and out of a stretched position rapidly',
        'Alternating between muscle contraction and stretching to achieve greater ROM',
        'Holding a stretch for 5 minutes without movement',
        'Using electrical stimulation to lengthen muscles',
      ],
      correctAnswer: 1,
      explanation: 'PNF (Proprioceptive Neuromuscular Facilitation) uses the contract-relax method: the muscle is stretched, then isometrically contracted for 5-10 seconds, relaxed, and then stretched further. This produces the greatest acute ROM improvements.',
    },
    {
      type: 'scenario',
      question: 'What is the most likely limitation and appropriate intervention?',
      scenario: 'You cannot achieve a full-depth squat. Your heels rise off the floor and you lean excessively forward. You have adequate hip flexibility when tested passively.',
      options: [
        'Tight hamstrings — perform static hamstring stretches before squatting',
        'Limited ankle dorsiflexion — perform ankle mobility drills and consider heel-elevated squats',
        'Tight chest muscles — perform chest stretches',
        'Weak biceps — perform more arm curls',
      ],
      correctAnswer: 1,
      explanation: 'Heels rising and excessive forward lean in a squat commonly indicate limited ankle dorsiflexion. Ankle mobility drills (e.g., knee-to-wall test, banded ankle mobilisations) and heel-elevated squats can address this restriction.',
    },
    {
      type: 'multiple_choice',
      question: 'When is foam rolling most appropriately used?',
      options: [
        'Only after training, never before',
        'Pre-exercise or post-exercise — it does not reduce force production like static stretching',
        'Only when you are injured',
        'Only for competitive athletes, not general gym users',
      ],
      correctAnswer: 1,
      explanation: 'Foam rolling can be used pre-exercise (to improve ROM without the force-reduction effects of static stretching) or post-exercise (to aid recovery). It is appropriate for all populations.',
    },
    {
      type: 'multiple_choice',
      question: 'Which statement about mobility drills is correct?',
      options: [
        'Mobility drills are the same as static stretching',
        'Mobility drills develop the strength and coordination to use available range of motion',
        'Mobility drills should only be performed once per week',
        'Mobility drills replace the need for any warm-up',
      ],
      correctAnswer: 1,
      explanation: 'Mobility drills are active exercises that develop joint range of motion with control — requiring not just muscle length but strength, stability, and motor control. They differ from stretching which focuses primarily on passive muscle length.',
    },

    // ─── CHAPTER 6: Exercise Selection & Technique (6 questions) ──
    {
      type: 'multiple_choice',
      question: 'Which of the following is a compound exercise?',
      options: [
        'Bicep curl',
        'Barbell back squat',
        'Tricep pushdown',
        'Lateral raise',
      ],
      correctAnswer: 1,
      explanation: 'The barbell back squat is a compound (multi-joint) exercise involving the hip, knee, and ankle joints and multiple muscle groups. Bicep curls, tricep pushdowns, and lateral raises are all isolation (single-joint) exercises.',
    },
    {
      type: 'multiple_choice',
      question: 'Which of the following is NOT one of the six fundamental movement patterns?',
      options: [
        'Push',
        'Hinge',
        'Rotation',
        'Carry',
      ],
      correctAnswer: 2,
      explanation: 'The six fundamental movement patterns are: Push, Pull, Squat, Hinge, Lunge, and Carry. Rotation is sometimes considered an additional pattern but is not one of the core six in most frameworks.',
    },
    {
      type: 'scenario',
      question: 'What is the most appropriate exercise selection approach?',
      scenario: 'You have never performed any free weight exercises. You want to develop leg strength for everyday activities.',
      options: [
        'Start with heavy barbell back squats at 80% of estimated 1RM',
        'Begin with bodyweight squats, progressing to goblet squats, then barbell squats as competence develops',
        'Only use leg press machines — free weights are too dangerous for beginners',
        'Start with single-leg pistol squats to build balance',
      ],
      correctAnswer: 1,
      explanation: 'Beginners should progress through a logical sequence: bodyweight → dumbbell/kettlebell → barbell. This builds competence, confidence, and movement quality before adding complexity and load.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the primary benefit of including unilateral exercises in a programme?',
      options: [
        'They allow heavier loads than bilateral exercises',
        'They are easier to learn than bilateral exercises',
        'They expose and correct left-right strength imbalances',
        'They only target the core muscles',
      ],
      correctAnswer: 2,
      explanation: 'Unilateral exercises work one limb at a time, exposing and helping to correct strength imbalances between sides. They also demand greater stabilisation, improving balance and proprioception.',
    },
    {
      type: 'multiple_choice',
      question: 'Knees caving inward (valgus) during a squat is commonly caused by which of the following?',
      options: [
        'Excessive chest flexibility',
        'Weak gluteus medius and poor hip stability',
        'Overactive hamstrings',
        'Excessive ankle mobility',
      ],
      correctAnswer: 1,
      explanation: 'Knee valgus (inward collapse) during squatting is commonly associated with weak gluteus medius (hip abductor), poor hip stability, and sometimes limited ankle dorsiflexion. Glute activation and strengthening exercises are a key corrective strategy.',
    },
    {
      type: 'multiple_choice',
      question: 'Why should compound exercises generally be placed before isolation exercises in a session?',
      options: [
        'Isolation exercises are more important and should be saved for last',
        'Compound exercises require more neuromuscular coordination and energy, so they should be performed when you are freshest',
        'It does not matter — exercise order has no effect on performance',
        'Isolation exercises serve as a warm-up for compound movements',
      ],
      correctAnswer: 1,
      explanation: 'Compound exercises involve multiple joints and muscle groups, requiring greater neuromuscular coordination, energy, and focus. Performing them first (when you are freshest) maximises performance and reduces injury risk.',
    },

    // ─── CHAPTER 7: Recovery & Adaptation (6 questions) ──────────
    {
      type: 'multiple_choice',
      question: 'What does the SAID principle state?',
      options: [
        'Sleep Always Improves Development',
        'Specific Adaptation to Imposed Demands',
        'Systematic Approach to Individual Design',
        'Strength And Intensity Determine results',
      ],
      correctAnswer: 1,
      explanation: 'SAID (Specific Adaptation to Imposed Demands) states that the body adapts specifically to the type of stress placed upon it. Train for strength → get stronger. Train for endurance → improve endurance.',
    },
    {
      type: 'multiple_choice',
      question: 'In the supercompensation model, when is the optimal time to perform the next training session?',
      options: [
        'During the fatigue phase, while the body is still recovering',
        'Exactly at baseline, before supercompensation occurs',
        'During the supercompensation window, when the body has adapted beyond baseline',
        'After the detraining phase, when fitness has declined',
      ],
      correctAnswer: 2,
      explanation: 'The optimal timing for the next session is during the supercompensation window — when the body has recovered and adapted beyond its previous baseline. Training too soon (fatigue) or too late (detraining) reduces the effectiveness of progressive training.',
    },
    {
      type: 'scenario',
      question: 'What is the most appropriate recommendation?',
      scenario: 'You are experiencing persistent fatigue, declining performance over 3 weeks, disturbed sleep, and increased irritability despite training consistently 6 days per week.',
      options: [
        'Increase training frequency to 7 days to push through the plateau',
        'Add a pre-workout supplement for more energy',
        'Implement a deload week and review sleep, nutrition, and overall recovery strategy',
        'Switch entirely to flexibility training for the next month',
      ],
      correctAnswer: 2,
      explanation: 'These symptoms indicate under-recovery or early overtraining. A deload week (reduced volume/intensity) combined with improved sleep, nutrition, and recovery strategies is the appropriate response — not more training stress.',
    },
    {
      type: 'multiple_choice',
      question: 'How many hours of sleep per night should adults aim for to optimise recovery?',
      options: [
        '4–5 hours',
        '5–6 hours',
        '7–9 hours',
        '10–12 hours',
      ],
      correctAnswer: 2,
      explanation: 'Adults should aim for 7-9 hours of quality sleep per night. During deep sleep, the body releases growth hormone, repairs tissue, consolidates motor learning, and restores the nervous system.',
    },
    {
      type: 'multiple_choice',
      question: 'What is a deload and how is it typically implemented?',
      options: [
        'A complete week off from all training',
        'A planned reduction of 40-60% in training volume while maintaining the training habit',
        'Switching from resistance training to only cardiovascular work',
        'Doubling training volume to shock the body into adaptation',
      ],
      correctAnswer: 1,
      explanation: 'A deload is a planned reduction in training volume and/or intensity (typically 40-60% reduction) lasting one week. Training continues but at reduced stress, allowing accumulated fatigue to dissipate while maintaining the training habit.',
    },
    {
      type: 'multiple_choice',
      question: 'Which of the following is NOT a method of progressive overload?',
      options: [
        'Increasing the weight lifted',
        'Adding more sets or reps over time',
        'Performing the same workout with the same load indefinitely',
        'Decreasing rest periods to increase training density',
      ],
      correctAnswer: 2,
      explanation: 'Progressive overload requires systematically increasing training demands over time. Performing the same workout indefinitely provides no progressive stimulus and will result in stagnation once the body has adapted.',
    },

    // ─── CHAPTER 8: Training for Special Populations (6 questions) ─
    {
      type: 'multiple_choice',
      question: 'For a complete beginner, which type of programme structure is most appropriate?',
      options: [
        'A 6-day body-part split with high volume',
        'Full-body sessions 2-3 times per week with lower volumes',
        'Daily HIIT sessions for maximum fat loss',
        'Only machine-based exercises for the first 12 months',
      ],
      correctAnswer: 1,
      explanation: 'Beginners respond best to full-body sessions 2-3 times per week with moderate volumes (2-3 sets per exercise). This frequency provides adequate stimulus and practice while allowing sufficient recovery.',
    },
    {
      type: 'multiple_choice',
      question: 'What is sarcopenia, and what is the primary countermeasure?',
      options: [
        'Age-related bone loss — calcium supplementation',
        'Age-related muscle mass loss — resistance training',
        'Age-related cardiovascular decline — steady-state cardio',
        'Age-related joint stiffness — daily yoga',
      ],
      correctAnswer: 1,
      explanation: 'Sarcopenia is the age-related loss of skeletal muscle mass and function. Resistance training is the primary evidence-based countermeasure, helping maintain muscle mass, strength, and functional capacity in older adults.',
    },
    {
      type: 'scenario',
      question: 'Which exercise should be avoided and why?',
      scenario: 'A pregnant woman in her second trimester wants to continue her resistance training programme. She currently performs barbell hip thrusts, standing overhead press, and supine (lying on back) bench press.',
      options: [
        'All exercises should be stopped — exercise is unsafe during pregnancy',
        'Supine bench press — lying on the back after the first trimester can compress the vena cava, reducing blood flow',
        'Standing overhead press — standing exercises are dangerous during pregnancy',
        'Hip thrusts — hip extension exercises are contraindicated in pregnancy',
      ],
      correctAnswer: 1,
      explanation: 'After the first trimester, supine (lying flat on the back) exercises should be avoided as the weight of the uterus can compress the inferior vena cava, potentially reducing blood flow. Incline bench press is a safe alternative.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the PAR-Q used for?',
      options: [
        'Measuring your 1 rep max on all exercises',
        'Screening for health conditions that may require medical clearance before exercise',
        'Calculating your macronutrient requirements',
        'Determining which training split is most appropriate',
      ],
      correctAnswer: 1,
      explanation: 'The Physical Activity Readiness Questionnaire (PAR-Q) is a standardised health screening tool that identifies individuals who may need medical clearance before beginning an exercise programme. It should be completed before starting a new training programme.',
    },
    {
      type: 'scenario',
      question: 'What is the most important action?',
      scenario: 'During a training session, a 55-year-old gym user suddenly experiences chest pain and shortness of breath during a set of squats.',
      options: [
        'Push through — it is probably just muscle soreness',
        'Stop the exercise immediately and seek medical assessment',
        'Switch to a lighter exercise and monitor',
        'Lie down and perform static stretches until it passes',
      ],
      correctAnswer: 1,
      explanation: 'Chest pain and sudden shortness of breath during exercise are potential signs of a cardiac event and require immediate cessation of exercise and medical attention. This is beyond anything that can be self-managed.',
    },
    {
      type: 'multiple_choice',
      question: 'What is the primary priority for postnatal exercise programming before returning to high-impact or heavy resistance training?',
      options: [
        'Achieving a calorie deficit for weight loss',
        'Returning to pre-pregnancy training loads as quickly as possible',
        'Pelvic floor rehabilitation and diastasis recti screening',
        'Performing sit-ups and crunches to rebuild core strength',
      ],
      correctAnswer: 2,
      explanation: 'Pelvic floor rehabilitation is the first priority postnatal. Diastasis recti (abdominal separation) should be screened before core-intensive exercises. Sit-ups and crunches should be avoided until diastasis has been assessed and addressed.',
    },
  ],
};
