import type { ChapterQuiz } from '../types';

export const unit1ChapterQuizzes: ChapterQuiz[] = [
  // ─── Chapter 1: Basic Anatomy for Training ───
  {
    unitNumber: 1,
    chapterNumber: 1,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Which anatomical plane divides the body into left and right halves?',
        options: ['Frontal plane', 'Sagittal plane', 'Transverse plane', 'Coronal plane'],
        correctAnswer: 1,
        explanation: 'The sagittal plane runs vertically from front to back, dividing the body into left and right sections.',
      },
      {
        type: 'multiple_choice',
        question: 'A bicep curl primarily occurs in which plane of movement?',
        options: ['Transverse plane', 'Frontal plane', 'Sagittal plane', 'Diagonal plane'],
        correctAnswer: 2,
        explanation: 'A bicep curl involves flexion at the elbow, which occurs in the sagittal plane.',
      },
      {
        type: 'multiple_choice',
        question: 'What does the term "posterior" mean in anatomical terminology?',
        options: ['Towards the front of the body', 'Towards the back of the body', 'Towards the midline', 'Away from the midline'],
        correctAnswer: 1,
        explanation: 'Posterior refers to the back of the body. For example, your hamstrings are on the posterior side of your thigh.',
      },
      {
        type: 'multiple_choice',
        question: 'Lateral raises primarily involve movement in which plane?',
        options: ['Sagittal plane', 'Transverse plane', 'Frontal plane', 'Horizontal plane'],
        correctAnswer: 2,
        explanation: 'Lateral raises involve abduction of the shoulder, which occurs in the frontal (coronal) plane.',
      },
      {
        type: 'scenario',
        question: 'Which directional term best describes the position of the shoulders relative to the hips?',
        scenario: 'You are labelling a body diagram for a training log and need to describe the position of different body parts.',
        options: ['Inferior', 'Lateral', 'Superior', 'Medial'],
        correctAnswer: 2,
        explanation: 'Superior means above or higher. The shoulders are superior to the hips.',
      },
      {
        type: 'multiple_choice',
        question: 'Which plane of movement would a Russian twist primarily occur in?',
        options: ['Sagittal plane', 'Frontal plane', 'Transverse plane', 'Vertical plane'],
        correctAnswer: 2,
        explanation: 'The transverse plane divides the body into upper and lower halves. Rotational movements like a Russian twist occur in this plane.',
      },
      {
        type: 'multiple_choice',
        question: 'What does "medial" mean in anatomical terminology?',
        options: ['Towards the outside of the body', 'Towards the midline of the body', 'Towards the head', 'Towards the feet'],
        correctAnswer: 1,
        explanation: 'Medial means closer to the midline of the body. For example, the inner thigh is medial to the outer thigh.',
      },
      {
        type: 'scenario',
        question: 'Which movement plane should you focus on to address this imbalance?',
        scenario: 'You notice your training programme only includes squats, lunges, and bicep curls — all forward-and-back movements.',
        options: ['More sagittal plane work', 'More frontal plane work', 'More sagittal and transverse work', 'No change needed'],
        correctAnswer: 1,
        explanation: 'All the listed exercises occur in the sagittal plane. Adding frontal plane movements (like lateral lunges or lateral raises) would create better balance.',
      },
      {
        type: 'multiple_choice',
        question: 'Which of the following is an example of a transverse plane exercise?',
        options: ['Squat', 'Lateral raise', 'Cable woodchop', 'Deadlift'],
        correctAnswer: 2,
        explanation: 'A cable woodchop involves rotation through the torso, making it a transverse plane movement.',
      },
      {
        type: 'multiple_choice',
        question: 'The term "anterior" refers to which side of the body?',
        options: ['The back', 'The front', 'The left side', 'The top'],
        correctAnswer: 1,
        explanation: 'Anterior means the front of the body. Your quadriceps are on the anterior side of your thigh.',
      },
    ],
  },

  // ─── Chapter 2: Joints and Movement ───
  {
    unitNumber: 1,
    chapterNumber: 2,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Which type of joint allows the greatest range of movement?',
        options: ['Hinge joint', 'Ball-and-socket joint', 'Pivot joint', 'Gliding joint'],
        correctAnswer: 1,
        explanation: 'Ball-and-socket joints (like the shoulder and hip) allow movement in all planes and the greatest range of motion.',
      },
      {
        type: 'multiple_choice',
        question: 'The knee is classified as which type of synovial joint?',
        options: ['Ball-and-socket', 'Pivot', 'Hinge', 'Saddle'],
        correctAnswer: 2,
        explanation: 'The knee is a hinge joint, primarily allowing flexion and extension.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the primary role of synovial fluid in a joint?',
        options: ['To strengthen the joint capsule', 'To reduce friction and nourish cartilage', 'To connect muscle to bone', 'To store energy for movement'],
        correctAnswer: 1,
        explanation: 'Synovial fluid lubricates the joint, reducing friction between cartilage surfaces and providing nutrients.',
      },
      {
        type: 'multiple_choice',
        question: 'Which movement describes bringing a limb closer to the midline of the body?',
        options: ['Abduction', 'Adduction', 'Extension', 'Circumduction'],
        correctAnswer: 1,
        explanation: 'Adduction is the movement of a limb towards the midline. For example, bringing your arm back to your side after a lateral raise.',
      },
      {
        type: 'scenario',
        question: 'What is the most likely cause of this discomfort?',
        scenario: 'You feel a clicking sensation in your shoulder during overhead pressing. There is no pain, but it happens every rep.',
        options: ['Torn muscle fibres', 'Synovial fluid movement or tendon gliding over bone', 'Fractured joint capsule', 'Excessive synovial fluid production'],
        correctAnswer: 1,
        explanation: 'Painless clicking during shoulder movements is commonly caused by synovial fluid shifting or tendons gliding over bony surfaces. It is usually harmless.',
      },
      {
        type: 'multiple_choice',
        question: 'What type of joint is found in the spine between vertebrae?',
        options: ['Ball-and-socket', 'Hinge', 'Gliding (plane)', 'Condyloid'],
        correctAnswer: 2,
        explanation: 'The facet joints between vertebrae are gliding (plane) joints, allowing small sliding movements that together create spinal flexibility.',
      },
      {
        type: 'multiple_choice',
        question: 'Which joint action occurs when you straighten your arm from a bent position?',
        options: ['Flexion', 'Extension', 'Rotation', 'Abduction'],
        correctAnswer: 1,
        explanation: 'Extension is the increase of the angle at a joint — straightening the arm is extension at the elbow.',
      },
      {
        type: 'scenario',
        question: 'Which approach best addresses this issue?',
        scenario: 'You struggle to reach full depth in a squat because your ankles feel tight and your heels lift off the ground.',
        options: ['Stop squatting — it is not safe', 'Improve ankle dorsiflexion through mobility work', 'Switch to only machine-based leg work', 'Add more weight to force depth'],
        correctAnswer: 1,
        explanation: 'Limited ankle dorsiflexion is a common barrier to squat depth. Targeted mobility work (calf stretches, ankle circles, elevated heel drills) improves this over time.',
      },
      {
        type: 'multiple_choice',
        question: 'What does "range of motion" (ROM) refer to?',
        options: ['The speed at which a joint moves', 'The full extent of movement available at a joint', 'The strength of the muscles around a joint', 'The number of joints involved in a movement'],
        correctAnswer: 1,
        explanation: 'Range of motion is the full extent of movement that a joint can achieve, from full flexion to full extension (or other relevant movements).',
      },
      {
        type: 'multiple_choice',
        question: 'Rotation at the hip joint is possible because it is a:',
        options: ['Hinge joint', 'Pivot joint', 'Ball-and-socket joint', 'Gliding joint'],
        correctAnswer: 2,
        explanation: 'The hip is a ball-and-socket joint, allowing flexion, extension, abduction, adduction, and rotation.',
      },
    ],
  },

  // ─── Chapter 3: Major Muscle Groups ───
  {
    unitNumber: 1,
    chapterNumber: 3,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Which muscle group is primarily responsible for extending the knee?',
        options: ['Hamstrings', 'Quadriceps', 'Glutes', 'Calves'],
        correctAnswer: 1,
        explanation: 'The quadriceps (front of the thigh) are the primary knee extensors, working during squats, leg extensions, and walking upstairs.',
      },
      {
        type: 'multiple_choice',
        question: 'The latissimus dorsi is located in which area of the body?',
        options: ['Front of the shoulder', 'Upper back and sides', 'Lower leg', 'Front of the thigh'],
        correctAnswer: 1,
        explanation: 'The latissimus dorsi (lats) are large muscles spanning the mid and lower back, responsible for pulling movements.',
      },
      {
        type: 'multiple_choice',
        question: 'Which muscle is the primary hip extensor?',
        options: ['Rectus femoris', 'Gluteus maximus', 'Tibialis anterior', 'Deltoid'],
        correctAnswer: 1,
        explanation: 'The gluteus maximus is the largest muscle in the body and the primary driver of hip extension — essential for squats, deadlifts, and sprinting.',
      },
      {
        type: 'scenario',
        question: 'Which muscle group should you prioritise strengthening?',
        scenario: 'You experience lower back discomfort after long periods of sitting. A physiotherapist suggests your glutes may be underactive.',
        options: ['Quadriceps', 'Hamstrings', 'Gluteus maximus and medius', 'Calves'],
        correctAnswer: 2,
        explanation: 'Weak or underactive glutes often contribute to lower back pain because the lower back compensates for poor hip extension. Strengthening the glutes reduces this compensation.',
      },
      {
        type: 'multiple_choice',
        question: 'Which muscle group acts as the antagonist to the quadriceps?',
        options: ['Calves', 'Hip flexors', 'Hamstrings', 'Glutes'],
        correctAnswer: 2,
        explanation: 'The hamstrings oppose the quadriceps — when the quads extend the knee, the hamstrings act as the antagonist. This agonist-antagonist relationship is key to balanced training.',
      },
      {
        type: 'multiple_choice',
        question: 'The deltoid muscle is responsible for which primary movement?',
        options: ['Elbow flexion', 'Shoulder abduction and flexion', 'Spinal rotation', 'Knee extension'],
        correctAnswer: 1,
        explanation: 'The deltoids are the cap-shaped muscles on your shoulders, responsible for raising your arms in various directions.',
      },
      {
        type: 'multiple_choice',
        question: 'Which muscle group is located on the posterior side of the upper arm?',
        options: ['Biceps brachii', 'Triceps brachii', 'Brachialis', 'Forearm flexors'],
        correctAnswer: 1,
        explanation: 'The triceps are on the back of the upper arm and are responsible for elbow extension (straightening the arm).',
      },
      {
        type: 'scenario',
        question: 'What adjustment would create better muscular balance?',
        scenario: 'Your weekly programme includes bench press, push-ups, and shoulder press, but no pulling movements.',
        options: ['Add more chest exercises', 'Add rows and pull-ups to balance push and pull', 'Remove shoulder press', 'Add only bicep curls'],
        correctAnswer: 1,
        explanation: 'A balanced programme should include roughly equal pushing and pulling volume to prevent muscular imbalances and postural issues.',
      },
      {
        type: 'multiple_choice',
        question: 'The core muscles include which of the following?',
        options: ['Only the rectus abdominis (six-pack)', 'Transverse abdominis, obliques, rectus abdominis, and erector spinae', 'Only the obliques', 'Only the lower back muscles'],
        correctAnswer: 1,
        explanation: 'The core is a group of muscles including the deep transverse abdominis, the obliques, the rectus abdominis, and the erector spinae — working together for stability.',
      },
      {
        type: 'multiple_choice',
        question: 'Which exercise primarily targets the hamstrings?',
        options: ['Leg extension', 'Romanian deadlift', 'Leg press', 'Calf raise'],
        correctAnswer: 1,
        explanation: 'The Romanian deadlift places significant stretch and load on the hamstrings through hip hinge mechanics.',
      },
    ],
  },

  // ─── Chapter 4: The Cardiovascular System ───
  {
    unitNumber: 1,
    chapterNumber: 4,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'What is the primary function of the cardiovascular system?',
        options: ['To digest food', 'To transport oxygen, nutrients, and waste products around the body', 'To produce hormones', 'To protect against infection'],
        correctAnswer: 1,
        explanation: 'The cardiovascular system circulates blood, delivering oxygen and nutrients to working tissues and removing waste products like carbon dioxide.',
      },
      {
        type: 'multiple_choice',
        question: 'What happens to your heart rate during steady-state cardiovascular exercise?',
        options: ['It decreases', 'It stays the same as at rest', 'It increases and reaches a plateau', 'It fluctuates randomly'],
        correctAnswer: 2,
        explanation: 'During steady-state exercise, your heart rate increases to meet oxygen demand and then plateaus at a sustainable level.',
      },
      {
        type: 'multiple_choice',
        question: 'Which chamber of the heart pumps oxygenated blood to the body?',
        options: ['Right atrium', 'Right ventricle', 'Left atrium', 'Left ventricle'],
        correctAnswer: 3,
        explanation: 'The left ventricle is the strongest chamber and pumps oxygenated blood out through the aorta to the entire body.',
      },
      {
        type: 'scenario',
        question: 'What is the most likely explanation?',
        scenario: 'After 8 weeks of consistent running, you notice your resting heart rate has dropped from 72 bpm to 64 bpm.',
        options: ['You are overtraining', 'Your heart has become more efficient (cardiac adaptation)', 'You are dehydrated', 'Your blood pressure has increased'],
        correctAnswer: 1,
        explanation: 'A lower resting heart rate is a sign of improved cardiovascular fitness — your heart pumps more blood per beat (increased stroke volume), so it doesn\'t need to beat as often.',
      },
      {
        type: 'multiple_choice',
        question: 'What is stroke volume?',
        options: ['The number of heartbeats per minute', 'The amount of blood pumped per heartbeat', 'The speed at which blood flows through arteries', 'The oxygen content of blood'],
        correctAnswer: 1,
        explanation: 'Stroke volume is the amount of blood ejected from the left ventricle with each heartbeat. Training increases stroke volume, improving cardiac efficiency.',
      },
      {
        type: 'multiple_choice',
        question: 'Which type of blood vessel carries blood away from the heart?',
        options: ['Veins', 'Capillaries', 'Arteries', 'Venules'],
        correctAnswer: 2,
        explanation: 'Arteries carry blood away from the heart. They have thick, elastic walls to handle the high pressure of blood being pumped.',
      },
      {
        type: 'multiple_choice',
        question: 'During exercise, blood is redistributed primarily to which area?',
        options: ['The digestive system', 'The working skeletal muscles', 'The brain only', 'The skin only'],
        correctAnswer: 1,
        explanation: 'During exercise, blood is shunted away from non-essential organs (like the gut) and directed to working muscles that need more oxygen and fuel.',
      },
      {
        type: 'scenario',
        question: 'What is the best explanation for this?',
        scenario: 'You feel lightheaded when you suddenly stop running at high intensity without a cool-down.',
        options: ['Low blood sugar', 'Blood pooling in the legs due to sudden stop', 'Dehydration only', 'Overtraining syndrome'],
        correctAnswer: 1,
        explanation: 'When you stop suddenly, the muscle pump in your legs stops helping return blood to the heart, causing blood to pool in the lower body and reducing blood flow to the brain.',
      },
      {
        type: 'multiple_choice',
        question: 'Cardiac output is calculated by:',
        options: ['Heart rate × blood pressure', 'Heart rate × stroke volume', 'Stroke volume ÷ heart rate', 'Blood pressure × stroke volume'],
        correctAnswer: 1,
        explanation: 'Cardiac output = heart rate × stroke volume. It represents the total volume of blood the heart pumps per minute.',
      },
      {
        type: 'multiple_choice',
        question: 'Regular cardiovascular training leads to which long-term adaptation?',
        options: ['Decreased lung capacity', 'Increased resting heart rate', 'Increased stroke volume and lower resting heart rate', 'Reduced capillary density'],
        correctAnswer: 2,
        explanation: 'Consistent cardio training increases stroke volume and capillary density while decreasing resting heart rate — all signs of improved cardiovascular efficiency.',
      },
    ],
  },

  // ─── Chapter 5: Energy Systems ───
  {
    unitNumber: 1,
    chapterNumber: 5,
    pickCount: 5,
    passMarkPercent: 80,
    questionBank: [
      {
        type: 'multiple_choice',
        question: 'Which energy system provides fuel for short, explosive efforts lasting up to 10 seconds?',
        options: ['Aerobic system', 'Lactic acid system', 'ATP-PC (phosphocreatine) system', 'Oxidative system'],
        correctAnswer: 2,
        explanation: 'The ATP-PC system provides immediate energy for very short, high-intensity efforts like a 1-rep max or a 40-metre sprint.',
      },
      {
        type: 'multiple_choice',
        question: 'ATP stands for:',
        options: ['Adenosine triphosphate', 'Active tissue protein', 'Aerobic training pathway', 'Amino transfer process'],
        correctAnswer: 0,
        explanation: 'Adenosine triphosphate (ATP) is the body\'s energy currency — all movement requires ATP, regardless of which system produces it.',
      },
      {
        type: 'multiple_choice',
        question: 'The lactic acid system primarily fuels efforts lasting approximately:',
        options: ['1–5 seconds', '10 seconds to 2 minutes', '5–30 minutes', 'Over 60 minutes'],
        correctAnswer: 1,
        explanation: 'The lactic acid (anaerobic glycolysis) system kicks in for high-intensity efforts lasting roughly 10 seconds to 2 minutes, such as a 400-metre sprint.',
      },
      {
        type: 'scenario',
        question: 'Which energy system is primarily being used?',
        scenario: 'You are performing a heavy set of 3 reps on the bench press, taking about 8 seconds to complete.',
        options: ['Aerobic system', 'Lactic acid system', 'ATP-PC system', 'All three equally'],
        correctAnswer: 2,
        explanation: 'A heavy set lasting under 10 seconds relies primarily on the ATP-PC system, which provides immediate energy without needing oxygen.',
      },
      {
        type: 'multiple_choice',
        question: 'Which energy system uses oxygen to produce ATP?',
        options: ['ATP-PC system', 'Lactic acid system', 'Aerobic (oxidative) system', 'All systems use oxygen'],
        correctAnswer: 2,
        explanation: 'The aerobic system requires oxygen to break down carbohydrates and fats for energy. It fuels sustained, lower-intensity activities.',
      },
      {
        type: 'multiple_choice',
        question: 'What is the by-product of the lactic acid system that contributes to muscle fatigue?',
        options: ['Carbon dioxide', 'Lactate and hydrogen ions', 'Creatine phosphate', 'Urea'],
        correctAnswer: 1,
        explanation: 'Anaerobic glycolysis produces lactate and hydrogen ions. The accumulation of hydrogen ions lowers muscle pH, contributing to the burning sensation and fatigue.',
      },
      {
        type: 'scenario',
        question: 'Which energy system is dominant during this activity?',
        scenario: 'You are jogging at a comfortable pace for 30 minutes, able to hold a conversation throughout.',
        options: ['ATP-PC system', 'Lactic acid system', 'Aerobic system', 'None — the body uses stored fat only'],
        correctAnswer: 2,
        explanation: 'A comfortable, sustained jog lasting 30 minutes is powered by the aerobic system, which efficiently uses oxygen to produce energy from carbohydrates and fats.',
      },
      {
        type: 'multiple_choice',
        question: 'The ATP-PC system does NOT require which of the following?',
        options: ['Creatine phosphate', 'Oxygen', 'Stored ATP', 'Enzymes'],
        correctAnswer: 1,
        explanation: 'The ATP-PC system is anaerobic — it does not require oxygen. It uses stored ATP and creatine phosphate for rapid energy production.',
      },
      {
        type: 'multiple_choice',
        question: 'Which fuel sources does the aerobic system use?',
        options: ['Only carbohydrates', 'Only fats', 'Carbohydrates, fats, and sometimes protein', 'Only creatine phosphate'],
        correctAnswer: 2,
        explanation: 'The aerobic system is versatile, primarily using carbohydrates and fats, and occasionally protein during prolonged exercise or when other fuel sources are depleted.',
      },
      {
        type: 'multiple_choice',
        question: 'As exercise intensity increases, the body shifts from which system to which?',
        options: ['Lactic acid to aerobic', 'Aerobic to anaerobic (lactic acid and ATP-PC)', 'ATP-PC to aerobic', 'There is no shift between systems'],
        correctAnswer: 1,
        explanation: 'As intensity rises, the aerobic system cannot supply energy fast enough, so the body increasingly relies on anaerobic systems (lactic acid and ATP-PC).',
      },
    ],
  },
];
