import type { UnitAssessment, ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

// ── Unit Assessments ──

export const mindsetL3Unit1Assessment: UnitAssessment = {
  unitNumber: 1, title: 'Unit 1 Assessment — Advanced Stress Physiology & Emotional Mastery',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What does the HPA axis stand for?', options: ['Heart-Pulse-Adrenaline', 'Hypothalamic-Pituitary-Adrenal', 'High-Performance-Activation', 'Hormone-Production-Axis'], correctAnswer: 1, explanation: 'The hypothalamic-pituitary-adrenal axis is the central stress response system.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['The weight of stress hormones', 'Cumulative wear and tear from chronic stress', 'The maximum stress you can handle', 'A measure of cortisol levels'], correctAnswer: 1, explanation: 'Allostatic load describes the cumulative physiological damage from chronic stress.' },
    { type: 'multiple_choice', question: 'How does cognitive reappraisal differ from emotional suppression?', options: ['They are the same thing', 'Reappraisal changes the emotion at its source; suppression tries to push it down', 'Suppression is more effective', 'Reappraisal avoids the emotion entirely'], correctAnswer: 1, explanation: 'Reappraisal changes interpretation to alter the emotion; suppression tries to inhibit the response after it occurs.' },
    { type: 'multiple_choice', question: 'What does affect labelling do to amygdala activity?', options: ['Increases it by 50%', 'Has no effect', 'Reduces it by up to 50%', 'Completely eliminates it'], correctAnswer: 2, explanation: 'Naming emotions reduces amygdala activation by recruiting prefrontal cortex regulation.' },
    { type: 'multiple_choice', question: 'What neurochemicals are released during flow state?', options: ['Only dopamine', 'Cortisol and adrenaline', 'Norepinephrine, dopamine, endorphins, anandamide, and serotonin', 'Only serotonin'], correctAnswer: 2, explanation: 'Flow involves a cascade of five key neurochemicals that enhance performance.' },
    { type: 'multiple_choice', question: 'What is the ideal challenge-skill balance for flow?', options: ['Task should be far beyond ability', 'Task should be approximately 4% beyond current ability', 'Task should be well within comfort zone', 'Challenge level does not matter'], correctAnswer: 1, explanation: 'Research suggests the optimal stretch is approximately 4% beyond current ability.' },
    { type: 'multiple_choice', question: 'What are the five domains of post-traumatic growth?', options: ['Strength, speed, power, endurance, flexibility', 'Appreciation, relationships, strength, possibilities, existential clarity', 'Denial, anger, bargaining, depression, acceptance', 'Physical, mental, emotional, social, spiritual'], correctAnswer: 1, explanation: 'Tedeschi and Calhoun identified these five domains of positive change after trauma.' },
    { type: 'multiple_choice', question: 'Which is the strongest source of self-efficacy according to Bandura?', options: ['Verbal persuasion', 'Vicarious experience', 'Mastery experience', 'Physiological state'], correctAnswer: 2, explanation: 'Actually doing the thing successfully is the strongest foundation for believing you can do it.' },
    { type: 'multiple_choice', question: 'What are the three states in polyvagal theory?', options: ['Fight, flight, freeze', 'Ventral vagal, sympathetic, dorsal vagal', 'Calm, alert, panicked', 'Rest, active, exhausted'], correctAnswer: 1, explanation: 'Polyvagal theory describes ventral vagal (safety), sympathetic (mobilisation), and dorsal vagal (shutdown).' },
    { type: 'scenario', scenario: 'Someone is in dorsal vagal shutdown — feeling numb, disconnected, and foggy.', question: 'Which intervention is most appropriate?', options: ['Intense breathwork', 'Slow breathing only', 'Gentle movement and environmental orienting', 'Telling them to "snap out of it"'], correctAnswer: 2, explanation: 'In shutdown, gentle movement and orienting to the environment helps shift toward mobilisation before calm.' },
    { type: 'multiple_choice', question: 'What effect does chronic cortisol have on the hippocampus?', options: ['It enlarges it', 'It shrinks it', 'No effect', 'It improves memory'], correctAnswer: 1, explanation: 'Chronic cortisol causes hippocampal atrophy, impairing memory and learning.' },
    { type: 'multiple_choice', question: 'What is the TIPP technique used for?', options: ['Improving flexibility', 'Managing intense emotional distress', 'Building muscle', 'Improving sleep'], correctAnswer: 1, explanation: 'TIPP (Temperature, Intense exercise, Paced breathing, Progressive relaxation) is a distress tolerance technique.' },
  ],
};

export const mindsetL3Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Advanced Breathing & Exposure Science',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What happens to blood CO2 during cyclic hyperventilation?', options: ['It increases', 'It decreases (respiratory alkalosis)', 'It stays the same', 'It fluctuates randomly'], correctAnswer: 1, explanation: 'Rapid breathing blows off CO2, lowering blood CO2 and raising pH.' },
    { type: 'multiple_choice', question: 'What is resonance frequency breathing?', options: ['Breathing as fast as possible', 'Breathing at the rate that maximises heart rate variability', 'Holding your breath for maximum time', 'Breathing only through the mouth'], correctAnswer: 1, explanation: 'Resonance frequency breathing (typically 4.5–7 breaths/min) maximises HRV.' },
    { type: 'multiple_choice', question: 'By how much does cold exposure increase dopamine levels?', options: ['10%', '50%', '250%', '1000%'], correctAnswer: 2, explanation: 'Cold exposure can increase dopamine by approximately 250%, lasting 2–3 hours.' },
    { type: 'multiple_choice', question: 'What is the cold shock response?', options: ['Feeling cold', 'Involuntary gasp, rapid breathing, and increased heart rate on cold contact', 'Shivering', 'Numbness in extremities'], correctAnswer: 1, explanation: 'The cold shock response is a sympathetic nervous system reaction to sudden cold exposure.' },
    { type: 'multiple_choice', question: 'What are heat shock proteins?', options: ['Proteins that cause heat stroke', 'Molecular chaperones that repair damaged proteins and protect cells', 'Hormones released during fever', 'Muscle-building proteins'], correctAnswer: 1, explanation: 'HSPs repair damaged proteins and increase cellular stress resistance.' },
    { type: 'multiple_choice', question: 'What does the Yerkes-Dodson Law describe?', options: ['The relationship between sleep and performance', 'The inverted-U relationship between arousal and performance', 'The effect of nutrition on cognition', 'The stages of learning'], correctAnswer: 1, explanation: 'The Yerkes-Dodson Law shows performance peaks at moderate arousal and declines at extremes.' },
    { type: 'multiple_choice', question: 'What is the Valsalva manoeuvre used for in training?', options: ['Improving flexibility', 'Maximising intra-abdominal pressure for heavy lifts', 'Reducing heart rate', 'Improving endurance'], correctAnswer: 1, explanation: 'The Valsalva manoeuvre creates core stability through held breath and bracing during heavy lifts.' },
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['A disease caused by hormones', 'Beneficial adaptation from low-to-moderate stress doses', 'A type of breathing technique', 'Chronic stress damage'], correctAnswer: 1, explanation: 'Hormesis describes how moderate stressors trigger beneficial adaptive responses.' },
    { type: 'multiple_choice', question: 'Finnish sauna studies found frequent sauna use reduced all-cause mortality by approximately how much?', options: ['10%', '20%', '40%', '80%'], correctAnswer: 2, explanation: 'Frequent sauna use (4–7x/week) was associated with approximately 40% reduction in all-cause mortality.' },
    { type: 'scenario', scenario: 'Someone wants to start cold exposure but has never tried it before.', question: 'What is the safest starting protocol?', options: ['Jump into an ice bath for 5 minutes', '30 seconds of cold water at the end of a normal shower', 'Swim in a cold lake', 'Hold ice on your skin for 10 minutes'], correctAnswer: 1, explanation: 'Starting with brief cold at the end of a warm shower allows safe habituation before progression.' },
    { type: 'multiple_choice', question: 'What BOLT score should you achieve before progressing to intense cyclic hyperventilation?', options: ['10 seconds', '15 seconds', '25 seconds', '60 seconds'], correctAnswer: 2, explanation: 'A BOLT score above 25 indicates sufficient CO2 tolerance for advanced protocols.' },
    { type: 'multiple_choice', question: 'How does contrast therapy reduce DOMS?', options: ['By eliminating lactic acid', 'Through vascular pumping — alternating vasodilation and vasoconstriction', 'By numbing the muscles', 'It does not reduce DOMS'], correctAnswer: 1, explanation: 'Temperature oscillation creates a vascular pump effect that enhances circulation and reduces inflammation.' },
  ],
};

export const mindsetL3Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Advanced Focus, Discipline & Cognitive Performance',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is attention residue?', options: ['Leftover attention from sleep', 'Cognitive cost of task-switching — part of your focus remains on the previous task', 'A type of meditation', 'Attention deficit disorder'], correctAnswer: 1, explanation: 'Attention residue means part of your cognitive focus remains on the previous task after switching.' },
    { type: 'multiple_choice', question: 'How many hours of genuine deep work can most people sustain per day?', options: ['1–2 hours', '3–4 hours', '6–8 hours', '10+ hours'], correctAnswer: 1, explanation: 'Research suggests most people can sustain 3–4 hours of truly deep cognitive work daily.' },
    { type: 'multiple_choice', question: 'What does the ego depletion model propose?', options: ['The ego grows with use', 'Willpower is a finite resource that gets depleted', 'Ego has no effect on decisions', 'Willpower is unlimited'], correctAnswer: 1, explanation: 'Baumeister\'s model proposed willpower is a depletable resource, though recent research questions the effect size.' },
    { type: 'multiple_choice', question: 'What is the most effective solution to decision fatigue?', options: ['Making more decisions to build stamina', 'Designing systems that eliminate unnecessary decisions', 'Drinking coffee', 'Sleeping more'], correctAnswer: 1, explanation: 'Systems and pre-commitment remove the need for decisions, preserving cognitive resources.' },
    { type: 'multiple_choice', question: 'What does BDNF stand for and why is it important?', options: ['Brain-Derived Neurotrophic Factor — supports neuron growth and plasticity', 'Body-Dependent Nutritional Factor', 'Basic Daily Nutritional Formula', 'Brain-Disrupting Neural Function'], correctAnswer: 0, explanation: 'BDNF supports neuronal growth, survival, and synaptic plasticity — critical for learning and brain health.' },
    { type: 'multiple_choice', question: 'What clears metabolic waste from the brain during sleep?', options: ['The lymphatic system', 'The glymphatic system', 'Blood circulation', 'Cerebrospinal breathing'], correctAnswer: 1, explanation: 'The glymphatic system is 10x more active during sleep, clearing amyloid-beta and other waste.' },
    { type: 'multiple_choice', question: 'What are the three basic psychological needs in Self-Determination Theory?', options: ['Food, shelter, safety', 'Autonomy, competence, relatedness', 'Power, achievement, affiliation', 'Physical, emotional, spiritual'], correctAnswer: 1, explanation: 'Deci and Ryan identified autonomy, competence, and relatedness as essential for intrinsic motivation.' },
    { type: 'multiple_choice', question: 'According to James Clear, what is the most effective layer to start behaviour change?', options: ['Outcomes', 'Processes', 'Identity', 'Environment'], correctAnswer: 2, explanation: 'Starting with identity ("I am someone who...") creates lasting change because behaviour follows belief.' },
    { type: 'multiple_choice', question: 'What type of visualisation is most effective for performance?', options: ['Outcome visualisation only', 'Process visualisation combined with brief outcome visualisation', 'Visualising relaxation', 'Not visualising at all'], correctAnswer: 1, explanation: 'Process visualisation primes neural pathways; brief outcome visualisation sets direction.' },
    { type: 'scenario', scenario: 'An athlete keeps saying "I just need to find my motivation" before training.', question: 'What does motivation science suggest?', options: ['They should wait until motivation arrives', 'Action precedes motivation — start training and motivation follows', 'They need a new programme', 'They should take a month off'], correctAnswer: 1, explanation: 'Motivation follows action, not the other way around. Starting creates the motivation to continue.' },
    { type: 'multiple_choice', question: 'What does creatine supplementation improve cognitively?', options: ['Long-term memory only', 'Short-term memory and reasoning, especially under stress or sleep deprivation', 'Nothing — it only affects muscles', 'Emotional regulation'], correctAnswer: 1, explanation: 'Creatine has cognitive benefits for short-term memory and reasoning, particularly when cognitively stressed.' },
    { type: 'multiple_choice', question: 'What is the motivation spectrum in SDT from least to most self-determined?', options: ['Intrinsic → extrinsic', 'Amotivation → external → introjected → identified → integrated → intrinsic', 'Low energy → high energy', 'Passive → active'], correctAnswer: 1, explanation: 'SDT describes a continuum from amotivation through external regulation to intrinsic motivation.' },
  ],
};

export const mindsetL3Unit4Assessment: UnitAssessment = {
  unitNumber: 4, title: 'Unit 4 Assessment — Resilience Integration & Lifelong Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What are the five pillars of daily resilience?', options: ['Eat, sleep, train, repeat, rest', 'Physiological regulation, physical challenge, cognitive engagement, emotional processing, social connection', 'Breathing, cold, heat, journaling, meditation', 'Strength, speed, endurance, flexibility, balance'], correctAnswer: 1, explanation: 'A complete system addresses physiology, physicality, cognition, emotion, and social connection.' },
    { type: 'multiple_choice', question: 'What is the AAAA Setback Protocol?', options: ['Assess, Accept, Adapt, Act', 'Avoid, Analyse, Attempt, Achieve', 'Acknowledge, Apologise, Adjust, Advance', 'Assess, Avoid, Accept, Achieve'], correctAnswer: 0, explanation: 'Assess the reality, Accept what happened, Adapt your plan, Act with the smallest meaningful step.' },
    { type: 'multiple_choice', question: 'How does rumination differ from reflection?', options: ['They are the same', 'Reflection produces action points; rumination is circular without resolution', 'Rumination is more productive', 'Reflection is unhealthy'], correctAnswer: 1, explanation: 'Reflection moves toward insight and action; rumination repeats without progress.' },
    { type: 'multiple_choice', question: 'How harmful is loneliness compared to other health risks?', options: ['Minor effect', 'Equivalent to smoking 15 cigarettes per day', 'Equivalent to mild dehydration', 'No measurable health effect'], correctAnswer: 1, explanation: 'Meta-analysis of 300,000+ participants found loneliness as harmful as smoking 15 cigarettes daily.' },
    { type: 'multiple_choice', question: 'What characterises an effective boundary?', options: ['Vague and flexible', 'Clear, consistent, compassionate, with known consequences', 'Aggressive and punishing', 'Only set when convenient'], correctAnswer: 1, explanation: 'Effective boundaries are specific, consistently enforced, compassionate, and have clear consequences.' },
    { type: 'multiple_choice', question: 'What is the difference between hedonic and eudaimonic wellbeing?', options: ['They are identical', 'Hedonic is pleasure-based; eudaimonic is meaning and purpose-based', 'Hedonic is long-lasting; eudaimonic is temporary', 'Eudaimonic is about physical health'], correctAnswer: 1, explanation: 'Hedonic wellbeing seeks pleasure; eudaimonic wellbeing seeks meaning, purpose, and self-realisation.' },
    { type: 'multiple_choice', question: 'What is the difference between coaching and therapy?', options: ['No difference', 'Coaching helps find answers through questions; therapy treats clinical conditions', 'Coaching is more effective', 'Therapy is for weak people'], correctAnswer: 1, explanation: 'Coaching facilitates self-discovery; therapy provides clinical treatment for mental health conditions.' },
    { type: 'multiple_choice', question: 'What is the 80/20 rule in active listening?', options: ['Speak 80%, listen 20%', 'Listen 80%, speak 20%', 'Agree 80% of the time', 'Practise 80 minutes daily'], correctAnswer: 1, explanation: 'Effective coaching involves listening far more than speaking — approximately 80% listening.' },
    { type: 'scenario', scenario: 'Someone you are coaching describes persistent low mood for three weeks, loss of interest in activities, and difficulty getting out of bed.', question: 'What should you do?', options: ['Give them a harder training programme', 'Encourage them to seek professional mental health support', 'Tell them to be more positive', 'Suggest cold exposure therapy'], correctAnswer: 1, explanation: 'These symptoms suggest possible depression — this exceeds peer coaching scope and requires professional help.' },
    { type: 'multiple_choice', question: 'What does "periodising mental training" mean?', options: ['Only training mentally on weekdays', 'Alternating between higher stress phases and recovery phases in mental practices', 'Training the same way every day', 'Only practising when motivated'], correctAnswer: 1, explanation: 'Like physical training, mental training benefits from cycling intensity with adequate recovery periods.' },
    { type: 'multiple_choice', question: 'According to the course, what is the ultimate performance metric?', options: ['Maximum intensity', 'Perfect execution', 'Sustainability', 'Speed of progress'], correctAnswer: 2, explanation: 'Sustainability — consistency over years — beats short-term intensity every time.' },
    { type: 'multiple_choice', question: 'What is a values clarification exercise designed to reveal?', options: ['Your fitness level', 'Your core values that should guide decision-making', 'Your personality type', 'Your career path'], correctAnswer: 1, explanation: 'Values clarification identifies your deepest priorities to guide consistent, meaningful decision-making.' },
  ],
};

// ── Final Assessment ──

export const mindsetL3FinalAssessment: UnitAssessment = {
  unitNumber: 0, title: 'Level 3 Final Assessment — Advanced Mindset',
  passMarkPercent: 80, pickCount: 20,
  questions: [
    { type: 'multiple_choice', question: 'What feedback mechanism regulates the HPA axis?', options: ['Cortisol feeds back to shut down CRH and ACTH release', 'Adrenaline increases CRH', 'Dopamine activates the pituitary', 'Serotonin suppresses the adrenals'], correctAnswer: 0, explanation: 'Cortisol provides negative feedback to the hypothalamus and pituitary to terminate the stress response.' },
    { type: 'multiple_choice', question: 'What brain change does chronic cortisol cause to the amygdala?', options: ['Shrinks it', 'Enlarges it (increasing anxiety)', 'No effect', 'Improves its function'], correctAnswer: 1, explanation: 'Chronic cortisol enlarges the amygdala, increasing anxiety and threat sensitivity.' },
    { type: 'multiple_choice', question: 'What is hypofrontality in flow state?', options: ['Increased prefrontal activity', 'Temporary partial deactivation of the prefrontal cortex', 'Complete brain shutdown', 'Heightened self-consciousness'], correctAnswer: 1, explanation: 'Hypofrontality silences the inner critic by partially deactivating the prefrontal cortex during flow.' },
    { type: 'multiple_choice', question: 'What minimum BOLT score indicates adequate CO2 tolerance for advanced breathwork?', options: ['10 seconds', '15 seconds', '25 seconds', '45 seconds'], correctAnswer: 2, explanation: 'A BOLT score above 25 indicates sufficient tolerance for more intense protocols.' },
    { type: 'multiple_choice', question: 'How long does the dopamine increase from cold exposure typically last?', options: ['30 minutes', '2–3 hours', '24 hours', '1 week'], correctAnswer: 1, explanation: 'Cold exposure produces a gradual, sustained dopamine increase lasting 2–3 hours.' },
    { type: 'multiple_choice', question: 'What does attention residue mean for gym performance?', options: ['Nothing', 'Checking your phone between sets reduces focus for 10–20 minutes', 'It improves multi-tasking', 'It only affects work performance'], correctAnswer: 1, explanation: 'Attention residue from phone-checking reduces training quality for an extended period.' },
    { type: 'multiple_choice', question: 'Which SDT need does rigid externally imposed programming undermine?', options: ['Competence', 'Autonomy', 'Relatedness', 'All equally'], correctAnswer: 1, explanation: 'Rigid external programmes remove choice, undermining the autonomy need.' },
    { type: 'multiple_choice', question: 'What is the most effective type of goal for daily behaviour?', options: ['Outcome goals', 'Performance goals', 'Process goals', 'Dream goals'], correctAnswer: 2, explanation: 'Process goals (daily actions) are fully controllable and build identity through consistent votes.' },
    { type: 'scenario', scenario: 'Someone trains 7 days a week, does cold plunges daily, and advanced breathwork twice daily. Their sleep is deteriorating and motivation is dropping.', question: 'What is the most likely issue?', options: ['Not training hard enough', 'Hormetic stress overload without adequate recovery', 'They need more cold exposure', 'Their nutrition is wrong'], correctAnswer: 1, explanation: 'Stacking too many stressors without recovery leads to overload — reduce frequency and periodise.' },
    { type: 'multiple_choice', question: 'How does process visualisation differ from outcome visualisation?', options: ['Process imagines the steps and effort; outcome imagines the end result', 'They are the same', 'Process is less effective', 'Outcome visualisation primes motor pathways'], correctAnswer: 0, explanation: 'Process visualisation primes the neural pathways for execution; outcome visualisation sets direction.' },
    { type: 'multiple_choice', question: 'What is the single strongest predictor of happiness and longevity?', options: ['Income', 'Physical fitness', 'Social connection quality', 'Career success'], correctAnswer: 2, explanation: 'Quality social connection is the strongest predictor of both happiness and longevity.' },
    { type: 'multiple_choice', question: 'When should you refer someone to professional mental health support?', options: ['Never — you can handle everything', 'When symptoms persist for 2+ weeks and impair daily functioning', 'Only if they ask', 'Only in emergencies'], correctAnswer: 1, explanation: 'Persistent symptoms impairing daily life exceed peer coaching scope and require professional intervention.' },
    { type: 'multiple_choice', question: 'What makes identified motivation more resilient than external motivation?', options: ['It is driven by guilt', 'It connects to personal values rather than external rewards', 'It requires no effort', 'It is always enjoyable'], correctAnswer: 1, explanation: 'Identified motivation is resilient because it connects behaviour to personal values and identity.' },
    { type: 'multiple_choice', question: 'What percentage of daily energy does the brain consume?', options: ['5%', '10%', '20%', '50%'], correctAnswer: 2, explanation: 'The brain uses approximately 20% of total body energy despite being only 2% of body mass.' },
    { type: 'multiple_choice', question: 'What is the most important factor for long-term brain health?', options: ['Supplements', 'Brain training games', 'Sleep', 'Caffeine'], correctAnswer: 2, explanation: 'Sleep enables glymphatic clearance, memory consolidation, and neural repair — irreplaceable for brain health.' },
    { type: 'scenario', scenario: 'A training partner asks you to help them "find their motivation." They feel stuck but have no clinical symptoms.', question: 'What approach aligns with motivation science?', options: ['Tell them to wait until they feel motivated', 'Help them identify their values and design systems that reduce reliance on willpower', 'Give them a motivational speech', 'Suggest they take a month off'], correctAnswer: 1, explanation: 'Values-based systems and environmental design create sustainable motivation without relying on feelings.' },
    { type: 'multiple_choice', question: 'What does the Unbreakable Philosophy ultimately emphasise?', options: ['Never showing weakness', 'Consistent, values-aligned living with tools for recovery', 'Training every day without rest', 'Being better than everyone else'], correctAnswer: 1, explanation: 'Being unbreakable means having the knowledge and tools to recover and grow — consistently, not perfectly.' },
    { type: 'multiple_choice', question: 'What is the key difference between assertive and aggressive boundary-setting?', options: ['No difference', 'Assertive states needs clearly without attacking; aggressive attacks the person', 'Aggressive is more effective', 'Assertive is passive'], correctAnswer: 1, explanation: 'Assertive communication protects the relationship while setting clear limits; aggression damages it.' },
    { type: 'multiple_choice', question: 'What is the recommended approach for mental training deload weeks?', options: ['Stop all practices entirely', 'Reduce intensity, extend sleep, focus on enjoyment every 4–6 weeks', 'Increase intensity', 'Only deload if injured'], correctAnswer: 1, explanation: 'Periodic deloads prevent psychological burnout and maintain long-term practice sustainability.' },
    { type: 'multiple_choice', question: 'According to growth mindset research, what characterises the most resilient approach to failure?', options: ['Avoiding failure at all costs', 'Viewing failure as evidence of fixed limitations', 'Viewing failure as information and an opportunity for learning', 'Ignoring failure completely'], correctAnswer: 2, explanation: 'Growth mindset treats failure as feedback — data for adjustment, not evidence of inability.' },
    { type: 'scenario', scenario: 'You have completed both Level 2 and Level 3 Mindset courses. A friend asks what the single most important takeaway is.', question: 'Which answer best captures the course philosophy?', options: ['Learn to never feel stressed', 'Build systems and practices that make resilience automatic, then apply them consistently', 'Avoid all discomfort', 'Knowledge is enough — no practice needed'], correctAnswer: 1, explanation: 'The course teaches that resilience is built through consistent practice of evidence-based systems — not perfection.' },
  ],
};

// ── Chapter Quizzes ──

// Unit 1 — Advanced Stress Physiology & Emotional Mastery
export const mindsetL3Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'What hormone does the hypothalamus release to start the HPA cascade?', options: ['Cortisol', 'ACTH', 'CRH (corticotropin-releasing hormone)', 'Adrenaline'], correctAnswer: 2, explanation: 'CRH from the hypothalamus triggers the pituitary to release ACTH.' },
    { type: 'multiple_choice', question: 'What is eustress?', options: ['Chronic damaging stress', 'Positive stress that drives adaptation and growth', 'Stress from exercise only', 'Stress you cannot control'], correctAnswer: 1, explanation: 'Eustress is beneficial stress that is short-duration and within coping capacity.' },
    { type: 'multiple_choice', question: 'What does chronic cortisol do to the prefrontal cortex?', options: ['Enhances it', 'Disrupts it, reducing decision-making and impulse control', 'Has no effect', 'Makes it larger'], correctAnswer: 1, explanation: 'Chronic cortisol impairs prefrontal function, reducing rational decision-making capacity.' },
    { type: 'multiple_choice', question: 'What is allostatic load?', options: ['Maximum weight you can lift', 'Cumulative physiological damage from chronic stress', 'A breathing technique', 'A type of training'], correctAnswer: 1, explanation: 'Allostatic load is the total wear and tear from sustained stress on body systems.' },
    { type: 'multiple_choice', question: 'Can the same stressor be both eustress and distress?', options: ['No, stressors are always one or the other', 'Yes, depending on perception and recovery state', 'Only physical stressors', 'Only psychological stressors'], correctAnswer: 1, explanation: 'Perception and recovery capacity determine whether a stressor is beneficial or harmful.' },
    { type: 'multiple_choice', question: 'What metabolic effect does chronic cortisol promote?', options: ['Fat loss', 'Insulin resistance and visceral fat storage', 'Muscle growth', 'Improved digestion'], correctAnswer: 1, explanation: 'Sustained cortisol promotes insulin resistance and preferential abdominal fat deposition.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Ignoring your emotions', 'Deliberately reinterpreting a situation to change your emotional response', 'Suppressing feelings', 'Avoiding stressful situations'], correctAnswer: 1, explanation: 'Reappraisal changes the meaning of a situation, altering the emotion at its source.' },
    { type: 'multiple_choice', question: 'What brain effect does affect labelling produce?', options: ['Increases amygdala activity', 'Reduces amygdala activity by recruiting prefrontal cortex', 'No measurable effect', 'Activates fight-or-flight'], correctAnswer: 1, explanation: 'Naming emotions engages the prefrontal cortex, which dampens amygdala reactivity.' },
    { type: 'multiple_choice', question: 'What does TIPP stand for in distress tolerance?', options: ['Think, Imagine, Plan, Proceed', 'Temperature, Intense exercise, Paced breathing, Progressive relaxation', 'Train, Improve, Persist, Perform', 'Time, Intention, Practice, Patience'], correctAnswer: 1, explanation: 'TIPP uses physiological interventions to change body state and therefore emotional state.' },
    { type: 'multiple_choice', question: 'What is third-person affect labelling?', options: ['Talking about someone else', 'Referring to yourself by name for additional psychological distance', 'Labelling emotions in a group', 'Writing emotions anonymously'], correctAnswer: 1, explanation: 'Using your own name creates psychological distance that enhances emotional regulation.' },
    { type: 'multiple_choice', question: 'How does suppression compare to reappraisal long-term?', options: ['Suppression is better', 'Reappraisal produces better outcomes with less physiological cost', 'They are equally effective', 'Neither is effective'], correctAnswer: 1, explanation: 'Suppression requires ongoing effort and does not reduce the underlying emotion; reappraisal does.' },
    { type: 'multiple_choice', question: 'Which form of labelling produces the strongest regulation?', options: ['Saying "I feel bad"', 'Written detailed labelling through journaling', 'Thinking silently', 'Talking to no one'], correctAnswer: 1, explanation: 'Written labelling forces precise articulation, producing the strongest and most lasting regulatory effect.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'Who coined the concept of "flow state"?', options: ['Sigmund Freud', 'Mihaly Csikszentmihalyi', 'Carl Jung', 'B.F. Skinner'], correctAnswer: 1, explanation: 'Csikszentmihalyi described and researched flow as a state of complete absorption.' },
    { type: 'multiple_choice', question: 'What happens to the prefrontal cortex during flow?', options: ['It becomes hyperactive', 'It partially deactivates (hypofrontality)', 'It shuts down completely', 'No change occurs'], correctAnswer: 1, explanation: 'Temporary hypofrontality silences the inner critic, allowing implicit systems to drive performance.' },
    { type: 'multiple_choice', question: 'How much can flow increase productivity?', options: ['10–20%', '50–100%', '200–500%', 'No measurable increase'], correctAnswer: 2, explanation: 'Research suggests flow can increase productivity by 200–500%.' },
    { type: 'multiple_choice', question: 'What is the minimum uninterrupted focus time to enter flow?', options: ['5 minutes', '10 minutes', '20 minutes', '60 minutes'], correctAnswer: 2, explanation: 'Most people need at least 20 minutes of uninterrupted focus before flow state becomes possible.' },
    { type: 'multiple_choice', question: 'What comes before the flow state in the flow cycle?', options: ['Recovery', 'The struggle phase', 'Relaxation', 'Sleep'], correctAnswer: 1, explanation: 'The struggle phase (difficulty and frustration) precedes the release into flow.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'How is trauma defined in this context?', options: ['Only severe physical injury', 'By how the nervous system responded and whether the response became stuck', 'Any negative experience', 'Only childhood events'], correctAnswer: 1, explanation: 'Trauma is defined by the nervous system response, not the severity of the event itself.' },
    { type: 'multiple_choice', question: 'What are the five domains of post-traumatic growth?', options: ['Physical recovery, mental clarity, emotional balance, social skills, career success', 'Appreciation, relationships, personal strength, new possibilities, existential clarity', 'Speed, strength, flexibility, endurance, coordination', 'Acceptance, anger, denial, bargaining, depression'], correctAnswer: 1, explanation: 'PTG manifests as greater appreciation, deeper relationships, personal strength, new possibilities, and existential understanding.' },
    { type: 'multiple_choice', question: 'When should you refer someone to professional help?', options: ['Only if they ask', 'When daily functioning is significantly impaired for more than two weeks', 'Never — peer support is always sufficient', 'Only in life-threatening situations'], correctAnswer: 1, explanation: 'Persistent functional impairment exceeds peer coaching scope and requires professional intervention.' },
    { type: 'multiple_choice', question: 'Does PTG mean trauma was necessary for growth?', options: ['Yes', 'No — it means growth can emerge from the struggle, not that trauma was beneficial', 'Only for some people', 'PTG is not real'], correctAnswer: 1, explanation: 'PTG does not justify trauma — it acknowledges that growth can emerge from adversity under the right conditions.' },
    { type: 'multiple_choice', question: 'What brain change occurs with PTSD?', options: ['Improved memory', 'Overactive amygdala, suppressed prefrontal cortex, hippocampal processing issues', 'Enhanced emotional regulation', 'No structural changes'], correctAnswer: 1, explanation: 'PTSD involves an overactive threat system, reduced rational processing, and unprocessed traumatic memories.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'What is the strongest source of self-efficacy?', options: ['Verbal persuasion', 'Mastery experience', 'Vicarious experience', 'Reading about success'], correctAnswer: 1, explanation: 'Actually succeeding at progressively harder challenges provides the most powerful evidence of capability.' },
    { type: 'multiple_choice', question: 'What is the T/C ratio related to?', options: ['Training/Coaching balance', 'Testosterone/Cortisol ratio correlating with behavioural confidence', 'Time/Cost efficiency', 'Training/Competition split'], correctAnswer: 1, explanation: 'The testosterone-to-cortisol ratio correlates with assertiveness and behavioural confidence.' },
    { type: 'multiple_choice', question: 'How does avoidance affect confidence?', options: ['It protects confidence', 'It reinforces the belief that you cannot handle the situation', 'It has no effect', 'It builds confidence over time'], correctAnswer: 1, explanation: 'Every avoidance strengthens the fear and weakens self-efficacy.' },
    { type: 'multiple_choice', question: 'What is the confidence exposure ladder?', options: ['A gym exercise', 'A ranked list of feared situations to work through progressively', 'A supplement protocol', 'A breathing technique'], correctAnswer: 1, explanation: 'The exposure ladder ranks situations from mildly uncomfortable to genuinely frightening for progressive desensitisation.' },
    { type: 'multiple_choice', question: 'What distinguishes genuine self-efficacy from performative confidence?', options: ['They are identical', 'Self-efficacy is built through progressive competence; performative confidence collapses under pressure', 'Performative confidence is stronger', 'Self-efficacy requires no experience'], correctAnswer: 1, explanation: 'Genuine self-efficacy is evidence-based; performative confidence lacks substance and fails when tested.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What are the three polyvagal states?', options: ['Happy, sad, angry', 'Ventral vagal, sympathetic, dorsal vagal', 'Alert, relaxed, asleep', 'Fight, flight, freeze'], correctAnswer: 1, explanation: 'Polyvagal theory describes safety (ventral vagal), mobilisation (sympathetic), and shutdown (dorsal vagal).' },
    { type: 'multiple_choice', question: 'What is the ventral vagal state associated with?', options: ['Fight or flight', 'Social engagement, safety, and calm', 'Numbness and shutdown', 'Panic'], correctAnswer: 1, explanation: 'Ventral vagal is the state of safety — connection, calm, and complex cognitive function.' },
    { type: 'multiple_choice', question: 'What works best for shifting out of dorsal vagal shutdown?', options: ['Intense breathwork', 'Gentle movement and orienting to the environment', 'Forcing yourself to socialise', 'Caffeine'], correctAnswer: 1, explanation: 'In shutdown, gentle stimulation (movement, sensory awareness) helps shift toward mobilisation before safety.' },
    { type: 'multiple_choice', question: 'What does co-regulation mean?', options: ['Regulating your own emotions', 'Using connection with another person\'s calm nervous system to regulate your own', 'Exercising with a partner', 'Taking medication'], correctAnswer: 1, explanation: 'Co-regulation uses social connection — a calm voice, presence — to help regulate your own nervous system.' },
    { type: 'multiple_choice', question: 'Can you be in mixed autonomic states?', options: ['No, only one state at a time', 'Yes — you can be sympathetically activated while partially in dorsal vagal', 'Only during sleep', 'Only during exercise'], correctAnswer: 1, explanation: 'Mixed states are common — you can feel anxious (sympathetic) and helpless (dorsal vagal) simultaneously.' },
  ]),
];

// Unit 2 — Advanced Breathing & Exposure Science
export const mindsetL3Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What happens to blood pH during cyclic hyperventilation?', options: ['It decreases (more acidic)', 'It increases (respiratory alkalosis)', 'It stays the same', 'It fluctuates unpredictably'], correctAnswer: 1, explanation: 'Blowing off CO2 raises blood pH, creating respiratory alkalosis.' },
    { type: 'multiple_choice', question: 'What is a CO2 table?', options: ['A nutrition reference chart', 'Repeated breath holds with decreasing rest intervals', 'A breathing speed test', 'A carbon dioxide detector'], correctAnswer: 1, explanation: 'CO2 tables progressively challenge your tolerance by reducing rest between holds.' },
    { type: 'multiple_choice', question: 'What breathing rate typically achieves resonance frequency?', options: ['12–15 breaths/min', '4.5–7 breaths/min', '20+ breaths/min', '1 breath/min'], correctAnswer: 1, explanation: 'Most people\'s resonance frequency falls between 4.5 and 7 breaths per minute.' },
    { type: 'multiple_choice', question: 'What does improved CO2 tolerance correlate with?', options: ['Higher blood pressure', 'Reduced anxiety and better performance under pressure', 'Increased breathing rate', 'Lower oxygen levels'], correctAnswer: 1, explanation: 'Better CO2 tolerance means a less reactive respiratory drive, directly reducing anxiety symptoms.' },
    { type: 'multiple_choice', question: 'What is the benefit of the breath hold after hyperventilation rounds?', options: ['It increases CO2 only', 'It creates a powerful sympathetic-to-parasympathetic transition', 'It builds lung capacity', 'It has no specific benefit'], correctAnswer: 1, explanation: 'The recovery phase after holds triggers a strong parasympathetic shift, enhancing vagal tone.' },
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What triggers the cold shock response?', options: ['Low body temperature', 'Cutaneous cold receptors signalling the sympathetic nervous system', 'Brain temperature drop', 'Muscle cooling'], correctAnswer: 1, explanation: 'Skin cold receptors trigger the involuntary sympathetic response upon cold contact.' },
    { type: 'multiple_choice', question: 'How long does the cold shock response typically last?', options: ['5–10 seconds', '30–60 seconds', '5 minutes', '30 minutes'], correctAnswer: 1, explanation: 'The cold shock response is most intense in the first 30–60 seconds and diminishes with habituation.' },
    { type: 'multiple_choice', question: 'What does cold exposure do to noradrenaline?', options: ['Decreases it', 'Increases it by 200–300%', 'No effect', 'Increases it by 10%'], correctAnswer: 1, explanation: 'Cold exposure significantly increases noradrenaline, improving alertness, focus, and mood.' },
    { type: 'multiple_choice', question: 'What is brown adipose tissue (BAT)?', options: ['Unhealthy body fat', 'Metabolically active fat that generates heat by burning calories', 'A type of muscle', 'Scar tissue'], correctAnswer: 1, explanation: 'BAT produces heat through thermogenesis, activated by cold exposure.' },
    { type: 'multiple_choice', question: 'What is the primary psychological benefit of cold exposure?', options: ['Improved flexibility', 'Proving you can choose discomfort and handle it — transferable mental toughness', 'Weight loss', 'Better skin'], correctAnswer: 1, explanation: 'Choosing voluntary discomfort builds the psychological habit of doing hard things.' },
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What cardiovascular response does sauna use create?', options: ['Heart rate decreases', 'Heart rate increases to 100–150 bpm with vasodilation', 'Blood pressure increases sharply and stays elevated', 'No cardiovascular effect'], correctAnswer: 1, explanation: 'Heat exposure creates cardiovascular stress similar to moderate exercise.' },
    { type: 'multiple_choice', question: 'What are heat shock proteins?', options: ['Proteins destroyed by heat', 'Molecular chaperones that repair proteins and protect cells', 'Proteins that cause overheating', 'Digestive enzymes'], correctAnswer: 1, explanation: 'HSPs repair damaged proteins and increase cellular resilience to all forms of stress.' },
    { type: 'multiple_choice', question: 'By how much can sauna increase growth hormone acutely?', options: ['10–20%', '50%', '200–300%', '1000%'], correctAnswer: 2, explanation: 'Studies show up to 200–300% acute growth hormone increase with 20-minute sauna sessions.' },
    { type: 'multiple_choice', question: 'What is contrast therapy?', options: ['Comparing two training programmes', 'Alternating heat and cold exposure for amplified benefits', 'Training at different intensities', 'Using light and dark rooms'], correctAnswer: 1, explanation: 'Contrast therapy combines heat and cold to enhance vascular, hormonal, and neurological benefits.' },
    { type: 'multiple_choice', question: 'How much sweat can be lost in a single sauna session?', options: ['A few millilitres', '0.5–1 litre', '3–5 litres', '10 litres'], correctAnswer: 1, explanation: 'Significant fluid loss (0.5–1L per session) makes hydration before and after essential.' },
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'What does the Yerkes-Dodson Law describe?', options: ['The relationship between sleep and memory', 'Performance peaks at moderate arousal; declines at both extremes', 'Higher arousal always means better performance', 'Rest is always optimal'], correctAnswer: 1, explanation: 'The inverted-U shows optimal performance at moderate arousal, with decline at under- and over-arousal.' },
    { type: 'multiple_choice', question: 'What breathing is best before a heavy lift?', options: ['Extended exhale to calm down', 'Short sharp breaths to increase sympathetic activation', 'Holding breath for 2 minutes', 'Hyperventilation for 5 minutes'], correctAnswer: 1, explanation: 'Power events benefit from moderate sympathetic activation to increase force readiness.' },
    { type: 'multiple_choice', question: 'When should you exhale during a precision task?', options: ['During the preparation phase', 'At the moment of execution', 'After completing the action', 'It does not matter'], correctAnswer: 1, explanation: 'Exhale at execution (e.g., releasing an arrow) provides maximum stability and calm.' },
    { type: 'multiple_choice', question: 'What is tactical breathing?', options: ['Breathing only through one nostril', '4-count inhale, 4-count hold, 4-count exhale, 4-count hold', 'Breathing as fast as possible', 'Not breathing during performance'], correctAnswer: 1, explanation: 'Tactical breathing (box breathing) manages anxiety during competition breaks and transitions.' },
    { type: 'multiple_choice', question: 'How can post-performance breathing reduce heart rate recovery time?', options: ['It cannot', 'Slow nasal breathing (4 in, 8 out) can reduce recovery time by 30%', 'Only cold water helps', 'Only medication works'], correctAnswer: 1, explanation: 'Deliberate parasympathetic breathing accelerates cardiovascular recovery after intense performance.' },
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What is hormesis?', options: ['Damage from excessive stress', 'Beneficial adaptation from controlled low-to-moderate stress', 'A type of hormone', 'A disease process'], correctAnswer: 1, explanation: 'Hormesis describes how moderate stressors trigger positive adaptive responses.' },
    { type: 'multiple_choice', question: 'By how much can contrast therapy reduce DOMS?', options: ['5%', '20–30%', '50–70%', '100%'], correctAnswer: 1, explanation: 'Studies show contrast therapy can reduce delayed-onset muscle soreness by 20–30%.' },
    { type: 'multiple_choice', question: 'What signs indicate hormetic stress overload?', options: ['Increased energy and motivation', 'Deteriorating sleep, dropping motivation, rising resting heart rate', 'Better performance', 'No signs — overload is not possible'], correctAnswer: 1, explanation: 'Sleep disruption, motivational decline, and elevated resting HR indicate too much stress without recovery.' },
    { type: 'multiple_choice', question: 'How should you end a contrast therapy session for alertness?', options: ['On heat', 'On cold', 'On a warm-up', 'Order does not matter'], correctAnswer: 1, explanation: 'Ending on cold promotes alertness through noradrenaline and dopamine elevation.' },
    { type: 'multiple_choice', question: 'How often should you include a full rest day from exposure stressors?', options: ['Never', 'At least one per week', 'Once per month', 'Only when injured'], correctAnswer: 1, explanation: 'Minimum one full rest day per week prevents cumulative stress overload.' },
  ]),
];

// Unit 3 — Advanced Focus, Discipline & Cognitive Performance
export const mindsetL3Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What are the three attention networks?', options: ['Visual, auditory, tactile', 'Alerting, orienting, executive', 'Short-term, long-term, working', 'Conscious, subconscious, unconscious'], correctAnswer: 1, explanation: 'Alerting (readiness), orienting (directing focus), and executive (conflict resolution) networks.' },
    { type: 'multiple_choice', question: 'How long does attention residue affect focus after a phone check?', options: ['1–2 minutes', '10–20 minutes', '1 hour', 'No effect'], correctAnswer: 1, explanation: 'Part of attention remains on the previous task for 10–20 minutes after switching.' },
    { type: 'multiple_choice', question: 'What percentage of body energy does the brain consume?', options: ['5%', '10%', '20%', '40%'], correctAnswer: 2, explanation: 'The brain uses approximately 20% of total energy despite being only 2% of body mass.' },
    { type: 'multiple_choice', question: 'What is the recommended starting block for deep work training?', options: ['5-minute blocks', '25-minute Pomodoro blocks', '3-hour blocks', '8-hour blocks'], correctAnswer: 1, explanation: 'Start with 25-minute focused blocks and gradually extend as capacity develops.' },
    { type: 'multiple_choice', question: 'What is more effective than willpower for maintaining focus?', options: ['Motivation', 'Environmental design — removing distractions', 'Caffeine', 'Positive thinking'], correctAnswer: 1, explanation: 'Removing distractions beats trying to resist them — environment design trumps willpower.' },
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'What did Baumeister\'s ego depletion theory propose?', options: ['Willpower grows with use', 'Willpower is a finite resource that gets depleted through decisions', 'Willpower is unlimited', 'Willpower only applies to diet'], correctAnswer: 1, explanation: 'The theory proposed willpower is finite and gets used up, though recent research questions the effect size.' },
    { type: 'multiple_choice', question: 'What is decision fatigue?', options: ['Tiredness from exercise', 'Declining decision quality as the number of decisions increases', 'Fatigue from too much sleep', 'A medical condition'], correctAnswer: 1, explanation: 'More decisions = worse later decisions, which is well-documented even if the mechanism is debated.' },
    { type: 'multiple_choice', question: 'What did James Clear call "making the right thing the default"?', options: ['Motivation technique', 'System design that removes the need for willpower', 'Positive affirmation', 'Goal setting'], correctAnswer: 1, explanation: 'Designing environments where desired behaviour requires less effort than undesired alternatives.' },
    { type: 'multiple_choice', question: 'Which type of decision is easiest to make?', options: ['Open-ended choices', 'Binary decisions (yes/no)', 'Multi-option decisions', 'Emotional decisions'], correctAnswer: 1, explanation: 'Binary decisions are simpler and consume less cognitive resources than open-ended choices.' },
    { type: 'multiple_choice', question: 'How does meal prep reduce decision fatigue?', options: ['It does not', 'It eliminates the daily "what should I eat?" decision entirely', 'It saves money only', 'It only helps with cooking time'], correctAnswer: 1, explanation: 'Pre-committing food choices eliminates daily nutrition decisions when willpower may be depleted.' },
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What does BDNF do in the brain?', options: ['Damages neurons', 'Supports growth, survival, and plasticity of neurons', 'Clears waste', 'Produces cortisol'], correctAnswer: 1, explanation: 'BDNF is essential for neuronal growth, survival, and synaptic plasticity.' },
    { type: 'multiple_choice', question: 'What system clears brain waste during sleep?', options: ['Lymphatic system', 'Glymphatic system', 'Digestive system', 'Respiratory system'], correctAnswer: 1, explanation: 'The glymphatic system is 10x more active during sleep, clearing proteins linked to neurodegeneration.' },
    { type: 'multiple_choice', question: 'What cognitive effect does even 2% dehydration have?', options: ['None', 'Impaired cognitive performance', 'Improved focus', 'Better memory'], correctAnswer: 1, explanation: 'Even mild dehydration measurably impairs cognitive performance and mood.' },
    { type: 'multiple_choice', question: 'What supplement has evidence for cognitive benefits under stress?', options: ['Vitamin C', 'Creatine (3–5g daily)', 'Calcium', 'Iron'], correctAnswer: 1, explanation: 'Creatine improves short-term memory and reasoning, especially under stress or sleep deprivation.' },
    { type: 'multiple_choice', question: 'How does exercise affect the hippocampus?', options: ['Shrinks it', 'Physically grows it through increased BDNF and neurogenesis', 'No effect', 'Damages it'], correctAnswer: 1, explanation: 'Regular exercise increases hippocampal volume through BDNF-driven neurogenesis.' },
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What are the three needs in Self-Determination Theory?', options: ['Safety, belonging, esteem', 'Autonomy, competence, relatedness', 'Food, water, shelter', 'Power, achievement, affiliation'], correctAnswer: 1, explanation: 'SDT identifies autonomy (control), competence (capability), and relatedness (connection) as essential.' },
    { type: 'multiple_choice', question: 'What type of motivation is "I train because it is who I am"?', options: ['External regulation', 'Introjected regulation', 'Integrated regulation', 'Amotivation'], correctAnswer: 2, explanation: 'Integrated regulation means the behaviour is fully aligned with your sense of identity.' },
    { type: 'multiple_choice', question: 'Why do rigid externally imposed programmes often fail?', options: ['They are too easy', 'They undermine autonomy', 'They are too short', 'The exercises are wrong'], correctAnswer: 1, explanation: 'Removing choice undermines the autonomy need, which is essential for sustained intrinsic motivation.' },
    { type: 'multiple_choice', question: 'What is the relationship between action and motivation?', options: ['Motivation always comes first', 'Action generates motivation — not the other way around', 'They are unrelated', 'Motivation is purely genetic'], correctAnswer: 1, explanation: 'Starting the action creates the motivation to continue — waiting for motivation leads to inaction.' },
    { type: 'multiple_choice', question: 'How can you support competence in training?', options: ['Make the programme too easy', 'Track progressive overload and celebrate small wins', 'Avoid challenging exercises', 'Never change the programme'], correctAnswer: 1, explanation: 'Visible progress and acknowledged achievements satisfy the competence need.' },
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'According to James Clear, what are the three layers of behaviour change?', options: ['Input, process, output', 'Identity, process, outcome', 'Goal, plan, action', 'Thought, feeling, behaviour'], correctAnswer: 1, explanation: 'Clear describes behaviour change as three concentric layers: identity (core), process, and outcome.' },
    { type: 'multiple_choice', question: 'How is identity actually changed?', options: ['Through declarations and affirmations', 'Through accumulated evidence — consistent actions that "vote" for the new identity', 'Through a single dramatic event', 'It cannot be changed'], correctAnswer: 1, explanation: 'Identity shifts through accumulated votes — small consistent actions that provide evidence.' },
    { type: 'multiple_choice', question: 'What is more powerful: "I should train today" or "I don\'t skip training"?', options: ['"I should train today"', '"I don\'t skip training" — because it is identity-based', 'They are equally effective', 'Neither is effective'], correctAnswer: 1, explanation: 'Identity-based framing is more powerful because it connects the action to who you are, not just what you should do.' },
    { type: 'multiple_choice', question: 'What are identity conflicts during personal change?', options: ['Arguments with friends', 'Resistance from others and feelings of impostor syndrome as you adopt new behaviours', 'Physical pain', 'Financial difficulties'], correctAnswer: 1, explanation: 'Others may resist your changes, and you may feel like an imposter in your new identity — both are normal.' },
    { type: 'multiple_choice', question: 'What is the best response to identity conflicts?', options: ['Return to old behaviours', 'Continue voting for the new identity while accepting discomfort is temporary', 'Avoid everyone who knew the old you', 'Pretend nothing has changed'], correctAnswer: 1, explanation: 'Continue consistent action toward the new identity — the transition discomfort is temporary.' },
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'Why does mental rehearsal improve physical performance?', options: ['It is a placebo effect', 'It activates similar motor cortex regions as physical practice, strengthening neural pathways', 'It replaces the need for training', 'It only works for elite athletes'], correctAnswer: 1, explanation: 'Mental imagery activates motor cortex regions, strengthening the neural pathways used in actual performance.' },
    { type: 'multiple_choice', question: 'Why can outcome visualisation alone reduce effort?', options: ['It cannot', 'The brain partially "experiences" the reward, reducing motivation to earn it', 'Outcome visualisation is always harmful', 'It only affects beginners'], correctAnswer: 1, explanation: 'Premature reward experience from outcome visualisation can reduce the drive to actually achieve it.' },
    { type: 'multiple_choice', question: 'What makes visualisation more effective?', options: ['Keeping it vague', 'Multi-sensory detail — sight, sound, feel, even smell', 'Only visualising success', 'Doing it once'], correctAnswer: 1, explanation: 'Richer, more detailed imagery creates a stronger neural effect.' },
    { type: 'multiple_choice', question: 'Should you include adversity in your visualisation?', options: ['No — only visualise perfect execution', 'Yes — visualising overcoming obstacles improves real-world resilience', 'Only negative scenarios', 'Adversity visualisation is harmful'], correctAnswer: 1, explanation: 'Including challenges and your response to them prepares you for real-world imperfection.' },
    { type: 'multiple_choice', question: 'How long should daily mental rehearsal practice be?', options: ['1 minute', '5–10 minutes', '60 minutes', '2 hours'], correctAnswer: 1, explanation: '5–10 minutes daily is sufficient for measurable performance benefits from mental rehearsal.' },
  ]),
];

// Unit 4 — Resilience Integration & Lifelong Practice
export const mindsetL3Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What are the five pillars of daily resilience?', options: ['Strength, cardio, flexibility, diet, sleep', 'Physiological regulation, physical challenge, cognitive engagement, emotional processing, social connection', 'Work, rest, play, eat, sleep', 'Breathing, cold, heat, journaling, meditation'], correctAnswer: 1, explanation: 'The five pillars cover physiology, physicality, cognition, emotion, and social connection.' },
    { type: 'multiple_choice', question: 'How should you approach implementing the five pillars?', options: ['All five simultaneously from day one', 'One pillar per week, building gradually', 'Only the pillars you enjoy', 'Only during training days'], correctAnswer: 1, explanation: 'Gradual stacking prevents overwhelm and builds sustainable habits.' },
    { type: 'multiple_choice', question: 'What is mental training periodisation?', options: ['Only training mentally on weekdays', 'Alternating high-intensity and recovery phases, with deload weeks every 4–6 weeks', 'Always pushing to maximum', 'Only practising when stressed'], correctAnswer: 1, explanation: 'Like physical training, mental training needs intensity cycling with scheduled recovery.' },
    { type: 'multiple_choice', question: 'What should your protocol specify for difficult life periods?', options: ['Stop all practices', 'Minimum viable doses — even 5 minutes of breathing is better than nothing', 'Double the intensity', 'Only exercise more'], correctAnswer: 1, explanation: 'Minimum viable doses maintain the habit even when full practice is not possible.' },
    { type: 'multiple_choice', question: 'How often should you review your resilience system?', options: ['Never — set it and forget it', 'Weekly quick review, with monthly and quarterly deeper reviews', 'Only when something goes wrong', 'Annually'], correctAnswer: 1, explanation: 'Regular reviews at multiple intervals ensure the system stays relevant and effective.' },
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What does the A-A-A-A setback protocol stand for?', options: ['Avoid, Analyse, Attempt, Achieve', 'Assess, Accept, Adapt, Act', 'Acknowledge, Adjust, Apply, Advance', 'Assess, Avoid, Accept, Achieve'], correctAnswer: 1, explanation: 'Assess reality, Accept what happened, Adapt your plan, Act with the smallest meaningful step.' },
    { type: 'multiple_choice', question: 'How does reflection differ from rumination?', options: ['They are the same process', 'Reflection produces action points; rumination is circular without resolution', 'Rumination is more productive', 'Reflection is unhealthy'], correctAnswer: 1, explanation: 'Reflection has direction and produces conclusions; rumination loops without progress.' },
    { type: 'multiple_choice', question: 'What should you do if you have been thinking about a setback for 20+ minutes without new insight?', options: ['Keep thinking harder', 'Write down three controllable actions and do one immediately', 'Call a friend to discuss', 'Go to sleep'], correctAnswer: 1, explanation: 'Breaking the rumination cycle requires shifting to concrete, controllable action.' },
    { type: 'multiple_choice', question: 'Is setback recovery a linear process?', options: ['Yes — it follows clear stages', 'No — it oscillates between emotional states with gradually decreasing intensity', 'It happens instantly', 'It only occurs with therapy'], correctAnswer: 1, explanation: 'Recovery is messy and non-linear — good days and bad days are normal throughout the process.' },
    { type: 'multiple_choice', question: 'What is the first practical step after a major setback?', options: ['Make a comprehensive recovery plan', 'Take the smallest meaningful action — one constructive thing today', 'Ignore it and carry on', 'Wait until you feel better'], correctAnswer: 1, explanation: 'The smallest step breaks paralysis and begins momentum — do not wait for a complete plan.' },
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'How harmful is loneliness to health?', options: ['Mildly inconvenient', 'Equivalent to smoking 15 cigarettes per day', 'Only affects mental health', 'Has no measurable health impact'], correctAnswer: 1, explanation: 'Meta-analysis of 300,000+ people found loneliness as damaging as heavy smoking.' },
    { type: 'multiple_choice', question: 'What matters more — relationship quantity or quality?', options: ['Quantity — more connections is always better', 'Quality — one deeply supportive relationship outweighs a hundred superficial ones', 'Neither matters', 'Only professional relationships matter'], correctAnswer: 1, explanation: 'Relationship quality — trust, reciprocity, emotional safety — is more protective than quantity.' },
    { type: 'multiple_choice', question: 'What characterises assertive (not aggressive) communication?', options: ['Yelling your needs', 'Stating needs clearly without attacking the other person', 'Saying nothing to avoid conflict', 'Manipulating others to get what you want'], correctAnswer: 1, explanation: 'Assertive communication is clear and direct while respecting both parties.' },
    { type: 'multiple_choice', question: 'What makes boundaries effective?', options: ['Being vague so others can interpret them', 'Being clear, consistent, compassionate, with known consequences', 'Only setting them when angry', 'Changing them based on others\' reactions'], correctAnswer: 1, explanation: 'Effective boundaries are specific, consistently enforced, kind in delivery, and backed by consequences.' },
    { type: 'multiple_choice', question: 'How should you approach curating your social environment?', options: ['Ruthlessly cut everyone who is not perfect', 'Deliberately add growth-supportive connections while managing existing relationships with boundaries', 'Only socialise with successful people', 'Isolate yourself for focus'], correctAnswer: 1, explanation: 'The approach is additive — bring in supportive people while setting appropriate boundaries with others.' },
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is the difference between hedonic and eudaimonic wellbeing?', options: ['No difference', 'Hedonic = pleasure/comfort; Eudaimonic = meaning/purpose/potential', 'Hedonic is better long-term', 'Eudaimonic is about physical health'], correctAnswer: 1, explanation: 'Hedonic seeks pleasure; eudaimonic seeks meaning — research shows eudaimonic produces deeper, lasting satisfaction.' },
    { type: 'multiple_choice', question: 'How are values best identified?', options: ['By what you say matters', 'By what you consistently prioritise when things get difficult', 'By what others value', 'By personality tests'], correctAnswer: 1, explanation: 'True values are revealed by behaviour under pressure, not by stated preferences.' },
    { type: 'multiple_choice', question: 'What is values-based decision-making?', options: ['Following rules set by others', 'Asking "which option aligns with my core values?" when facing decisions', 'Always choosing the easiest option', 'Only making decisions when calm'], correctAnswer: 1, explanation: 'Using your identified core values as a decision framework cuts through analysis paralysis.' },
    { type: 'multiple_choice', question: 'Why does values-aligned living sustain motivation?', options: ['It does not', 'It creates a sense of coherence — you are acting in line with who you truly are', 'It eliminates all difficulty', 'It requires no effort'], correctAnswer: 1, explanation: 'When actions align with deepest values, intrinsic motivation sustains effort far longer than external rewards.' },
    { type: 'multiple_choice', question: 'What is the values clarification "end of life" exercise?', options: ['Planning your funeral', 'Imagining looking back at your life and asking what you want to have been true', 'A medical assessment', 'A legal document'], correctAnswer: 1, explanation: 'This reflection exercise reveals your deepest values by considering what would matter most in retrospect.' },
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'What is the key difference between coaching and therapy?', options: ['No difference', 'Coaching helps find answers through questions; therapy treats clinical conditions', 'Coaching is superior', 'Therapy is for everyone; coaching is for athletes only'], correctAnswer: 1, explanation: 'Coaching facilitates self-discovery; therapy provides evidence-based treatment for clinical conditions.' },
    { type: 'multiple_choice', question: 'What is the 80/20 rule in active listening?', options: ['Talk 80%, listen 20%', 'Listen 80%, speak 20%', 'Agree with 80% of what is said', 'Use 80% of the session for exercises'], correctAnswer: 1, explanation: 'Effective coaching involves far more listening than speaking.' },
    { type: 'multiple_choice', question: 'What is a "powerful question"?', options: ['A demanding question', 'An open-ended, non-judgemental question that promotes self-discovery', 'A yes/no question', 'A trick question'], correctAnswer: 1, explanation: 'Powerful questions help others find their own answers, which are more impactful than advice.' },
    { type: 'multiple_choice', question: 'When must you refer to professional help?', options: ['Never', 'When someone describes persistent low mood, self-harm, panic attacks, or trauma responses', 'Only if they request it', 'Only in emergencies'], correctAnswer: 1, explanation: 'Clinical symptoms exceed peer coaching scope and require trained professional intervention.' },
    { type: 'multiple_choice', question: 'Why is resisting the urge to give advice important in coaching?', options: ['Advice is always wrong', 'People\'s own discoveries are more powerful and lasting than being told what to do', 'You should never help anyone', 'Advice makes you liable'], correctAnswer: 1, explanation: 'Self-discovered insights create stronger commitment and lasting change than externally given advice.' },
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'What does "unbreakable" mean in the course philosophy?', options: ['Never feeling pain', 'Having the tools and self-awareness to recover from anything and grow stronger', 'Being physically invincible', 'Never failing'], correctAnswer: 1, explanation: 'Unbreakable means having resilience systems that enable recovery and growth, not invulnerability.' },
    { type: 'multiple_choice', question: 'What is the ultimate performance metric according to the course?', options: ['Maximum intensity', 'Perfect technique', 'Sustainability — consistency over years', 'Speed of progress'], correctAnswer: 2, explanation: '3x/week for 10 years beats 7x/week for 3 months. Sustainability is the ultimate metric.' },
    { type: 'multiple_choice', question: 'What should a lifelong maintenance plan include?', options: ['Only training', 'Daily non-negotiables, weekly practices, and periodic reviews', 'Whatever you feel like each day', 'Only cold exposure'], correctAnswer: 1, explanation: 'A structured plan with daily, weekly, and periodic elements maintains resilience long-term.' },
    { type: 'multiple_choice', question: 'What is the purpose of deload weeks in mental training?', options: ['To lose progress', 'To prevent psychological burnout and maintain long-term sustainability', 'They are unnecessary', 'To test maximum capacity'], correctAnswer: 1, explanation: 'Deload weeks prevent burnout and allow recovery, ensuring practices remain sustainable.' },
    { type: 'multiple_choice', question: 'Where does resilience ultimately live?', options: ['In textbooks', 'In the accumulated evidence of who you choose to be, every single day', 'In supplements', 'In genetic potential'], correctAnswer: 1, explanation: 'Resilience is demonstrated through daily consistent action, not theoretical knowledge.' },
  ]),
];
