import type { UnitAssessment, ChapterQuiz } from '../types';

// ── Unit 1: Advanced Macronutrients & Energy Systems ──

export const nutritionL3Unit1Assessment: UnitAssessment = {
  unitNumber: 1, title: 'Unit 1 Assessment — Advanced Macronutrients & Energy Systems',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the primary fuel source during high-intensity, short-duration exercise?', options: ['Fat oxidation', 'Muscle glycogen via glycolysis', 'Ketone bodies', 'Amino acid oxidation'], correctAnswer: 1, explanation: 'Glycolysis rapidly converts glucose to pyruvate for ATP during intense efforts.' },
    { type: 'multiple_choice', question: 'Approximately how many ATP molecules does aerobic metabolism yield per glucose molecule?', options: ['2', '12', '38', '100'], correctAnswer: 2, explanation: 'The full aerobic pathway (glycolysis + Krebs cycle + ETC) yields approximately 38 ATP.' },
    { type: 'multiple_choice', question: 'What is the leucine threshold for maximally stimulating muscle protein synthesis?', options: ['0.5–1g', '2.5–3g', '5–6g', '10g'], correctAnswer: 1, explanation: 'Approximately 2.5–3g of leucine is needed to maximally stimulate MPS.' },
    { type: 'multiple_choice', question: 'Which fatty acid group promotes anti-inflammatory pathways?', options: ['Omega-6', 'Omega-3', 'Trans fats', 'Saturated fats'], correctAnswer: 1, explanation: 'Omega-3 fatty acids (EPA/DHA) promote anti-inflammatory responses.' },
    { type: 'multiple_choice', question: 'What percentage of TDEE does NEAT typically account for?', options: ['1–5%', '5–10%', '15–30%', '50–60%'], correctAnswer: 2, explanation: 'NEAT accounts for approximately 15–30% and is the most variable component.' },
    { type: 'multiple_choice', question: 'What is adaptive thermogenesis?', options: ['Increased metabolism from overeating', 'The body reducing energy expenditure beyond predicted levels during prolonged dieting', 'Increased body temperature from exercise', 'The thermic effect of protein'], correctAnswer: 1, explanation: 'Adaptive thermogenesis is the body conserving energy during caloric restriction beyond what weight loss alone would predict.' },
    { type: 'multiple_choice', question: 'What is the recommended protein distribution strategy for maximising MPS?', options: ['All protein in one meal', 'Two large meals', '3–5 meals each hitting the leucine threshold', 'Continuous sipping of protein shakes'], correctAnswer: 2, explanation: 'Distributing protein across 3–5 meals, each reaching the leucine threshold, maximises total daily MPS.' },
    { type: 'scenario', scenario: 'A person consumes 120g protein daily but eats 80g at dinner and splits the rest between two small meals.', question: 'What is the main issue with this distribution?', options: ['Total protein is too low', 'Most meals do not reach the leucine threshold', 'Protein at dinner is wasted', 'They need more fat'], correctAnswer: 1, explanation: 'The two smaller meals (20g each) likely fall below the leucine threshold, reducing total daily MPS stimulation.' },
    { type: 'multiple_choice', question: 'Which component of TDEE is most affected by a caloric deficit?', options: ['BMR only', 'EAT only', 'NEAT and hormonal regulation', 'TEF only'], correctAnswer: 2, explanation: 'NEAT decreases unconsciously and hormones adapt, together causing the largest adaptive response.' },
    { type: 'multiple_choice', question: 'What is the ideal omega-6 to omega-3 ratio?', options: ['15:1', '10:1', '2:1 to 4:1', '1:10'], correctAnswer: 2, explanation: 'A ratio of 2:1 to 4:1 is considered ideal but the modern Western diet is typically 15:1 or higher.' },
    { type: 'multiple_choice', question: 'Alcohol provides how many calories per gram?', options: ['4', '7', '9', '0'], correctAnswer: 1, explanation: 'Alcohol provides 7 calories per gram — almost as energy-dense as fat.' },
    { type: 'multiple_choice', question: 'By how much can alcohol suppress muscle protein synthesis when consumed post-training?', options: ['5%', '15%', 'Up to 37%', '75%'], correctAnswer: 2, explanation: 'Research shows alcohol can suppress MPS by up to 37% even when adequate protein is consumed.' },
  ],
};

export const nutritionL3Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Micronutrients, Supplementation & Special Populations',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'Why do fat-soluble vitamins carry a risk of toxicity?', options: ['They are absorbed quickly', 'They are stored in the body and can accumulate', 'They require large doses to be effective', 'They interact with medications'], correctAnswer: 1, explanation: 'Fat-soluble vitamins are stored in liver and adipose tissue, so excess accumulates rather than being excreted.' },
    { type: 'multiple_choice', question: 'What daily vitamin D supplementation does Public Health England recommend for UK adults in autumn and winter?', options: ['5 micrograms', '10 micrograms (400 IU)', '50 micrograms', '100 micrograms'], correctAnswer: 1, explanation: 'PHE recommends 10 micrograms (400 IU) daily during autumn and winter.' },
    { type: 'multiple_choice', question: 'Which supplement has the strongest evidence base for improving strength and power?', options: ['BCAAs', 'Glutamine', 'Creatine monohydrate', 'Testosterone boosters'], correctAnswer: 2, explanation: 'Creatine monohydrate is the most researched and consistently supported sports supplement.' },
    { type: 'multiple_choice', question: 'What is the effective caffeine dose for performance enhancement?', options: ['1mg per kg body weight', '3–6mg per kg body weight', '10–15mg per kg body weight', '20mg per kg body weight'], correctAnswer: 1, explanation: '3–6mg/kg consumed 30–60 minutes before training is the evidence-based dose.' },
    { type: 'multiple_choice', question: 'Which nutrient must all vegans supplement without exception?', options: ['Iron', 'Calcium', 'Vitamin B12', 'Vitamin C'], correctAnswer: 2, explanation: 'No reliable plant source of B12 exists. Deficiency causes irreversible nerve damage.' },
    { type: 'multiple_choice', question: 'How much additional energy per day is recommended during the third trimester of pregnancy?', options: ['0 extra calories', 'Approximately 200 calories', 'Approximately 500 calories', 'Double normal intake'], correctAnswer: 1, explanation: 'Only approximately 200 additional calories per day are recommended, and only in the third trimester.' },
    { type: 'multiple_choice', question: 'What daily protein intake may older adults need to combat sarcopenia?', options: ['0.8g per kg', '1.2–1.6g per kg', '3g per kg', '0.5g per kg'], correctAnswer: 1, explanation: 'Older adults may need 1.2–1.6g/kg to overcome anabolic resistance and maintain muscle mass.' },
    { type: 'scenario', scenario: 'A vegan client reports fatigue, tingling in their hands, and difficulty concentrating. They do not take any supplements.', question: 'Which deficiency is most likely?', options: ['Iron', 'Vitamin D', 'Vitamin B12', 'Zinc'], correctAnswer: 2, explanation: 'Neurological symptoms (tingling, concentration issues) combined with fatigue in a non-supplementing vegan strongly suggest B12 deficiency.' },
    { type: 'multiple_choice', question: 'In the UK, who is legally qualified to provide medical nutrition therapy?', options: ['Personal trainers with a nutrition certificate', 'Registered Dietitians (HCPC regulated)', 'Nutritional therapists', 'Anyone with a food hygiene certificate'], correctAnswer: 1, explanation: 'Only Registered Dietitians regulated by the HCPC are qualified for medical nutrition therapy in the UK.' },
    { type: 'multiple_choice', question: 'Which form of iron is more bioavailable?', options: ['Non-haem iron from plants', 'Haem iron from animal sources', 'Supplemental iron oxide', 'Iron from fortified cereals'], correctAnswer: 1, explanation: 'Haem iron from animal sources is absorbed approximately 2–3 times more efficiently than non-haem iron.' },
    { type: 'multiple_choice', question: 'What is the recommended folic acid supplementation during early pregnancy?', options: ['100 micrograms', '400 micrograms daily', '1000 micrograms', '5000 micrograms'], correctAnswer: 1, explanation: '400 micrograms daily from trying to conceive until 12 weeks of pregnancy.' },
    { type: 'multiple_choice', question: 'Plant-based ALA converts to EPA/DHA at approximately what rate?', options: ['50–60%', '25–30%', '5–10%', '0%'], correctAnswer: 2, explanation: 'ALA conversion to EPA/DHA is very poor — approximately 5–10% — which is why algae-based supplements are recommended for vegans.' },
  ],
};

export const nutritionL3Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Sports Nutrition & Performance Fuelling',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What protein intake is recommended during a fat loss phase?', options: ['0.8g per kg', '1.2g per kg', '2.0–2.4g per kg', '4g per kg'], correctAnswer: 2, explanation: 'Higher protein (2.0–2.4g/kg) during a deficit preserves muscle mass and increases satiety.' },
    { type: 'multiple_choice', question: 'What carbohydrate loading protocol is currently recommended?', options: ['Depletion for 3 days then loading for 3 days', '8–12g/kg carbohydrate for 36–48 hours with tapering training', 'Zero carbs for a week then unlimited carbs', 'Normal eating with extra pasta the night before'], correctAnswer: 1, explanation: 'The modern simplified protocol of 8–12g/kg for 36–48 hours achieves comparable glycogen levels without depletion.' },
    { type: 'multiple_choice', question: 'For events over 2.5 hours, what is the recommended intra-event carbohydrate intake?', options: ['10g per hour', '30g per hour', 'Up to 90g per hour using glucose-fructose combinations', '150g per hour'], correctAnswer: 2, explanation: 'Up to 90g/hour using multiple transportable carbohydrates (2:1 glucose:fructose) for ultra-endurance events.' },
    { type: 'multiple_choice', question: 'What caloric surplus is appropriate for a lean bulk in trained individuals?', options: ['50–100 calories', '200–400 calories', '1000+ calories', 'No surplus needed'], correctAnswer: 1, explanation: 'A modest 200–400 calorie surplus provides sufficient energy for muscle growth with minimal fat gain.' },
    { type: 'multiple_choice', question: 'At what level of dehydration does measurable performance decline typically begin?', options: ['0.5% body weight', '2% body weight', '5% body weight', '10% body weight'], correctAnswer: 1, explanation: 'Dehydration of 2% or more of body weight consistently impairs both physical and cognitive performance.' },
    { type: 'scenario', scenario: 'An athlete has been dieting for 14 weeks. They report persistent fatigue, strength loss, poor sleep, and extreme hunger.', question: 'What is the most appropriate recommendation?', options: ['Reduce calories further', 'Add more cardio', 'Plan a 1–2 week diet break at maintenance calories', 'Switch to a keto diet'], correctAnswer: 2, explanation: 'After 14 weeks, these symptoms indicate metabolic adaptation. A diet break at maintenance is the appropriate response.' },
    { type: 'multiple_choice', question: 'Which body composition method is considered the practical gold standard?', options: ['BMI calculation', 'Bioelectrical impedance (BIA) scales', 'DEXA scan', 'Waist-to-hip ratio'], correctAnswer: 2, explanation: 'DEXA scans use low-dose X-rays to differentiate bone, lean mass, and fat mass with approximately 1–2% accuracy.' },
    { type: 'multiple_choice', question: 'What is the primary electrolyte of concern during prolonged endurance exercise?', options: ['Potassium', 'Calcium', 'Sodium', 'Magnesium'], correctAnswer: 2, explanation: 'Sodium is the primary electrolyte lost in sweat and its depletion can cause dangerous hyponatraemia.' },
    { type: 'multiple_choice', question: 'What is the recommended fat loss rate for non-obese individuals?', options: ['1–2kg per week', '0.25–0.5kg per week', '3kg per week', '0.05kg per week'], correctAnswer: 1, explanation: 'A rate of 0.25–0.5kg per week minimises muscle loss and is sustainable.' },
    { type: 'multiple_choice', question: 'Why is body weight alone an unreliable measure of progress?', options: ['Scales are inaccurate', 'Daily fluctuations of 1–3kg from water, glycogen, and gut contents mask true changes', 'Weight never changes', 'Muscle weighs more than fat'], correctAnswer: 1, explanation: 'Daily weight fluctuations from non-fat factors obscure the actual trend in body composition.' },
    { type: 'multiple_choice', question: 'What is hyponatraemia?', options: ['High blood sodium', 'Dangerously low blood sodium from over-drinking plain water', 'Dehydration', 'High blood sugar'], correctAnswer: 1, explanation: 'Hyponatraemia is dangerously low blood sodium, usually caused by over-drinking water without sodium replacement.' },
    { type: 'multiple_choice', question: 'How much glycogen does a high-volume training session typically deplete?', options: ['5–10%', '25–40%', '80–100%', '0%'], correctAnswer: 1, explanation: 'A typical high-volume session (20–25 working sets) depletes approximately 25–40% of muscle glycogen.' },
  ],
};

export const nutritionL3Unit4Assessment: UnitAssessment = {
  unitNumber: 4, title: 'Unit 4 Assessment — Nutrition Psychology, Behaviour Change & Professional Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the difference between hunger and appetite?', options: ['They are the same thing', 'Hunger is physiological; appetite can be triggered by environmental or emotional cues', 'Appetite is physiological; hunger is psychological', 'Hunger only occurs when fasting'], correctAnswer: 1, explanation: 'Hunger is a physiological need for energy; appetite is the desire to eat, influenced by many non-physiological factors.' },
    { type: 'multiple_choice', question: 'Using a smaller plate reduces intake by approximately how much?', options: ['5%', '10%', '20%', '50%'], correctAnswer: 2, explanation: 'Research shows using a 25cm plate instead of a 30cm plate reduces intake by approximately 20%.' },
    { type: 'multiple_choice', question: 'In the Transtheoretical Model, which stage involves actively changing behaviour?', options: ['Contemplation', 'Preparation', 'Action', 'Maintenance'], correctAnswer: 2, explanation: 'The Action stage is when the person is actively implementing new behaviours.' },
    { type: 'multiple_choice', question: 'What is habit stacking?', options: ['Adding multiple habits at once', 'Attaching a new behaviour to an existing established habit', 'Replacing all bad habits simultaneously', 'Tracking habits in a journal'], correctAnswer: 1, explanation: 'Habit stacking links a new desired behaviour to an existing automatic habit to reduce cognitive effort.' },
    { type: 'multiple_choice', question: 'Which of these is a warning sign of disordered eating?', options: ['Enjoying a variety of foods', 'Occasional overeating at celebrations', 'Intense guilt after eating and preoccupation with food that dominates daily thoughts', 'Choosing to meal prep on Sundays'], correctAnswer: 2, explanation: 'Intense guilt and food preoccupation that dominates daily life are key psychological warning signs.' },
    { type: 'scenario', scenario: 'A friend tells you they skip meals to compensate for "bad eating days" and exercise excessively after eating cake. They seem distressed about food.', question: 'What is the most appropriate response?', options: ['Give them a meal plan', 'Tell them to stop worrying', 'Express concern without judgement and encourage them to speak with their GP', 'Ignore it — it is their choice'], correctAnswer: 2, explanation: 'Compassionate concern and referral to appropriate professional support is the responsible response.' },
    { type: 'multiple_choice', question: 'Which principle of motivational interviewing involves avoiding arguments with resistant clients?', options: ['Express Empathy', 'Develop Discrepancy', 'Roll with Resistance', 'Support Self-Efficacy'], correctAnswer: 2, explanation: 'Rolling with Resistance means acknowledging the person\'s perspective rather than confronting it.' },
    { type: 'multiple_choice', question: 'In the UK, the title "dietitian" is protected by which body?', options: ['NHS', 'HCPC (Health and Care Professions Council)', 'AfN (Association for Nutrition)', 'British Nutrition Foundation'], correctAnswer: 1, explanation: 'The title "dietitian" is legally protected by the HCPC in the UK.' },
    { type: 'multiple_choice', question: 'What is the most reliable predictor of sustained behaviour change?', options: ['Motivation', 'Self-efficacy', 'Knowledge', 'Fear of consequences'], correctAnswer: 1, explanation: 'Self-efficacy — belief in your ability to succeed — is one of the strongest predictors of sustained change.' },
    { type: 'multiple_choice', question: 'What is the cheapest approach to healthy eating?', options: ['Buying pre-made meals', 'Ordering meal kit deliveries', 'Buying raw ingredients in bulk and cooking them yourself', 'Eating out at healthy restaurants'], correctAnswer: 2, explanation: 'Buying and cooking raw ingredients is the most affordable approach by a significant margin.' },
    { type: 'multiple_choice', question: 'What does "change talk" refer to in motivational interviewing?', options: ['Talking about the weather to build rapport', 'Language that favours movement toward change', 'Telling someone what they must change', 'Discussing past failures'], correctAnswer: 1, explanation: 'Change talk is any language expressing desire, ability, reason, or need for change.' },
    { type: 'multiple_choice', question: 'Eating while distracted increases intake by approximately how much?', options: ['1–2%', '10–25%', '50%', '100%'], correctAnswer: 1, explanation: 'Research shows eating while distracted by TV or phones increases intake by 10–25%.' },
  ],
};

// ── Final Assessment ──
export const nutritionL3FinalAssessment: UnitAssessment = {
  unitNumber: 0, title: 'Level 3 Nutrition Final Assessment',
  passMarkPercent: 80, pickCount: 40,
  questions: [
    ...nutritionL3Unit1Assessment.questions,
    ...nutritionL3Unit2Assessment.questions,
    ...nutritionL3Unit3Assessment.questions,
    ...nutritionL3Unit4Assessment.questions,
  ],
};

// ── Chapter Quizzes ──
function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

// Unit 1 chapter quizzes
export const nutritionL3Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'Where does glycolysis occur?', options: ['Mitochondria', 'Cell nucleus', 'Cytoplasm', 'Endoplasmic reticulum'], correctAnswer: 2, explanation: 'Glycolysis occurs in the cytoplasm of cells.' },
    { type: 'multiple_choice', question: 'How many ATP molecules does glycolysis alone produce per glucose molecule?', options: ['2', '12', '36', '38'], correctAnswer: 0, explanation: 'Glycolysis yields 2 ATP per glucose molecule.' },
    { type: 'multiple_choice', question: 'What happens to pyruvate when oxygen is insufficient?', options: ['It enters the Krebs cycle', 'It is converted to lactate', 'It is stored as glycogen', 'It is excreted'], correctAnswer: 1, explanation: 'Without oxygen, pyruvate is converted to lactate via anaerobic metabolism.' },
    { type: 'multiple_choice', question: 'How much glycogen can muscles typically store?', options: ['50–100g', '300–500g', '1000–1500g', '2000g'], correctAnswer: 1, explanation: 'Muscles store approximately 300–500g of glycogen.' },
    { type: 'multiple_choice', question: 'What sensation is associated with glycogen depletion during exercise?', options: ['Nausea', '"Hitting the wall"', 'Cramping', 'Dizziness'], correctAnswer: 1, explanation: 'Glycogen depletion leads to the fatigue sensation athletes describe as "hitting the wall."' },
    { type: 'multiple_choice', question: 'Which energy system dominates during a heavy set of squats?', options: ['Aerobic', 'Anaerobic glycolysis', 'Fat oxidation', 'Ketone metabolism'], correctAnswer: 1, explanation: 'High-intensity, short-duration efforts rely primarily on anaerobic glycolysis.' },
    { type: 'multiple_choice', question: 'Liver glycogen primarily maintains what?', options: ['Muscle contraction', 'Blood glucose levels', 'Protein synthesis', 'Fat storage'], correctAnswer: 1, explanation: 'Liver glycogen maintains blood glucose, critical for brain function.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'What does MPS stand for?', options: ['Maximum Protein Serving', 'Muscle Protein Synthesis', 'Metabolic Protein Storage', 'Minimal Protein Supply'], correctAnswer: 1, explanation: 'MPS stands for Muscle Protein Synthesis.' },
    { type: 'multiple_choice', question: 'How long does resistance training elevate MPS?', options: ['30 minutes', '2–4 hours', '24–72 hours', '7 days'], correctAnswer: 2, explanation: 'Resistance training stimulates MPS for 24–72 hours after a session.' },
    { type: 'multiple_choice', question: 'What amino acid is most important for triggering MPS?', options: ['Glutamine', 'Leucine', 'Glycine', 'Tryptophan'], correctAnswer: 1, explanation: 'Leucine is the key amino acid trigger for MPS.' },
    { type: 'multiple_choice', question: 'How much protein per meal is generally needed to reach the leucine threshold?', options: ['5–10g', '15–20g', '25–40g', '60–80g'], correctAnswer: 2, explanation: 'Approximately 25–40g of high-quality protein per meal reaches the leucine threshold.' },
    { type: 'multiple_choice', question: 'Is the 30-minute "anabolic window" after training critical?', options: ['Yes, you must eat within 30 minutes', 'No, the window is measured in hours not minutes', 'Only for cardio', 'Only for beginners'], correctAnswer: 1, explanation: 'The anabolic window is measured in hours. Daily total and distribution matter more than exact post-workout timing.' },
    { type: 'multiple_choice', question: 'How many protein-rich meals per day is recommended for optimal MPS?', options: ['1–2', '3–5', '6–8', '10+'], correctAnswer: 1, explanation: '3–5 meals each hitting the leucine threshold maximises 24-hour MPS.' },
    { type: 'multiple_choice', question: 'Why might vegans need larger protein servings per meal?', options: ['Plant protein tastes worse', 'Plant proteins contain less leucine per gram', 'Plant protein is not real protein', 'Vegans need less protein overall'], correctAnswer: 1, explanation: 'Plant proteins typically contain less leucine per gram, requiring larger servings to reach the threshold.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'Cholesterol is the precursor to which type of hormones?', options: ['Peptide hormones', 'Steroid hormones', 'Thyroid hormones', 'Growth hormones'], correctAnswer: 1, explanation: 'Cholesterol is the precursor to steroid hormones including testosterone and oestrogen.' },
    { type: 'multiple_choice', question: 'What is the ideal omega-6 to omega-3 ratio?', options: ['15:1', '2:1 to 4:1', '1:1', '20:1'], correctAnswer: 1, explanation: 'The ideal ratio is 2:1 to 4:1, though the modern Western diet typically exceeds 15:1.' },
    { type: 'multiple_choice', question: 'What are industrial trans fats?', options: ['Natural fats found in dairy', 'Unsaturated fats altered by partial hydrogenation', 'Essential fatty acids', 'A type of omega-3'], correctAnswer: 1, explanation: 'Industrial trans fats are created through partial hydrogenation and increase cardiovascular risk.' },
    { type: 'multiple_choice', question: 'What percentage of daily calories should fat comprise for active individuals?', options: ['5–10%', '20–35%', '50–60%', '70–80%'], correctAnswer: 1, explanation: 'Fat should comprise 20–35% of total daily calories for most active individuals.' },
    { type: 'multiple_choice', question: 'Which omega-3 forms are most bioactive?', options: ['ALA', 'EPA and DHA', 'GLA', 'CLA'], correctAnswer: 1, explanation: 'EPA and DHA from oily fish are the most bioactive forms; plant ALA converts poorly.' },
    { type: 'multiple_choice', question: 'Going below what fat intake risks hormonal disruption?', options: ['50% of calories', '35% of calories', '20% of calories', '5% of calories'], correctAnswer: 2, explanation: 'Going below 20% of calories from fat risks hormonal disruption and poor vitamin absorption.' },
    { type: 'multiple_choice', question: 'What minimum fat intake per kg body weight is recommended?', options: ['0.3g/kg', '0.7g/kg', '1.5g/kg', '2.0g/kg'], correctAnswer: 1, explanation: 'At least 0.7g fat per kilogram body weight protects hormonal function.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'Which TDEE component accounts for 60–70% of daily expenditure?', options: ['NEAT', 'BMR', 'TEF', 'EAT'], correctAnswer: 1, explanation: 'BMR accounts for approximately 60–70% of total daily energy expenditure.' },
    { type: 'multiple_choice', question: 'Which macronutrient has the highest thermic effect?', options: ['Fat', 'Carbohydrate', 'Protein', 'Alcohol'], correctAnswer: 2, explanation: 'Protein has the highest TEF at 20–30%, meaning more calories are burned digesting it.' },
    { type: 'multiple_choice', question: 'What is a diet break?', options: ['Skipping meals for a day', 'A planned 1–2 week period eating at maintenance calories', 'Stopping your diet permanently', 'Fasting for 48 hours'], correctAnswer: 1, explanation: 'Diet breaks are planned periods at maintenance to partially restore hormonal balance.' },
    { type: 'multiple_choice', question: 'NEAT can decrease by how many calories during a deficit?', options: ['10–20', '50–100', '200–400', '1000+'], correctAnswer: 2, explanation: 'NEAT can unconsciously decrease by 200–400 calories during caloric restriction.' },
    { type: 'multiple_choice', question: 'Is "metabolic damage" a scientifically supported concept?', options: ['Yes, diets permanently break your metabolism', 'No, adaptive thermogenesis is real but partially reverses when calories are restored', 'Yes, but only from keto diets', 'No, metabolism never changes'], correctAnswer: 1, explanation: '"Metabolic damage" has no scientific basis. Adaptive thermogenesis is real but partially reversible.' },
    { type: 'multiple_choice', question: 'Exercise activity thermogenesis (EAT) typically accounts for what percentage of TDEE?', options: ['5–10%', '30–40%', '50–60%', '70–80%'], correctAnswer: 0, explanation: 'Despite feeling important, EAT typically accounts for only 5–10% of total expenditure.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'When should a pre-training meal ideally be consumed?', options: ['Immediately before', '2–3 hours before', '6 hours before', 'The night before'], correctAnswer: 1, explanation: 'A balanced pre-training meal 2–3 hours before provides adequate fuel and digestion time.' },
    { type: 'multiple_choice', question: 'For sessions under 60 minutes, what intra-training nutrition is needed?', options: ['30g carbs per hour', '60g carbs per hour', 'Water only', '90g carbs per hour'], correctAnswer: 2, explanation: 'For moderate-intensity sessions under 60 minutes, water alone is sufficient.' },
    { type: 'multiple_choice', question: 'What does carbohydrate periodisation mean?', options: ['Never eating carbs', 'Matching carb intake to training demands day-by-day', 'Eating carbs only at night', 'Eliminating carbs for a week then loading'], correctAnswer: 1, explanation: 'Carbohydrate periodisation means eating more carbs on heavy training days and fewer on rest days.' },
    { type: 'multiple_choice', question: 'How much carbohydrate per kg is recommended on a heavy training day?', options: ['0–1g/kg', '2–3g/kg', '4–7g/kg', '10–15g/kg'], correctAnswer: 2, explanation: '4–7g carbohydrate per kilogram body weight on heavy training days.' },
    { type: 'multiple_choice', question: 'How urgently do you need to eat protein after training?', options: ['Within 5 minutes or gains are lost', 'Within 1–2 hours is ideal but not urgent if you ate before training', 'Within 30 seconds', 'It does not matter at all'], correctAnswer: 1, explanation: 'Within 1–2 hours is ideal, but urgency depends on pre-training nutrition and next session timing.' },
    { type: 'multiple_choice', question: 'During carbohydrate periodisation, which macronutrient stays constant?', options: ['Carbohydrate', 'Fat only', 'Protein', 'All macros change equally'], correctAnswer: 2, explanation: 'Protein and fat remain relatively constant; carbohydrate varies based on training demand.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'How many calories per gram does alcohol provide?', options: ['0', '4', '7', '9'], correctAnswer: 2, explanation: 'Alcohol provides 7 calories per gram.' },
    { type: 'multiple_choice', question: 'What happens to fat oxidation when you consume alcohol?', options: ['It increases', 'It is suppressed until alcohol is processed', 'It is unaffected', 'It doubles'], correctAnswer: 1, explanation: 'The body prioritises alcohol metabolism, suppressing fat oxidation until processing is complete.' },
    { type: 'multiple_choice', question: 'How does alcohol affect sleep?', options: ['Improves all sleep phases', 'Reduces REM and deep sleep phases', 'Has no effect on sleep', 'Only affects sleep if consumed after midnight'], correctAnswer: 1, explanation: 'Alcohol disrupts sleep architecture, particularly reducing REM and deep sleep.' },
    { type: 'multiple_choice', question: 'When is the best time to consume alcohol if you choose to drink?', options: ['Immediately after training', 'During training', 'On rest days, separated from training by 4–6 hours', 'Before training for confidence'], correctAnswer: 2, explanation: 'Rest days with at least 4–6 hours separation from any training window minimises impact.' },
    { type: 'multiple_choice', question: 'How many calories do four pints of lager approximately add?', options: ['200', '400', '800', '1500'], correctAnswer: 2, explanation: 'Four pints of lager adds approximately 800 calories — equivalent to a full meal.' },
    { type: 'multiple_choice', question: 'Alcohol acts as what type of substance regarding fluid balance?', options: ['Hydrating agent', 'Diuretic', 'Electrolyte', 'Neutral'], correctAnswer: 1, explanation: 'Alcohol is a diuretic — it inhibits ADH, promoting fluid loss and potential dehydration.' },
  ]),
];

// Unit 2 chapter quizzes
export const nutritionL3Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'Why can fat-soluble vitamins cause toxicity?', options: ['They are excreted quickly', 'They accumulate in the body', 'They are water-based', 'They evaporate'], correctAnswer: 1, explanation: 'Fat-soluble vitamins are stored in liver and adipose tissue, accumulating over time.' },
    { type: 'multiple_choice', question: 'Between which months is UVB insufficient for vitamin D production in the UK?', options: ['June to August', 'October to March', 'January to February', 'All year'], correctAnswer: 1, explanation: 'From October to March, the UK sun is too low for adequate UVB exposure.' },
    { type: 'multiple_choice', question: 'Why should pregnant women avoid liver?', options: ['It contains bacteria', 'Very high vitamin A (retinol) which can cause birth defects', 'It is too high in iron', 'It tastes bad'], correctAnswer: 1, explanation: 'Liver is very high in preformed retinol, which in excess can cause birth defects.' },
    { type: 'multiple_choice', question: 'What role does vitamin K play?', options: ['Energy production', 'Blood clotting and bone metabolism', 'Muscle growth', 'Fat storage'], correctAnswer: 1, explanation: 'Vitamin K is essential for blood clotting (K1) and bone metabolism (K2).' },
    { type: 'multiple_choice', question: 'Which groups are at higher risk of vitamin D deficiency?', options: ['People who spend a lot of time outdoors', 'People with darker skin, those who cover their skin, indoor workers, and older adults', 'Only children', 'Only athletes'], correctAnswer: 1, explanation: 'Darker skin, covered skin, limited outdoor time, and older age all increase risk.' },
    { type: 'multiple_choice', question: 'What does vitamin E primarily function as?', options: ['A hormone', 'An antioxidant', 'A coenzyme in glycolysis', 'A structural protein'], correctAnswer: 1, explanation: 'Vitamin E acts as an antioxidant, protecting cell membranes from oxidative damage.' },
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What do B vitamins primarily support?', options: ['Bone growth', 'Energy metabolism as coenzymes', 'Fat storage', 'Blood clotting'], correctAnswer: 1, explanation: 'B vitamins act as coenzymes in pathways that convert macronutrients into ATP.' },
    { type: 'multiple_choice', question: 'Why is B12 a particular concern for vegans?', options: ['It is expensive', 'It is found almost exclusively in animal products', 'Plants contain too much B12', 'It causes weight gain'], correctAnswer: 1, explanation: 'B12 is found almost exclusively in animal products; all vegans must supplement.' },
    { type: 'multiple_choice', question: 'What improves non-haem iron absorption?', options: ['Tea and coffee', 'Vitamin C', 'Calcium', 'Phytates'], correctAnswer: 1, explanation: 'Vitamin C significantly improves absorption of non-haem iron from plant sources.' },
    { type: 'multiple_choice', question: 'Magnesium is involved in how many enzymatic reactions?', options: ['10', '50', 'Over 300', 'Over 1000'], correctAnswer: 2, explanation: 'Magnesium is involved in over 300 enzymatic reactions in the body.' },
    { type: 'multiple_choice', question: 'Which mineral supports testosterone production?', options: ['Calcium', 'Iron', 'Zinc', 'Sodium'], correctAnswer: 2, explanation: 'Zinc supports immune function, protein synthesis, and testosterone production.' },
    { type: 'multiple_choice', question: 'What is the most common nutritional deficiency worldwide?', options: ['Vitamin C', 'Vitamin D', 'Iron', 'Calcium'], correctAnswer: 2, explanation: 'Iron deficiency is the most common nutritional deficiency worldwide.' },
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'What is the recommended daily creatine dose?', options: ['0.5g', '3–5g', '20g', '50g'], correctAnswer: 1, explanation: 'The standard maintenance dose is 3–5g per day, every day.' },
    { type: 'multiple_choice', question: 'Which supplement tier do BCAAs fall into for people with adequate protein intake?', options: ['Tier 1 — Strong evidence', 'Tier 2 — Moderate evidence', 'Tier 3 — Limited/no evidence', 'Not categorised'], correctAnswer: 2, explanation: 'BCAAs are redundant if total protein intake is adequate — Tier 3.' },
    { type: 'multiple_choice', question: 'How does creatine improve performance?', options: ['By burning fat', 'By increasing phosphocreatine stores for rapid ATP regeneration', 'By reducing appetite', 'By increasing testosterone'], correctAnswer: 1, explanation: 'Creatine increases phosphocreatine stores, improving capacity for short, intense efforts.' },
    { type: 'multiple_choice', question: 'When should caffeine be consumed for performance benefits?', options: ['During training', '30–60 minutes before training', '3 hours after training', 'Before bed'], correctAnswer: 1, explanation: 'Caffeine is most effective when consumed 30–60 minutes before training.' },
    { type: 'multiple_choice', question: 'What is a red flag in supplement marketing?', options: ['Published peer-reviewed research', 'Transparent ingredient dosing', 'Proprietary blends hiding individual ingredient doses', 'Third-party testing certification'], correctAnswer: 2, explanation: 'Proprietary blends that hide doses are a warning sign of marketing-driven products.' },
    { type: 'multiple_choice', question: 'Does creatine cause kidney damage in healthy individuals?', options: ['Yes, always', 'No — extensively studied for 30+ years with no evidence of harm', 'Only in women', 'Only at high doses'], correctAnswer: 1, explanation: 'Decades of research show no kidney damage from creatine in healthy individuals.' },
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'How many extra calories per day are needed during the third trimester?', options: ['0', 'Approximately 200', 'Approximately 500', '1000'], correctAnswer: 1, explanation: 'Only approximately 200 additional calories per day are recommended in the third trimester.' },
    { type: 'multiple_choice', question: 'When should folic acid supplementation begin?', options: ['At birth of the baby', 'From trying to conceive until 12 weeks', 'Only in the third trimester', 'After delivery'], correctAnswer: 1, explanation: '400 micrograms daily from the point of trying to conceive until 12 weeks of pregnancy.' },
    { type: 'multiple_choice', question: 'What protein intake may older adults need to combat sarcopenia?', options: ['0.5g/kg', '0.8g/kg', '1.2–1.6g/kg', '3g/kg'], correctAnswer: 2, explanation: 'Older adults may need 1.2–1.6g/kg daily to maintain muscle mass against anabolic resistance.' },
    { type: 'multiple_choice', question: 'What is sarcopenia?', options: ['Bone loss', 'Age-related loss of muscle mass and function', 'Fat gain in older adults', 'Vitamin deficiency'], correctAnswer: 1, explanation: 'Sarcopenia is the progressive loss of muscle mass and function associated with ageing.' },
    { type: 'multiple_choice', question: 'What is the UK advice on alcohol during pregnancy?', options: ['Up to 2 units per week', 'No more than 14 units', 'Complete abstinence', '1 glass of wine daily'], correctAnswer: 2, explanation: 'UK Chief Medical Officers advise complete abstinence as no safe level has been established.' },
    { type: 'multiple_choice', question: 'Why are older adults at higher risk of dehydration?', options: ['They sweat more', 'Reduced thirst sensation', 'They drink too much tea', 'Higher activity levels'], correctAnswer: 1, explanation: 'Ageing reduces thirst sensation, meaning older adults may not drink enough.' },
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What must all vegans supplement?', options: ['Vitamin C', 'Vitamin B12', 'Calcium', 'Iron'], correctAnswer: 1, explanation: 'No reliable plant source of B12 exists — supplementation is non-negotiable for vegans.' },
    { type: 'multiple_choice', question: 'Do complementary plant proteins need to be eaten at the same meal?', options: ['Yes, always', 'No — the body pools amino acids over 24 hours', 'Only at breakfast', 'Only post-training'], correctAnswer: 1, explanation: 'Amino acids are pooled over the day; variety across meals is sufficient.' },
    { type: 'multiple_choice', question: 'How many major allergens must be declared under UK food law?', options: ['5', '8', '14', '20'], correctAnswer: 2, explanation: 'UK food law requires declaration of 14 major allergens.' },
    { type: 'multiple_choice', question: 'What improves plant-based zinc absorption?', options: ['Consuming with tea', 'Soaking, sprouting, and fermenting', 'Taking calcium supplements', 'Eating raw only'], correctAnswer: 1, explanation: 'Soaking, sprouting, and fermenting reduce phytates that inhibit zinc absorption.' },
    { type: 'multiple_choice', question: 'What is coeliac disease?', options: ['A food preference', 'An autoimmune condition triggered by gluten', 'A type of food poisoning', 'Lactose intolerance'], correctAnswer: 1, explanation: 'Coeliac disease is an autoimmune condition requiring lifelong strict gluten avoidance.' },
    { type: 'multiple_choice', question: 'Why are algae-based omega-3 supplements recommended for vegans?', options: ['They are cheaper', 'Plant ALA converts very poorly to EPA/DHA', 'Fish oil causes allergies', 'Algae taste better'], correctAnswer: 1, explanation: 'ALA from plants converts to EPA/DHA at only 5–10%, making algae-based supplements the reliable alternative.' },
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'Who can provide medical nutrition therapy in the UK?', options: ['Any personal trainer', 'Registered Dietitians (HCPC)', 'Nutrition coaches', 'Health food shop staff'], correctAnswer: 1, explanation: 'Only HCPC-regulated Registered Dietitians can provide medical nutrition therapy.' },
    { type: 'multiple_choice', question: 'What dietary pattern has the strongest evidence for cardiovascular health?', options: ['Carnivore diet', 'Mediterranean diet', 'Juice cleanse', 'Raw food diet'], correctAnswer: 1, explanation: 'Mediterranean and DASH dietary patterns have the strongest evidence for cardiovascular health.' },
    { type: 'multiple_choice', question: 'What percentage of body weight loss significantly reduces type 2 diabetes risk?', options: ['1%', '5–7%', '15%', '25%'], correctAnswer: 1, explanation: 'The UK Diabetes Prevention Programme shows 5–7% weight loss significantly reduces progression risk.' },
    { type: 'multiple_choice', question: 'What should you do if you suspect someone has an eating disorder?', options: ['Diagnose them yourself', 'Ignore it', 'Express concern and encourage them to speak with their GP', 'Put them on a meal plan'], correctAnswer: 2, explanation: 'Compassionate concern and referral to a GP is the appropriate response.' },
    { type: 'multiple_choice', question: 'What is the title of the UK eating disorder charity?', options: ['Mind', 'Beat', 'CALM', 'Samaritans'], correctAnswer: 1, explanation: 'Beat (beateatingdisorders.org.uk) is the UK\'s leading eating disorder charity.' },
    { type: 'multiple_choice', question: 'Is the title "nutritionist" legally protected in the UK?', options: ['Yes, fully protected', 'No, not in the same way as "dietitian"', 'Only in Scotland', 'Only for NHS staff'], correctAnswer: 1, explanation: 'Unlike "dietitian," the title "nutritionist" is not legally protected in the UK.' },
  ]),
];

// Unit 3 chapter quizzes
export const nutritionL3Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'What protein range is recommended for resistance-trained individuals?', options: ['0.5–0.8g/kg', '1.6–2.2g/kg', '3–4g/kg', '5g/kg'], correctAnswer: 1, explanation: '1.6–2.2g protein per kilogram body weight is the evidence-based range.' },
    { type: 'multiple_choice', question: 'How much muscle glycogen does a high-volume session typically deplete?', options: ['5%', '25–40%', '75%', '100%'], correctAnswer: 1, explanation: 'A typical 20–25 working set session depletes approximately 25–40% of muscle glycogen.' },
    { type: 'multiple_choice', question: 'What should a pre-training meal ideally contain?', options: ['Only fats', '25–40g protein and 40–80g carbohydrates', 'Only water', 'Alcohol and protein'], correctAnswer: 1, explanation: 'A balanced pre-training meal with protein and carbohydrates 2–3 hours before provides optimal fuel.' },
    { type: 'multiple_choice', question: 'Why do very low-carb diets reduce training performance?', options: ['They cause dehydration', 'Suboptimal glycogen stores limit high-intensity work', 'They increase fat burning too much', 'They contain too much fibre'], correctAnswer: 1, explanation: 'Low carb intake means starting sessions with less glycogen, impairing performance especially later in the session.' },
    { type: 'multiple_choice', question: 'What minimum fat intake per kg body weight is recommended?', options: ['0.1g/kg', '0.7g/kg', '2g/kg', '5g/kg'], correctAnswer: 1, explanation: 'At least 0.7g fat per kilogram protects hormonal function.' },
    { type: 'multiple_choice', question: 'How does glycogen bind water?', options: ['1g water per 1g glycogen', '3g water per 1g glycogen', '10g water per 1g glycogen', 'It does not bind water'], correctAnswer: 1, explanation: 'Glycogen binds water at approximately 3g water per 1g glycogen, explaining weight changes with carb intake.' },
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'What carbohydrate intake is recommended for carb loading?', options: ['2–3g/kg', '5–6g/kg', '8–12g/kg', '15–20g/kg'], correctAnswer: 2, explanation: '8–12g/kg for 36–48 hours is the modern carbohydrate loading protocol.' },
    { type: 'multiple_choice', question: 'What ratio of glucose to fructose enables up to 90g/hour absorption?', options: ['1:1', '2:1', '3:1', '10:1'], correctAnswer: 1, explanation: 'A 2:1 glucose-to-fructose ratio utilises different absorption pathways for maximum uptake.' },
    { type: 'multiple_choice', question: 'What is hyponatraemia?', options: ['High blood sodium', 'Dangerously low blood sodium', 'Dehydration', 'Muscle cramping'], correctAnswer: 1, explanation: 'Hyponatraemia is dangerously low blood sodium, often from over-drinking plain water.' },
    { type: 'multiple_choice', question: 'For events under 60 minutes, what fuelling is recommended?', options: ['60g carbs per hour', 'Water only (possible carb mouth rinse)', '90g carbs per hour', 'Protein shake'], correctAnswer: 1, explanation: 'Events under 60 minutes need only water; carb mouth rinsing may provide a small benefit.' },
    { type: 'multiple_choice', question: 'Why should fuelling strategy be practised in training?', options: ['To save money', 'The gut can be trained to tolerate carbs; new strategies on race day risk GI distress', 'To impress your coach', 'It does not need practising'], correctAnswer: 1, explanation: 'The gut adapts to higher carb intake over time; trying new strategies on race day risks gastrointestinal problems.' },
    { type: 'multiple_choice', question: 'How much sodium can be lost per hour through sweat?', options: ['10–50mg', '200–2000mg+', '5000mg', '0mg'], correctAnswer: 1, explanation: 'Sodium losses vary widely from 200mg to over 2000mg per hour depending on individual factors.' },
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What caloric deficit is appropriate for most people during fat loss?', options: ['100 calories', '300–500 calories', '1000+ calories', '2000 calories'], correctAnswer: 1, explanation: 'A 300–500 calorie deficit produces sustainable fat loss of 0.25–0.5kg per week.' },
    { type: 'multiple_choice', question: 'Why should protein intake increase during a deficit?', options: ['To gain more muscle', 'To preserve muscle mass, increase satiety, and raise thermic effect', 'Protein has fewer calories', 'It is unnecessary'], correctAnswer: 1, explanation: 'Higher protein (2.0–2.4g/kg) during a deficit preserves muscle, increases fullness, and burns more calories through TEF.' },
    { type: 'multiple_choice', question: 'What is the best predictor of successful fat loss?', options: ['The specific diet chosen', 'Adherence — consistently maintaining the deficit', 'Supplement use', 'Training intensity'], correctAnswer: 1, explanation: 'Adherence consistently outperforms any specific diet methodology for long-term results.' },
    { type: 'multiple_choice', question: 'How long should fat loss phases typically last before a diet break?', options: ['2–3 weeks', '8–16 weeks', '6–12 months', 'Indefinitely'], correctAnswer: 1, explanation: 'After 8–16 weeks, a planned transition to maintenance is important for hormonal and psychological recovery.' },
    { type: 'multiple_choice', question: 'Which sign suggests you should end a fat loss phase?', options: ['Mild hunger before meals', 'Loss of menstrual cycle (amenorrhoea)', 'Slow weight loss', 'Occasional cravings'], correctAnswer: 1, explanation: 'Loss of menstrual cycle is a serious sign of energy deficiency requiring immediate attention.' },
    { type: 'multiple_choice', question: 'What fibre intake supports satiety during fat loss?', options: ['5–10g daily', '25–35g daily', '50–75g daily', '100g daily'], correctAnswer: 1, explanation: 'Adequate fibre intake of 25–35g daily supports fullness and digestive health during a deficit.' },
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'What caloric surplus is appropriate for a lean bulk?', options: ['0 calories', '200–400 calories', '1000 calories', '2000 calories'], correctAnswer: 1, explanation: 'A modest 200–400 calorie surplus optimises muscle growth while minimising fat gain.' },
    { type: 'multiple_choice', question: 'What rate of weight gain is appropriate for intermediate lifters?', options: ['1kg per week', '0.25–0.5% body weight per month', '2% body weight per week', '5kg per month'], correctAnswer: 1, explanation: 'Intermediate lifters should aim for approximately 0.25–0.5% body weight gain per month.' },
    { type: 'multiple_choice', question: 'Do larger surpluses proportionally increase muscle growth?', options: ['Yes, more food equals more muscle', 'No — beyond a moderate surplus, extra calories primarily increase fat', 'Only with steroids', 'Only for beginners'], correctAnswer: 1, explanation: 'Muscle growth rate is biologically limited; excess calories beyond a moderate surplus become fat.' },
    { type: 'multiple_choice', question: 'What should you monitor alongside body weight during a gaining phase?', options: ['Blood pressure', 'Waist measurement', 'Hair growth', 'Skin colour'], correctAnswer: 1, explanation: 'If waist increases significantly faster than weight, the surplus is likely too large.' },
    { type: 'multiple_choice', question: 'How fast can beginners gain muscle?', options: ['Approximately 0.5–1% body weight per month', '5kg per week', '10kg per month', 'They cannot gain muscle'], correctAnswer: 0, explanation: 'Beginners can gain approximately 0.5–1% body weight per month with a higher proportion as muscle.' },
    { type: 'multiple_choice', question: 'What is a "dirty bulk"?', options: ['Eating unclean food', 'Unrestricted eating with a very large surplus, leading to excessive fat gain', 'Eating fast food only', 'Training without showering'], correctAnswer: 1, explanation: 'A dirty bulk involves unrestricted eating, producing excessive fat gain that requires longer cutting phases.' },
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'At what percentage of body weight dehydration does performance decline?', options: ['0.5%', '2%', '5%', '10%'], correctAnswer: 1, explanation: '2% dehydration consistently impairs both physical and cognitive performance.' },
    { type: 'multiple_choice', question: 'What urine colour indicates good hydration?', options: ['Clear', 'Pale straw', 'Dark yellow', 'Orange'], correctAnswer: 1, explanation: 'Pale straw colour indicates good hydration; very clear may indicate over-hydration.' },
    { type: 'multiple_choice', question: 'How much water should you drink 2–3 hours before training?', options: ['50ml', '400–600ml', '2 litres', '5 litres'], correctAnswer: 1, explanation: 'Pre-hydrating with 400–600ml in the 2–3 hours before exercise is recommended.' },
    { type: 'multiple_choice', question: 'Is drinking 8 glasses of water per day scientifically supported?', options: ['Yes, it is essential', 'No — fluid needs vary based on many factors', 'Only for athletes', 'Only in summer'], correctAnswer: 1, explanation: 'The 8-glasses rule has no robust scientific basis; needs vary by size, activity, climate, and diet.' },
    { type: 'multiple_choice', question: 'How much fluid should you drink to replace 1kg of weight lost during exercise?', options: ['500ml', '1 litre', '1.5 litres (150%)', '3 litres'], correctAnswer: 2, explanation: 'Replace approximately 150% of weight lost — 1.5 litres for every 1kg.' },
    { type: 'multiple_choice', question: 'What hormone controls kidney water retention?', options: ['Insulin', 'Cortisol', 'Anti-diuretic hormone (ADH)', 'Testosterone'], correctAnswer: 2, explanation: 'ADH controls how much water the kidneys retain to maintain fluid balance.' },
  ]),
  cq(3, 6, [
    { type: 'multiple_choice', question: 'Daily weight can fluctuate by how much?', options: ['0.1kg', '1–3kg', '5–10kg', '20kg'], correctAnswer: 1, explanation: 'Daily fluctuations of 1–3kg are normal from water, glycogen, and gut contents.' },
    { type: 'multiple_choice', question: 'Which body composition method is considered the practical gold standard?', options: ['BMI', 'BIA scales', 'DEXA scan', 'Tape measure'], correctAnswer: 2, explanation: 'DEXA scans differentiate bone, lean mass, and fat mass with approximately 1–2% accuracy.' },
    { type: 'multiple_choice', question: 'At what waist circumference are men at increased metabolic health risk?', options: ['80cm', '94cm', '110cm', '120cm'], correctAnswer: 1, explanation: 'Men above 94cm waist circumference are at increased metabolic health risk.' },
    { type: 'multiple_choice', question: 'What is the most practical tool for tracking visual body composition changes?', options: ['BMI calculator', 'Monthly progress photos under consistent conditions', 'Daily scale weight', 'Guessing'], correctAnswer: 1, explanation: 'Monthly progress photos with consistent lighting, time, and clothing reveal changes numbers often miss.' },
    { type: 'multiple_choice', question: 'What does it mean if weight is stable but waist is decreasing?', options: ['No progress is being made', 'You are likely recomposing — gaining muscle while losing fat', 'You need to eat less', 'The tape measure is wrong'], correctAnswer: 1, explanation: 'Stable weight with decreasing waist indicates body recomposition — simultaneous muscle gain and fat loss.' },
    { type: 'multiple_choice', question: 'How often should progress photos be taken?', options: ['Daily', 'Monthly', 'Yearly', 'Never'], correctAnswer: 1, explanation: 'Monthly progress photos under consistent conditions provide the best visual tracking data.' },
  ]),
];

// Unit 4 chapter quizzes
export const nutritionL3Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What is the difference between hunger and appetite?', options: ['They are identical', 'Hunger is physiological; appetite is influenced by environment and emotion', 'Appetite is stronger than hunger', 'Hunger only happens when fasting'], correctAnswer: 1, explanation: 'Hunger is a physiological signal; appetite can be triggered by non-physiological cues.' },
    { type: 'multiple_choice', question: 'Using a smaller plate reduces intake by approximately how much?', options: ['5%', '20%', '50%', '75%'], correctAnswer: 1, explanation: 'A 25cm plate instead of 30cm reduces intake by approximately 20%.' },
    { type: 'multiple_choice', question: 'Eating while distracted increases intake by how much?', options: ['1–2%', '10–25%', '50%', '100%'], correctAnswer: 1, explanation: 'Distracted eating (TV, phone) increases intake by 10–25%.' },
    { type: 'multiple_choice', question: 'What is wrong with labelling foods as "good" or "bad"?', options: ['Nothing — it helps motivation', 'It creates guilt cycles and restriction-binge patterns', 'It makes food tastier', 'It simplifies nutrition'], correctAnswer: 1, explanation: 'Moral food labelling promotes guilt, shame, and restriction-overconsumption cycles.' },
    { type: 'multiple_choice', question: 'What is more effective than willpower for controlling food intake?', options: ['Stronger motivation', 'Changing the food environment', 'Reading more nutrition books', 'Skipping meals'], correctAnswer: 1, explanation: 'Environmental changes (food visibility, plate size, accessibility) produce larger effects than willpower alone.' },
    { type: 'multiple_choice', question: 'What category should foods be assessed by instead of "good" or "bad"?', options: ['Price', 'Nutrient density', 'Brand name', 'Taste rating'], correctAnswer: 1, explanation: 'Nutrient density — nutritional value per calorie — is a more constructive framework.' },
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What are the five stages in the Transtheoretical Model?', options: ['Denial, Anger, Bargaining, Depression, Acceptance', 'Precontemplation, Contemplation, Preparation, Action, Maintenance', 'Plan, Do, Check, Act, Review', 'Start, Struggle, Fail, Restart, Succeed'], correctAnswer: 1, explanation: 'The five stages are Precontemplation, Contemplation, Preparation, Action, and Maintenance.' },
    { type: 'multiple_choice', question: 'What is habit stacking?', options: ['Doing everything at once', 'Linking a new habit to an existing automatic habit', 'Making a to-do list', 'Replacing all habits simultaneously'], correctAnswer: 1, explanation: 'Habit stacking attaches a new behaviour to an existing established habit as the cue.' },
    { type: 'multiple_choice', question: 'What is an implementation intention?', options: ['A vague goal', 'A specific "if-then" plan for a behaviour', 'A wish', 'A New Year\'s resolution'], correctAnswer: 1, explanation: 'Implementation intentions use "if-then" planning to specify when and how a behaviour will occur.' },
    { type: 'multiple_choice', question: 'What is self-efficacy?', options: ['Physical fitness', 'Belief in your ability to succeed at a specific task', 'Intelligence', 'Motivation'], correctAnswer: 1, explanation: 'Self-efficacy is your belief in your own ability to succeed — a strong predictor of sustained change.' },
    { type: 'multiple_choice', question: 'How long does it typically take for a new habit to become automatic?', options: ['1–2 days', '4–8 weeks', '6 months', '1 year'], correctAnswer: 1, explanation: 'Most habits take approximately 4–8 weeks of consistent practice to become automatic.' },
    { type: 'multiple_choice', question: 'Which strategy best supports long-term behaviour change?', options: ['Changing everything at once', 'Mastering one habit at a time before adding another', 'Relying on motivation', 'Setting extreme goals'], correctAnswer: 1, explanation: 'Sequential habit building — mastering one before adding another — is more effective than simultaneous overhaul.' },
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'Where on the spectrum does obsessive macro tracking sit?', options: ['Healthy eating', 'Potentially disordered eating', 'Clinical eating disorder', 'Not on the spectrum'], correctAnswer: 1, explanation: 'Obsessive tracking that causes anxiety or dominates daily life sits in the disordered eating range.' },
    { type: 'multiple_choice', question: 'What is the appropriate response if you suspect someone has an eating disorder?', options: ['Diagnose them', 'Ignore it', 'Express concern without judgement and encourage them to see their GP', 'Put them on a strict meal plan'], correctAnswer: 2, explanation: 'Compassionate concern and referral to a GP is the responsible response.' },
    { type: 'multiple_choice', question: 'What is Beat?', options: ['A fitness app', 'The UK\'s leading eating disorder charity', 'A music streaming service', 'A weight loss programme'], correctAnswer: 1, explanation: 'Beat (beateatingdisorders.org.uk) provides helplines, support, and local services for eating disorders.' },
    { type: 'multiple_choice', question: 'Which is a behavioural warning sign of disordered eating?', options: ['Enjoying a variety of foods', 'Avoiding social eating and excessive food rules', 'Cooking for friends', 'Trying new restaurants'], correctAnswer: 1, explanation: 'Avoiding social eating and rigid food rules are behavioural indicators of disordered eating.' },
    { type: 'multiple_choice', question: 'Can fitness communities normalise disordered eating behaviours?', options: ['No, fitness is always healthy', 'Yes — extreme restriction and compensation are often normalised', 'Only in bodybuilding', 'Only online'], correctAnswer: 1, explanation: 'Fitness and bodybuilding communities have normalised many behaviours that sit on the disordered eating spectrum.' },
    { type: 'multiple_choice', question: 'What distinguishes a food allergy from an intolerance?', options: ['Allergies are less serious', 'Allergies involve an immune (IgE) response and can be life-threatening; intolerances do not', 'They are the same thing', 'Intolerances are more dangerous'], correctAnswer: 1, explanation: 'Food allergies involve an immune response and can cause anaphylaxis; intolerances are uncomfortable but not life-threatening.' },
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is motivational interviewing?', options: ['Telling people what to do', 'A counselling approach that helps people explore their own reasons for change', 'A job interview technique', 'A type of therapy for depression'], correctAnswer: 1, explanation: 'MI guides people toward their own motivations for change rather than directing them.' },
    { type: 'multiple_choice', question: 'What does "rolling with resistance" mean?', options: ['Arguing harder', 'Acknowledging the person\'s perspective rather than fighting it', 'Giving up', 'Changing the subject'], correctAnswer: 1, explanation: 'Rolling with resistance means acknowledging rather than confronting opposition — resistance often decreases.' },
    { type: 'multiple_choice', question: 'What is "change talk"?', options: ['Discussing the weather', 'Language that favours movement toward change', 'Complaining about current habits', 'Talking about other people\'s changes'], correctAnswer: 1, explanation: 'Change talk includes statements of desire, ability, reason, or need for change.' },
    { type: 'multiple_choice', question: 'Which MI principle involves highlighting past successes?', options: ['Express Empathy', 'Develop Discrepancy', 'Roll with Resistance', 'Support Self-Efficacy'], correctAnswer: 3, explanation: 'Supporting Self-Efficacy includes reinforcing belief in ability through highlighting past successes.' },
    { type: 'multiple_choice', question: 'Why is asking questions more effective than giving advice?', options: ['It saves time', 'People are more likely to commit to change they articulate themselves', 'Questions are easier', 'Advice is always wrong'], correctAnswer: 1, explanation: 'Self-articulated motivations produce stronger commitment than externally imposed advice.' },
    { type: 'multiple_choice', question: 'Can MI principles be applied to your own internal dialogue?', options: ['No, only for professionals', 'Yes — noticing sustain talk and reframing toward change talk is effective', 'Only with a therapist', 'Only in writing'], correctAnswer: 1, explanation: 'MI principles work on your own internal dialogue — notice sustain talk and consciously reframe toward change talk.' },
  ]),
  cq(4, 5, [
    { type: 'multiple_choice', question: 'What is batch cooking?', options: ['Cooking one meal at a time', 'Preparing large quantities of base ingredients to mix and match throughout the week', 'Ordering takeaway in bulk', 'Cooking only at weekends'], correctAnswer: 1, explanation: 'Batch cooking prepares versatile base ingredients that are combined in different ways during the week.' },
    { type: 'multiple_choice', question: 'How much time does a typical batch cooking session take?', options: ['30 minutes', '2–3 hours for 15–20 meals', '8 hours', '15 minutes'], correctAnswer: 1, explanation: 'Approximately 2–3 hours on one day can produce components for 15–20 meals.' },
    { type: 'multiple_choice', question: 'Are frozen vegetables nutritionally inferior to fresh?', options: ['Yes, always', 'No — they are nutritionally equivalent, often frozen at peak ripeness', 'Only if organic', 'Frozen is always better'], correctAnswer: 1, explanation: 'Frozen vegetables are picked and frozen at peak ripeness, making them nutritionally equivalent to fresh.' },
    { type: 'multiple_choice', question: 'What is the cheapest protein source from this list?', options: ['Organic chicken breast', 'Eggs', 'Wagyu steak', 'Fresh salmon'], correctAnswer: 1, explanation: 'Eggs are consistently one of the cheapest high-quality protein sources available.' },
    { type: 'multiple_choice', question: 'What is a key benefit of meal planning for food waste?', options: ['It increases waste', 'It reduces waste by ensuring you buy only what you need', 'It has no effect', 'It only works for large families'], correctAnswer: 1, explanation: 'Planning purchases around actual needs significantly reduces food waste — a major hidden cost.' },
    { type: 'multiple_choice', question: 'What is the most expensive approach to eating?', options: ['Buying raw ingredients in bulk', 'Buying individual meals, takeaways, and prepared foods', 'Growing your own vegetables', 'Shopping at markets'], correctAnswer: 1, explanation: 'Convenience foods, takeaways, and prepared meals are significantly more expensive per serving.' },
  ]),
  cq(4, 6, [
    { type: 'multiple_choice', question: 'Is the title "nutritionist" legally protected in the UK?', options: ['Yes', 'No', 'Only in Wales', 'Only after 2020'], correctAnswer: 1, explanation: 'Unlike "dietitian," the title "nutritionist" is not legally protected in the UK.' },
    { type: 'multiple_choice', question: 'When should you refer someone to a registered dietitian?', options: ['When they ask about vegetables', 'When they have a diagnosed medical condition affecting nutrition', 'Never', 'Only if they ask'], correctAnswer: 1, explanation: 'Medical conditions like diabetes, kidney disease, or eating disorders require specialist referral.' },
    { type: 'multiple_choice', question: 'What regulates Registered Dietitians in the UK?', options: ['NHS', 'HCPC', 'GMC', 'BMA'], correctAnswer: 1, explanation: 'The Health and Care Professions Council (HCPC) regulates the title "dietitian" in the UK.' },
    { type: 'multiple_choice', question: 'What is the most responsible action when you do not know the answer to a nutrition question?', options: ['Make up an answer', 'Say "I do not know" and suggest appropriate resources', 'Avoid the person', 'Google it quickly and pretend you knew'], correctAnswer: 1, explanation: 'Honest acknowledgement of limitations and appropriate referral is the responsible approach.' },
    { type: 'multiple_choice', question: 'What is a key principle of responsible nutrition communication?', options: ['Using absolute statements like "never eat X"', 'Distinguishing between evidence-based guidelines and personal opinion', 'Promoting supplements for commission', 'Sharing dramatic transformation photos'], correctAnswer: 1, explanation: 'Responsible communication distinguishes evidence from opinion and acknowledges uncertainty.' },
    { type: 'multiple_choice', question: 'Why should you maintain a referral network?', options: ['To avoid doing any work', 'To quickly direct people to appropriate help when situations exceed your scope', 'For marketing purposes', 'It is a legal requirement'], correctAnswer: 1, explanation: 'Having referral contacts ready means you can act quickly when someone needs specialist support.' },
  ]),
];
