import type { UnitAssessment, ChapterQuiz } from '../types';

function cq(unit: number, ch: number, questions: any[]): ChapterQuiz {
  return { unitNumber: unit, chapterNumber: ch, questionBank: questions, pickCount: 5, passMarkPercent: 80 };
}

// ── Unit Assessments ──

export const mindsetL2Unit1Assessment: UnitAssessment = {
  unitNumber: 1, title: 'Unit 1 Assessment — Foundations of Mental Resilience',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is mental resilience?', options: ['Never feeling stressed', 'The ability to adapt to stress, recover from setbacks, and maintain progress', 'Ignoring your emotions', 'Being physically strong'], correctAnswer: 1, explanation: 'Resilience is about adaptation and recovery, not suppression or invincibility.' },
    { type: 'multiple_choice', question: 'What triggers the fight-or-flight response?', options: ['Only physical danger', 'The parasympathetic nervous system', 'The sympathetic nervous system via the amygdala', 'Deep breathing'], correctAnswer: 2, explanation: 'The amygdala detects threats and activates the sympathetic nervous system.' },
    { type: 'multiple_choice', question: 'What is the primary hormone associated with chronic stress?', options: ['Testosterone', 'Dopamine', 'Cortisol', 'Serotonin'], correctAnswer: 2, explanation: 'Cortisol is the primary chronic stress hormone with wide-ranging negative effects when chronically elevated.' },
    { type: 'multiple_choice', question: 'Which nerve is the primary pathway of the parasympathetic nervous system?', options: ['Sciatic nerve', 'Vagus nerve', 'Femoral nerve', 'Ulnar nerve'], correctAnswer: 1, explanation: 'The vagus nerve connects to heart, lungs, and digestive system, driving rest-and-digest responses.' },
    { type: 'multiple_choice', question: 'How does an extended exhale affect the nervous system?', options: ['Activates sympathetic tone', 'Has no effect', 'Activates parasympathetic tone via vagal stimulation', 'Increases cortisol'], correctAnswer: 2, explanation: 'Extended exhales stimulate the vagus nerve and shift toward parasympathetic dominance.' },
    { type: 'multiple_choice', question: 'In Carol Dweck\'s theory, what characterises a growth mindset?', options: ['Believing abilities are fixed', 'Avoiding challenges', 'Believing abilities are developed through effort and learning', 'Ignoring feedback'], correctAnswer: 2, explanation: 'Growth mindset sees abilities as developable through effort, learning, and persistence.' },
    { type: 'multiple_choice', question: 'Which type of goal is entirely within your control?', options: ['Outcome goal', 'Performance goal', 'Process goal', 'Result goal'], correctAnswer: 2, explanation: 'Process goals (daily actions) are fully controllable, unlike outcomes which depend on external factors.' },
    { type: 'multiple_choice', question: 'Which sleep stage is critical for physical recovery and growth hormone release?', options: ['REM sleep', 'Light sleep (N1)', 'Deep sleep (N3)', 'All stages equally'], correctAnswer: 2, explanation: 'Deep sleep (N3) is when growth hormone is released and physical tissue repair occurs.' },
    { type: 'multiple_choice', question: 'How long is a complete sleep cycle?', options: ['30 minutes', '60 minutes', 'Approximately 90 minutes', '3 hours'], correctAnswer: 2, explanation: 'A complete cycle through all sleep stages takes approximately 90 minutes.' },
    { type: 'scenario', scenario: 'Someone says "I am just not a morning person" when discussing building a morning routine.', question: 'What type of mindset does this reflect?', options: ['Growth mindset', 'Fixed mindset', 'Process-oriented thinking', 'Realistic assessment'], correctAnswer: 1, explanation: 'Framing a changeable behaviour as a fixed trait ("I am not...") reflects a fixed mindset.' },
    { type: 'multiple_choice', question: 'What should caffeine intake be limited to for good sleep?', options: ['After 8pm', 'After 6pm', 'After 2pm', 'No limit needed'], correctAnswer: 2, explanation: 'Caffeine has a half-life of 5–6 hours, so avoiding it after 2pm protects sleep quality.' },
    { type: 'multiple_choice', question: 'What bedroom temperature is optimal for sleep?', options: ['20–22°C', '16–18°C', '24–26°C', '12–14°C'], correctAnswer: 1, explanation: 'A cool bedroom (16–18°C) supports the core temperature drop needed for sleep onset.' },
  ],
};

export const mindsetL2Unit2Assessment: UnitAssessment = {
  unitNumber: 2, title: 'Unit 2 Assessment — Breathing Science & Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What primarily drives the urge to breathe?', options: ['Low oxygen levels', 'Rising carbon dioxide levels', 'Heart rate', 'Blood pressure'], correctAnswer: 1, explanation: 'CO2 levels, not oxygen, primarily trigger the urge to breathe via brainstem chemoreceptors.' },
    { type: 'multiple_choice', question: 'What is the BOLT score?', options: ['A fitness test', 'Body Oxygen Level Test — comfortable pause after exhale', 'A breathing speed test', 'A lung capacity measure'], correctAnswer: 1, explanation: 'BOLT measures CO2 tolerance by timing a comfortable breath hold after normal exhalation.' },
    { type: 'multiple_choice', question: 'What is the box breathing protocol?', options: ['Breathe as fast as possible', '4 seconds inhale, 4 hold, 4 exhale, 4 hold', 'Continuous deep breathing', 'Hold your breath for 4 minutes'], correctAnswer: 1, explanation: 'Box breathing uses equal 4-second phases: inhale, hold, exhale, hold.' },
    { type: 'multiple_choice', question: 'What makes the 4-7-8 technique effective for calming?', options: ['The long inhale', 'The extended exhale activates vagal tone', 'The breath hold increases oxygen', 'It requires no practice'], correctAnswer: 1, explanation: 'The extended exhale phase maximises parasympathetic activation through vagal stimulation.' },
    { type: 'multiple_choice', question: 'How does the Wim Hof method increase energy?', options: ['By increasing CO2', 'Through rapid breathing that triggers controlled adrenaline release', 'By slowing heart rate', 'Through extended exhales'], correctAnswer: 1, explanation: 'Rapid breathing lowers CO2, alters blood pH, and triggers a controlled adrenaline response.' },
    { type: 'multiple_choice', question: 'Where should you NEVER practise hyperventilation-based breathwork?', options: ['In bed', 'In or near water', 'Sitting on a chair', 'In a quiet room'], correctAnswer: 1, explanation: 'Loss of consciousness in water can be fatal — never practise near water.' },
    { type: 'multiple_choice', question: 'What does chronic mouth breathing promote?', options: ['Better sleep', 'Sympathetic nervous system activation and stress', 'Parasympathetic balance', 'Higher CO2 tolerance'], correctAnswer: 1, explanation: 'Mouth breathing bypasses nasal benefits and promotes sympathetic activation.' },
    { type: 'multiple_choice', question: 'Cold water immersion increases noradrenaline by approximately how much?', options: ['10–20%', '50–100%', '200–300%', '1000%'], correctAnswer: 2, explanation: 'Cold water immersion can increase noradrenaline by 200–300%, improving alertness and mood.' },
    { type: 'multiple_choice', question: 'What is the recommended starting protocol for cold exposure?', options: ['10 minutes in an ice bath', '30 seconds of cold water at the end of your shower', '5 minutes of cold water immersion', 'Swimming in a cold lake'], correctAnswer: 1, explanation: 'Start with 30 seconds of cold at the end of a normal shower and gradually increase.' },
    { type: 'multiple_choice', question: 'What psychological benefit does cold exposure provide?', options: ['It eliminates stress', 'It proves you can choose discomfort and handle it', 'It makes you immune to cold', 'It replaces exercise'], correctAnswer: 1, explanation: 'Choosing voluntary discomfort builds the psychological muscle of doing hard things — transferable to all areas.' },
    { type: 'multiple_choice', question: 'What type of journaling is most effective for processing difficult experiences?', options: ['Gratitude only', 'Free writing about thoughts and feelings', 'Writing to-do lists', 'Copying motivational quotes'], correctAnswer: 1, explanation: 'Expressive free writing forces cognitive processing of experiences, reducing their emotional charge.' },
    { type: 'multiple_choice', question: 'How many breaths per minute may indicate over-breathing?', options: ['6–8', '8–10', 'Above 12', 'Above 20'], correctAnswer: 2, explanation: 'A resting breathing rate above 12 breaths per minute may indicate chronic over-breathing.' },
  ],
};

export const mindsetL2Unit3Assessment: UnitAssessment = {
  unitNumber: 3, title: 'Unit 3 Assessment — Focus, Discipline & Habit Formation',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'How long does it take to refocus after a distraction?', options: ['30 seconds', '2 minutes', 'Average of 23 minutes', '1 hour'], correctAnswer: 2, explanation: 'Research shows it takes an average of 23 minutes to fully refocus after an interruption.' },
    { type: 'multiple_choice', question: 'What is true multitasking?', options: ['Switching quickly between tasks', 'Performing two cognitive tasks simultaneously — which is neurologically impossible', 'Working on a laptop while watching TV', 'Listening to music while studying'], correctAnswer: 1, explanation: 'True cognitive multitasking is impossible — what people call multitasking is rapid task switching.' },
    { type: 'multiple_choice', question: 'Why is motivation unreliable for sustained behaviour?', options: ['It is always low', 'It is an emotion that fluctuates like all emotions', 'It only works for beginners', 'It requires too much energy'], correctAnswer: 1, explanation: 'Motivation fluctuates naturally — systems and discipline produce more consistent results.' },
    { type: 'multiple_choice', question: 'What is an identity-based habit?', options: ['A habit based on what you want to achieve', 'A habit based on who you want to become', 'A habit copied from someone else', 'A habit based on rewards'], correctAnswer: 1, explanation: 'Identity-based habits focus on becoming the type of person who naturally does the desired behaviour.' },
    { type: 'multiple_choice', question: 'What are the three components of the habit loop?', options: ['Plan, Execute, Review', 'Cue, Routine, Reward', 'Start, Continue, Stop', 'Trigger, Action, Outcome'], correctAnswer: 1, explanation: 'The habit loop is: Cue (trigger) → Routine (behaviour) → Reward (reinforcement).' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Ignoring negative thoughts', 'Changing your interpretation of a situation to change how you feel about it', 'Arguing with your emotions', 'Suppressing difficult feelings'], correctAnswer: 1, explanation: 'Cognitive reappraisal changes interpretation, not facts, to produce a more constructive emotional response.' },
    { type: 'multiple_choice', question: 'What does the "S" in the STOP method stand for?', options: ['Speak', 'Stop', 'Start', 'Shift'], correctAnswer: 1, explanation: 'S = Stop. Literally pause before speaking or acting.' },
    { type: 'multiple_choice', question: 'Why is process visualisation more effective than outcome visualisation?', options: ['It is faster', 'It prepares you for the actual steps and challenges involved', 'It is easier', 'Outcome visualisation does not work at all'], correctAnswer: 1, explanation: 'Process visualisation improves performance by mentally rehearsing the steps and responses needed.' },
    { type: 'multiple_choice', question: 'How long does it typically take for a new habit to become automatic?', options: ['1 week', '4–8 weeks', '6 months', '1 year'], correctAnswer: 1, explanation: 'Most habits require approximately 4–8 weeks of consistent repetition to become automatic.' },
    { type: 'multiple_choice', question: 'What is the "never miss twice" rule?', options: ['Always train twice a day', 'Missing one day is acceptable but two consecutive days starts a new pattern of not doing it', 'Train even when injured', 'Always do double if you miss'], correctAnswer: 1, explanation: 'One missed day does not break a habit — but two consecutive days establishes a pattern of absence.' },
    { type: 'multiple_choice', question: 'What is affect labelling?', options: ['Putting sticky notes on emotions', 'Naming your emotions out loud to reduce their intensity', 'Categorising people by personality', 'Writing labels on a journal'], correctAnswer: 1, explanation: 'Naming emotions activates the prefrontal cortex and measurably reduces emotional intensity.' },
    { type: 'multiple_choice', question: 'Which brain region handles automatic habits?', options: ['Prefrontal cortex', 'Basal ganglia', 'Amygdala', 'Hippocampus'], correctAnswer: 1, explanation: 'The basal ganglia encodes automatic habits, freeing the prefrontal cortex for other tasks.' },
  ],
};

export const mindsetL2Unit4Assessment: UnitAssessment = {
  unitNumber: 4, title: 'Unit 4 Assessment — Practical Application & Daily Practice',
  passMarkPercent: 80, pickCount: 10,
  questions: [
    { type: 'multiple_choice', question: 'What is the most important factor in a morning routine?', options: ['Duration', 'Complexity', 'Consistency', 'Waking early'], correctAnswer: 2, explanation: 'A consistent short routine is far more effective than an elaborate one that is not sustained.' },
    { type: 'multiple_choice', question: 'Why should you avoid checking your phone first thing in the morning?', options: ['Phones are bad', 'It puts you in reactive mode, responding to others\' priorities', 'It uses too much battery', 'It is a waste of time'], correctAnswer: 1, explanation: 'Checking your phone floods your brain with external demands, preventing proactive intention-setting.' },
    { type: 'multiple_choice', question: 'What is stress inoculation training?', options: ['Avoiding all stress', 'Controlled exposure to manageable stress to build resilience', 'Extreme suffering', 'Taking stress medication'], correctAnswer: 1, explanation: 'SIT builds resilience through progressive, controlled exposure — like a vaccine for your nervous system.' },
    { type: 'multiple_choice', question: 'What are the three phases of stress inoculation?', options: ['Fight, Flight, Freeze', 'Education, Skill Acquisition, Application', 'Start, Stop, Restart', 'Breathe, Think, Act'], correctAnswer: 1, explanation: 'SIT progresses through understanding stress, learning coping tools, then applying them under controlled challenge.' },
    { type: 'multiple_choice', question: 'What is mindfulness?', options: ['Clearing your mind completely', 'Paying attention to the present moment without judgement', 'Meditating for an hour daily', 'Ignoring your thoughts'], correctAnswer: 1, explanation: 'Mindfulness is present-moment awareness without judgement — not thought suppression.' },
    { type: 'multiple_choice', question: 'What is the "mental bicep curl" in mindfulness?', options: ['Visualising lifting weights', 'Noticing when your mind has wandered and returning to the present', 'Thinking harder', 'Concentrating without blinking'], correctAnswer: 1, explanation: 'Each time you notice wandering and return attention to the present, you strengthen the attentional muscle.' },
    { type: 'multiple_choice', question: 'What is the minimum effective dose for a daily mindfulness practice?', options: ['30 minutes', '3 minutes', '1 hour', '10 seconds'], correctAnswer: 1, explanation: 'Even 3 minutes of daily practice produces measurable benefits when done consistently.' },
    { type: 'scenario', scenario: 'Someone designs a 90-minute morning routine including cold exposure, breathwork, journaling, meditation, and exercise. They abandon it after 5 days.', question: 'What was the primary mistake?', options: ['Not including enough activities', 'Starting too ambitiously — should have begun with 10–15 minutes', 'Waking too late', 'Not having the right equipment'], correctAnswer: 1, explanation: 'Overly ambitious protocols collapse quickly. Start small (10–15 min) and build as the habit solidifies.' },
    { type: 'multiple_choice', question: 'How often should you review and adjust your resilience protocol?', options: ['Daily', 'Weekly', 'Monthly', 'Never'], correctAnswer: 2, explanation: 'Monthly reviews allow enough time to assess what is working while keeping the protocol evolving.' },
    { type: 'multiple_choice', question: 'What is the ultimate goal of a resilience protocol?', options: ['To follow it perfectly forever', 'For the practices to become integrated into your identity and feel natural', 'To become invincible', 'To eliminate all stress'], correctAnswer: 1, explanation: 'The goal is integration — practices become as natural as brushing your teeth, not a forced protocol.' },
    { type: 'multiple_choice', question: 'Where does most mental suffering come from?', options: ['The present moment', 'Ruminating about the past or worrying about the future', 'Physical pain', 'Other people'], correctAnswer: 1, explanation: 'Most suffering comes from past rumination (regret) or future worry (anxiety), not the present moment.' },
    { type: 'multiple_choice', question: 'What is the key principle when progressing a resilience practice?', options: ['Progress as fast as possible', 'Only progress when the current level feels manageable and consistent', 'Skip levels that feel easy', 'Change everything at once'], correctAnswer: 1, explanation: 'Progress only when the current level is consistent — rushing leads to burnout and abandonment.' },
  ],
};

export const mindsetL2FinalAssessment: UnitAssessment = {
  unitNumber: 0, title: 'Level 2 Mindset Final Assessment',
  passMarkPercent: 80, pickCount: 40,
  questions: [
    ...mindsetL2Unit1Assessment.questions,
    ...mindsetL2Unit2Assessment.questions,
    ...mindsetL2Unit3Assessment.questions,
    ...mindsetL2Unit4Assessment.questions,
  ],
};

// ── Chapter Quizzes ──

export const mindsetL2Unit1ChapterQuizzes: ChapterQuiz[] = [
  cq(1, 1, [
    { type: 'multiple_choice', question: 'Is resilience an innate trait or a trainable skill?', options: ['Innate — you either have it or you don\'t', 'Trainable — it develops through practice', 'Only for athletes', 'Determined by genetics alone'], correctAnswer: 1, explanation: 'Research consistently shows resilience is a set of trainable skills, not a fixed trait.' },
    { type: 'multiple_choice', question: 'What are the three components of resilience?', options: ['Speed, Strength, Power', 'Adaptability, Emotional Regulation, Recovery', 'Intelligence, Creativity, Memory', 'Courage, Endurance, Discipline'], correctAnswer: 1, explanation: 'Resilience comprises adaptability, emotional regulation, and recovery capacity.' },
    { type: 'multiple_choice', question: 'Does resilience mean never feeling stressed?', options: ['Yes', 'No — resilient people still feel stress but process it effectively', 'Only under extreme conditions', 'It depends on personality'], correctAnswer: 1, explanation: 'Resilient people experience the full range of emotions but have better systems for processing them.' },
    { type: 'multiple_choice', question: 'What does growth orientation mean in the context of resilience?', options: ['Getting taller', 'Viewing challenges as opportunities for development', 'Always being positive', 'Ignoring problems'], correctAnswer: 1, explanation: 'Growth orientation means seeing challenges as development opportunities rather than threats.' },
    { type: 'multiple_choice', question: 'What is the misconception about resilience that causes harm?', options: ['That it can be learned', 'That it means never breaking — which discourages seeking help', 'That it requires practice', 'That it involves emotions'], correctAnswer: 1, explanation: 'The "never break" myth frames normal emotional responses as weakness and discourages help-seeking.' },
    { type: 'multiple_choice', question: 'How is mental resilience built?', options: ['Through avoiding all stress', 'Through deliberate exposure to manageable challenges and structured recovery', 'Through medication', 'Through reading about it'], correctAnswer: 1, explanation: 'Like physical strength, resilience builds through progressive challenge and recovery.' },
  ]),
  cq(1, 2, [
    { type: 'multiple_choice', question: 'Can your brain distinguish between real and perceived threats?', options: ['Yes, always', 'No — both trigger the same fight-or-flight response', 'Only when you are calm', 'Only in adults'], correctAnswer: 1, explanation: 'The amygdala triggers the same physiological cascade for both real and perceived threats.' },
    { type: 'multiple_choice', question: 'What is the difference between acute and chronic stress?', options: ['Acute is bad, chronic is good', 'Acute is short-term and beneficial; chronic is sustained and harmful', 'They are the same', 'Acute only affects athletes'], correctAnswer: 1, explanation: 'Acute stress drives adaptation; chronic stress damages health and performance.' },
    { type: 'multiple_choice', question: 'What does elevated cortisol promote?', options: ['Muscle growth', 'Fat storage, immune suppression, and sleep disruption', 'Better focus', 'Faster recovery'], correctAnswer: 1, explanation: 'Chronic cortisol elevation promotes visceral fat storage, impairs immunity, and disrupts sleep.' },
    { type: 'multiple_choice', question: 'What hormone provides immediate energy during acute stress?', options: ['Cortisol', 'Insulin', 'Adrenaline', 'Melatonin'], correctAnswer: 2, explanation: 'Adrenaline provides the immediate energy and alertness burst during acute stress.' },
    { type: 'multiple_choice', question: 'What is the key message about stress management?', options: ['Eliminate all stress', 'Control your relationship with stress — do not eliminate it', 'Ignore stress', 'Only manage work stress'], correctAnswer: 1, explanation: 'The goal is managing your response to stress, not eliminating stress entirely.' },
    { type: 'multiple_choice', question: 'If you are constantly tired, frequently ill, and sleeping poorly, what is likely too high?', options: ['Your motivation', 'Your total stress load', 'Your protein intake', 'Your happiness'], correctAnswer: 1, explanation: 'These symptoms typically indicate an excessive total stress load across all life domains.' },
  ]),
  cq(1, 3, [
    { type: 'multiple_choice', question: 'What are the two branches of the autonomic nervous system?', options: ['Motor and sensory', 'Sympathetic and parasympathetic', 'Central and peripheral', 'Somatic and reflex'], correctAnswer: 1, explanation: 'The ANS has sympathetic (accelerator) and parasympathetic (brake) branches.' },
    { type: 'multiple_choice', question: 'What is vagal tone?', options: ['A sound the vagus nerve makes', 'The strength and efficiency of the vagus nerve', 'A breathing technique', 'A type of meditation'], correctAnswer: 1, explanation: 'Higher vagal tone is associated with better stress recovery, emotional regulation, and resilience.' },
    { type: 'multiple_choice', question: 'What happens to heart rate during exhalation?', options: ['It increases', 'It decreases', 'It stays the same', 'It stops'], correctAnswer: 1, explanation: 'Heart rate naturally decreases during exhale — a phenomenon called respiratory sinus arrhythmia.' },
    { type: 'multiple_choice', question: 'Why is breathing unique among autonomic functions?', options: ['It uses the most energy', 'It can be controlled both voluntarily and involuntarily', 'It only works when conscious', 'It cannot be changed'], correctAnswer: 1, explanation: 'Breathing is the only autonomic function you can also control voluntarily — bridging conscious and unconscious systems.' },
    { type: 'multiple_choice', question: 'What type of breathing activates the sympathetic system?', options: ['Slow nasal breathing', 'Fast shallow chest breathing', 'Extended exhale breathing', 'Diaphragmatic breathing'], correctAnswer: 1, explanation: 'Fast, shallow chest breathing signals stress and activates sympathetic tone.' },
    { type: 'multiple_choice', question: 'What does nasal breathing produce that mouth breathing does not?', options: ['More CO2', 'Nitric oxide', 'More oxygen', 'Adrenaline'], correctAnswer: 1, explanation: 'Nasal breathing activates nitric oxide production, which aids blood flow and oxygen delivery.' },
  ]),
  cq(1, 4, [
    { type: 'multiple_choice', question: 'What does a fixed mindset believe about abilities?', options: ['They are developed through effort', 'They are innate and unchangeable', 'They improve with age', 'They do not exist'], correctAnswer: 1, explanation: 'Fixed mindset assumes abilities are innate — you either have them or you do not.' },
    { type: 'multiple_choice', question: 'What is the most powerful single word for shifting to a growth mindset?', options: ['No', 'Always', 'Yet', 'Never'], correctAnswer: 2, explanation: '"Yet" transforms dead ends into directions: "I can\'t do this... yet."' },
    { type: 'multiple_choice', question: 'Can you hold different mindsets in different areas of life?', options: ['No — you are either fixed or growth', 'Yes — most people have different mindsets in different domains', 'Only if you are a beginner', 'Only children can'], correctAnswer: 1, explanation: 'Most people hold growth mindsets in some areas and fixed mindsets in others.' },
    { type: 'multiple_choice', question: 'How does a growth mindset respond to failure?', options: ['Gives up', 'Blames others', 'Asks "what can I learn?" and adjusts approach', 'Pretends it didn\'t happen'], correctAnswer: 2, explanation: 'Growth mindset attributes failure to changeable behaviours and strategies, not fixed traits.' },
    { type: 'multiple_choice', question: 'Does growth mindset mean you can achieve anything?', options: ['Yes, with enough effort', 'No — genetics and circumstances matter, but mindset influences what you do within your constraints', 'Only in sport', 'Only with a coach'], correctAnswer: 1, explanation: 'Growth mindset means optimising within constraints, not ignoring reality.' },
  ]),
  cq(1, 5, [
    { type: 'multiple_choice', question: 'Which goal type is entirely within your control?', options: ['Outcome goal', 'Performance goal', 'Process goal', 'Dream goal'], correctAnswer: 2, explanation: 'Process goals (daily actions) are fully controllable regardless of external factors.' },
    { type: 'multiple_choice', question: 'Why do outcome goals become discouraging?', options: ['They are too easy', 'Progress is often slow or invisible, eroding motivation', 'They cost too much', 'They are unrealistic by definition'], correctAnswer: 1, explanation: 'When results are slow, outcome-dependent motivation collapses despite perfect process.' },
    { type: 'multiple_choice', question: 'What makes process goals sustain motivation?', options: ['They are impressive to others', 'They provide daily wins that accumulate into habit formation', 'They are easier to set', 'They require no effort'], correctAnswer: 1, explanation: 'Daily small wins from process goals build habits — which are more powerful than motivation.' },
    { type: 'multiple_choice', question: 'How often should you review performance goals?', options: ['Daily', 'Weekly', 'Monthly', 'Yearly'], correctAnswer: 2, explanation: 'Monthly reviews give enough time to see trends while allowing timely adjustments.' },
    { type: 'multiple_choice', question: 'How long should you try a new process before concluding it is not working?', options: ['1 day', '2–4 weeks', '6 months', '1 year'], correctAnswer: 1, explanation: 'Give each process adjustment at least 2–4 weeks before evaluating its effectiveness.' },
  ]),
  cq(1, 6, [
    { type: 'multiple_choice', question: 'What is the single most powerful recovery tool?', options: ['Supplements', 'Ice baths', 'Sleep', 'Massage'], correctAnswer: 2, explanation: 'Sleep is the most powerful recovery tool — no supplement or technique can compensate for poor sleep.' },
    { type: 'multiple_choice', question: 'What predominates in the first half of the night?', options: ['REM sleep', 'Deep sleep (N3)', 'Light sleep only', 'No sleep stages dominate'], correctAnswer: 1, explanation: 'Deep sleep predominates in the first half; REM predominates in the second half.' },
    { type: 'multiple_choice', question: 'What does REM sleep support?', options: ['Physical recovery only', 'Emotional processing, creativity, and memory consolidation', 'Muscle growth', 'Bone density'], correctAnswer: 1, explanation: 'REM sleep is essential for emotional processing, creativity, and memory consolidation.' },
    { type: 'multiple_choice', question: 'Why does alcohol impair sleep despite helping you fall asleep?', options: ['It does not impair sleep', 'It disrupts sleep architecture, reducing REM and deep sleep', 'It makes you sleep too long', 'It only affects light sleep'], correctAnswer: 1, explanation: 'Alcohol significantly reduces the quality of sleep by disrupting both REM and deep sleep phases.' },
    { type: 'multiple_choice', question: 'What triggers melatonin release?', options: ['Bright light', 'Darkness', 'Exercise', 'Caffeine'], correctAnswer: 1, explanation: 'Darkness triggers melatonin release, which is why reducing light before bed aids sleep onset.' },
  ]),
];

export const mindsetL2Unit2ChapterQuizzes: ChapterQuiz[] = [
  cq(2, 1, [
    { type: 'multiple_choice', question: 'What drives the urge to breathe?', options: ['Low oxygen', 'Rising CO2 levels', 'Heart rate', 'Blood pressure'], correctAnswer: 1, explanation: 'CO2 levels primarily control breathing rate via brainstem chemoreceptors.' },
    { type: 'multiple_choice', question: 'What is chronic mouth breathing associated with?', options: ['Better sleep', 'Increased stress activation and poor sleep', 'Higher CO2 tolerance', 'Better oxygen delivery'], correctAnswer: 1, explanation: 'Mouth breathing promotes sympathetic activation and bypasses nasal benefits.' },
    { type: 'multiple_choice', question: 'What is chest breathing?', options: ['Efficient deep breathing', 'Shallow breathing using accessory muscles that promotes stress', 'Diaphragmatic breathing', 'A relaxation technique'], correctAnswer: 1, explanation: 'Chest breathing is shallow, uses neck/upper chest muscles, and activates the sympathetic system.' },
    { type: 'multiple_choice', question: 'What does over-breathing (hyperventilation) cause?', options: ['Better oxygen delivery', 'Reduced CO2, paradoxically reducing oxygen delivery (Bohr effect)', 'Relaxation', 'Improved focus'], correctAnswer: 1, explanation: 'Hyperventilation lowers CO2, which impairs oxygen release to tissues via the Bohr effect.' },
    { type: 'multiple_choice', question: 'A BOLT score under 20 seconds suggests what?', options: ['Excellent breathing health', 'Room for improvement in CO2 tolerance', 'You are an elite athlete', 'No action needed'], correctAnswer: 1, explanation: 'A BOLT score under 20 seconds suggests low CO2 tolerance and likely dysfunctional breathing patterns.' },
  ]),
  cq(2, 2, [
    { type: 'multiple_choice', question: 'What is the diaphragm?', options: ['A chest muscle', 'A dome-shaped muscle at the base of the ribcage', 'A neck muscle', 'A bone'], correctAnswer: 1, explanation: 'The diaphragm is the primary breathing muscle, positioned at the base of the ribcage.' },
    { type: 'multiple_choice', question: 'During diaphragmatic breathing, what should rise?', options: ['Shoulders', 'Chest', 'Belly', 'Head'], correctAnswer: 2, explanation: 'Proper diaphragmatic breathing causes the belly to rise as the diaphragm descends.' },
    { type: 'multiple_choice', question: 'The diaphragm also functions as what type of muscle?', options: ['Arm muscle', 'Core stability muscle', 'Cardiac muscle', 'Facial muscle'], correctAnswer: 1, explanation: 'Diaphragmatic breathing creates intra-abdominal pressure that stabilises the spine.' },
    { type: 'multiple_choice', question: 'How should you progress diaphragmatic breathing practice?', options: ['Only practise lying down', 'Progress from lying to seated to standing to walking', 'Skip to walking immediately', 'Only practise during exercise'], correctAnswer: 1, explanation: 'Progress through positions as the technique becomes natural: lying → seated → standing → walking.' },
    { type: 'multiple_choice', question: 'How often should you practise diaphragmatic breathing initially?', options: ['Once a week', 'Twice daily for 5 minutes', 'Once a month', 'Only when stressed'], correctAnswer: 1, explanation: 'Twice daily for 5 minutes builds the neural pathway for automatic diaphragmatic breathing.' },
  ]),
  cq(2, 3, [
    { type: 'multiple_choice', question: 'Who uses box breathing?', options: ['Only yoga practitioners', 'Military special forces, emergency services, and athletes', 'Only children', 'Nobody — it is unproven'], correctAnswer: 1, explanation: 'Box breathing is used across high-performance fields for maintaining composure under pressure.' },
    { type: 'multiple_choice', question: 'Why is the 4-7-8 technique effective before sleep?', options: ['It makes you tired', 'The extended exhale strongly activates parasympathetic tone', 'It increases heart rate', 'It raises cortisol'], correctAnswer: 1, explanation: 'The extended exhale maximises vagal stimulation, shifting toward parasympathetic dominance.' },
    { type: 'multiple_choice', question: 'How many slow breaths can shift your nervous system state?', options: ['100', '50', 'As few as 6', '1000'], correctAnswer: 2, explanation: 'Even 6 slow, controlled breaths can measurably shift autonomic state during acute stress.' },
    { type: 'multiple_choice', question: 'When is box breathing most useful?', options: ['During sleep', 'Before stressful events and during acute stress', 'Only during meditation', 'Never — it does not work'], correctAnswer: 1, explanation: 'Box breathing is most effective for pre-event composure and acute stress management.' },
    { type: 'multiple_choice', question: 'What creates the calming effect of extended exhale breathing?', options: ['Increased CO2', 'Spending more time in each cycle with decreasing heart rate', 'Faster breathing', 'Increased oxygen'], correctAnswer: 1, explanation: 'Extended exhales maximise the time spent with naturally decreasing heart rate (respiratory sinus arrhythmia).' },
  ]),
  cq(2, 4, [
    { type: 'multiple_choice', question: 'How many deep breaths does the Wim Hof method start with?', options: ['5–10', '30–40', '100', '3'], correctAnswer: 1, explanation: 'The Wim Hof method begins with 30–40 deep, rapid breaths.' },
    { type: 'multiple_choice', question: 'What does the rapid breathing phase of Wim Hof cause?', options: ['Increased CO2', 'Lowered CO2 and controlled adrenaline release', 'Immediate sleep', 'Muscle growth'], correctAnswer: 1, explanation: 'Rapid breathing lowers CO2 (respiratory alkalosis) and triggers a controlled adrenaline response.' },
    { type: 'multiple_choice', question: 'What should you never do while practising hyperventilation breathwork?', options: ['Sit down', 'Close your eyes', 'Be near water or standing where fainting is dangerous', 'Listen to music'], correctAnswer: 2, explanation: 'Low CO2 can cause loss of consciousness — never practise near water or in dangerous positions.' },
    { type: 'multiple_choice', question: 'How many rounds should beginners start with?', options: ['10', '3', '1', '7'], correctAnswer: 1, explanation: 'Start with 3 rounds and build tolerance over weeks.' },
    { type: 'multiple_choice', question: 'Do retention times typically increase across rounds?', options: ['No — they decrease', 'Yes — each round typically produces a longer hold', 'They stay the same', 'Only for experienced practitioners'], correctAnswer: 1, explanation: 'Retention times typically increase with each round as CO2 tolerance temporarily improves.' },
  ]),
  cq(2, 5, [
    { type: 'multiple_choice', question: 'What hormones does cold water immersion release?', options: ['Insulin and glucagon', 'Noradrenaline and dopamine', 'Oestrogen and progesterone', 'Melatonin and serotonin'], correctAnswer: 1, explanation: 'Cold exposure triggers significant releases of noradrenaline (200–300%) and dopamine.' },
    { type: 'multiple_choice', question: 'How long should beginners start with cold exposure?', options: ['10 minutes', '30 seconds', '5 minutes', '1 hour'], correctAnswer: 1, explanation: 'Start with 30 seconds of cold at the end of your normal shower.' },
    { type: 'multiple_choice', question: 'What should you focus on during cold exposure?', options: ['Holding your breath', 'Controlling your breathing — slow nasal breaths', 'Screaming', 'Moving as fast as possible'], correctAnswer: 1, explanation: 'Maintaining slow, controlled breathing through the discomfort is the primary resilience training.' },
    { type: 'multiple_choice', question: 'What temperature range provides most cold exposure benefits?', options: ['20–25°C', '10–15°C', '0–5°C', 'Below 0°C'], correctAnswer: 1, explanation: 'Most benefits occur at 10–15°C in the first 1–3 minutes — extreme cold is unnecessary.' },
    { type: 'multiple_choice', question: 'What is the main psychological benefit of cold exposure?', options: ['It eliminates all discomfort', 'It builds proof that you can choose and handle discomfort', 'It makes you immune to cold', 'It replaces therapy'], correctAnswer: 1, explanation: 'Deliberately choosing discomfort builds transferable psychological resilience.' },
  ]),
  cq(2, 6, [
    { type: 'multiple_choice', question: 'What mechanism makes journaling effective?', options: ['It improves handwriting', 'Cognitive processing — organising thoughts reduces emotional charge', 'It fills time', 'It replaces therapy'], correctAnswer: 1, explanation: 'Writing forces cognitive organisation, creating narrative coherence and reducing emotional intensity.' },
    { type: 'multiple_choice', question: 'What is the most important factor for effective journaling?', options: ['Beautiful writing', 'Consistency', 'Using an expensive notebook', 'Writing for at least 30 minutes'], correctAnswer: 1, explanation: 'A messy paragraph every day is infinitely more valuable than a perfect entry once a month.' },
    { type: 'multiple_choice', question: 'What is the three-question journaling framework?', options: ['Who, What, Where', 'Grateful for, Biggest challenge, One action', 'Past, Present, Future', 'Start, Stop, Continue'], correctAnswer: 1, explanation: 'What am I grateful for? What is my biggest challenge? What is one action I can take?' },
    { type: 'multiple_choice', question: 'How long is sufficient for daily journaling?', options: ['30 minutes minimum', '5 minutes', '2 hours', '10 seconds'], correctAnswer: 1, explanation: '5 minutes is sufficient for effective daily journaling — consistency beats duration.' },
    { type: 'multiple_choice', question: 'What type of journaling shifts attention toward positive life aspects?', options: ['Complaint journaling', 'Gratitude journaling', 'News journaling', 'Fantasy journaling'], correctAnswer: 1, explanation: 'Gratitude journaling (3 things daily) shifts attention toward positive aspects and improves wellbeing.' },
  ]),
];

export const mindsetL2Unit3ChapterQuizzes: ChapterQuiz[] = [
  cq(3, 1, [
    { type: 'multiple_choice', question: 'How long does it take to refocus after a distraction?', options: ['2 minutes', '23 minutes', '1 minute', '5 seconds'], correctAnswer: 1, explanation: 'Research shows an average of 23 minutes to fully refocus after an interruption.' },
    { type: 'multiple_choice', question: 'Is true multitasking possible for cognitive tasks?', options: ['Yes', 'No — it is rapid task switching', 'Only for women', 'Only for experts'], correctAnswer: 1, explanation: 'The brain cannot perform two cognitively demanding tasks simultaneously.' },
    { type: 'multiple_choice', question: 'What is the Pomodoro technique?', options: ['A cooking method', '25–50 minute focused work blocks with 5–10 minute breaks', 'A type of exercise', 'A sleep protocol'], correctAnswer: 1, explanation: 'The Pomodoro technique structures work into focused blocks with strategic breaks.' },
    { type: 'multiple_choice', question: 'What is the two-minute rule?', options: ['Meditate for 2 minutes', 'If a task takes less than 2 minutes, do it now; otherwise schedule it', 'Warm up for 2 minutes', 'Rest for 2 minutes'], correctAnswer: 1, explanation: 'Quick tasks done immediately prevent them from fragmenting future attention.' },
    { type: 'multiple_choice', question: 'What depletes the prefrontal cortex\'s capacity?', options: ['Exercise', 'Every decision, task switch, and distraction', 'Sleep', 'Water intake'], correctAnswer: 1, explanation: 'The prefrontal cortex operates like a battery depleted by decisions and cognitive demands.' },
  ]),
  cq(3, 2, [
    { type: 'multiple_choice', question: 'Why is motivation unreliable?', options: ['It is always low', 'It is an emotion that naturally fluctuates', 'It does not exist', 'It only works for some people'], correctAnswer: 1, explanation: 'Like all emotions, motivation rises and falls — systems and discipline are more consistent.' },
    { type: 'multiple_choice', question: 'What is environment design?', options: ['Interior decorating', 'Arranging your environment so desired actions are the easiest option', 'Building a new house', 'Organising your desk'], correctAnswer: 1, explanation: 'Environment design reduces willpower required by making good choices the default.' },
    { type: 'multiple_choice', question: 'What is an identity-based habit?', options: ['Copying someone else', 'Acting consistently with who you want to become', 'Tracking habits on an app', 'Setting outcome goals'], correctAnswer: 1, explanation: 'Identity-based habits flow from self-concept: "I am someone who..." rather than "I want to..."' },
    { type: 'multiple_choice', question: 'What does "every action is a vote" mean?', options: ['You should vote more', 'Each action reinforces the type of person you are becoming', 'Actions do not matter', 'Only big actions count'], correctAnswer: 1, explanation: 'Small consistent actions accumulate into identity — each one is a vote for who you are becoming.' },
    { type: 'multiple_choice', question: 'What is the most effective way to train consistently?', options: ['Wait for motivation', 'Create systems that work regardless of how you feel', 'Only train when you feel great', 'Train twice as hard on good days'], correctAnswer: 1, explanation: 'Systems that operate independently of motivation produce the most consistent results.' },
  ]),
  cq(3, 3, [
    { type: 'multiple_choice', question: 'What are the three parts of the habit loop?', options: ['Start, Middle, End', 'Cue, Routine, Reward', 'Plan, Act, Review', 'Try, Fail, Retry'], correctAnswer: 1, explanation: 'Every habit follows: Cue (trigger) → Routine (behaviour) → Reward (reinforcement).' },
    { type: 'multiple_choice', question: 'Which brain region takes over once a habit is automatic?', options: ['Prefrontal cortex', 'Basal ganglia', 'Amygdala', 'Cerebellum'], correctAnswer: 1, explanation: 'The basal ganglia encodes automatic habits, freeing the prefrontal cortex.' },
    { type: 'multiple_choice', question: 'What is the best way to break an unwanted habit?', options: ['Use willpower', 'Keep the cue and reward but replace the routine', 'Ignore it', 'Punish yourself'], correctAnswer: 1, explanation: 'Replacing the routine while keeping the same cue and reward is the most effective strategy.' },
    { type: 'multiple_choice', question: 'What does "start absurdly small" mean?', options: ['Set tiny goals like one press-up to reduce resistance', 'Think small forever', 'Never progress', 'Only do easy things'], correctAnswer: 0, explanation: 'Absurdly small starts (one press-up, 2 minutes of journaling) build the neural pathway with minimal resistance.' },
    { type: 'multiple_choice', question: 'What is the "never miss twice" rule?', options: ['Train twice daily', 'Missing one day is fine but two consecutive days starts a pattern of absence', 'Never miss any day', 'Always do double after missing'], correctAnswer: 1, explanation: 'One miss does not break a habit — but two consecutive misses establish a new pattern.' },
  ]),
  cq(3, 4, [
    { type: 'multiple_choice', question: 'Is emotional regulation the same as suppression?', options: ['Yes', 'No — regulation is conscious processing, not hiding emotions', 'Only for negative emotions', 'Depends on the situation'], correctAnswer: 1, explanation: 'Regulation means processing emotions consciously; suppression increases stress and impairs health.' },
    { type: 'multiple_choice', question: 'What is cognitive reappraisal?', options: ['Denying reality', 'Changing your interpretation to change your emotional response', 'Ignoring the situation', 'Arguing with yourself'], correctAnswer: 1, explanation: 'Reappraisal changes interpretation, not facts, producing a more constructive emotional response.' },
    { type: 'multiple_choice', question: 'What does STOP stand for?', options: ['Stop, Think, Observe, Proceed', 'Stop, Take a breath, Observe, Proceed', 'Start, Try, Overcome, Persist', 'Slow, Think, Operate, Plan'], correctAnswer: 1, explanation: 'Stop, Take a breath, Observe your feelings, Proceed with conscious choice.' },
    { type: 'multiple_choice', question: 'What is affect labelling?', options: ['Writing feelings on a label', 'Naming your emotions to reduce their intensity', 'Rating emotions 1-10', 'Describing emotions to others'], correctAnswer: 1, explanation: 'Naming emotions ("I notice I am feeling angry") activates the prefrontal cortex and reduces intensity.' },
    { type: 'multiple_choice', question: 'What creates the "space" between stimulus and response?', options: ['Time', 'Conscious awareness and deliberate pausing', 'Distance', 'Other people'], correctAnswer: 1, explanation: 'Conscious awareness — pausing before reacting — creates the space for intentional response.' },
  ]),
  cq(3, 5, [
    { type: 'multiple_choice', question: 'Why does visualisation work?', options: ['It is magic', 'It activates the same neural pathways as physical performance', 'It replaces practice', 'It only works for athletes'], correctAnswer: 1, explanation: 'Mental rehearsal activates motor cortex regions similar to actual movement.' },
    { type: 'multiple_choice', question: 'Which type of visualisation improves performance more?', options: ['Outcome visualisation', 'Process visualisation', 'Both equally', 'Neither works'], correctAnswer: 1, explanation: 'Process visualisation (imagining steps and challenges) is more effective than imagining the end result.' },
    { type: 'multiple_choice', question: 'Should you include challenges in your visualisation?', options: ['No — only positive outcomes', 'Yes — visualise encountering and overcoming difficulty', 'Challenges are too negative', 'Only if you expect problems'], correctAnswer: 1, explanation: 'Including challenges in visualisation prepares you to respond effectively during actual performance.' },
    { type: 'multiple_choice', question: 'How long should a visualisation session last?', options: ['1 minute', '5–10 minutes', '30 minutes', '1 hour'], correctAnswer: 1, explanation: '5–10 minutes per session, practised 3–5 times before an event, is the evidence-based approach.' },
    { type: 'multiple_choice', question: 'Can outcome visualisation actually reduce effort?', options: ['No', 'Yes — it can create a premature sense of achievement', 'Only for lazy people', 'It always increases effort'], correctAnswer: 1, explanation: 'Research shows imagining the end result can reduce effort by creating premature satisfaction.' },
  ]),
];

export const mindsetL2Unit4ChapterQuizzes: ChapterQuiz[] = [
  cq(4, 1, [
    { type: 'multiple_choice', question: 'What is the most important quality of a morning routine?', options: ['Length', 'Consistency', 'Complexity', 'Start time'], correctAnswer: 1, explanation: 'A consistent short routine beats an ambitious one that is abandoned.' },
    { type: 'multiple_choice', question: 'Why avoid checking your phone first thing?', options: ['Battery conservation', 'It puts you in reactive mode', 'Screens are bad', 'It is impolite'], correctAnswer: 1, explanation: 'Checking your phone immediately floods you with external demands and reactive thinking.' },
    { type: 'multiple_choice', question: 'How much water should you drink upon waking?', options: ['A sip', '500ml', '2 litres', 'None'], correctAnswer: 1, explanation: 'You wake mildly dehydrated — 500ml rehydrates and supports alertness.' },
    { type: 'multiple_choice', question: 'What is the recommended starting duration for a morning routine?', options: ['90 minutes', '10–15 minutes', '5 seconds', '2 hours'], correctAnswer: 1, explanation: 'Start with 10–15 minutes and build as the habit solidifies.' },
    { type: 'multiple_choice', question: 'What is the core principle of morning routine design?', options: ['More is better', 'Sustainability over ambition', 'Complexity builds discipline', 'Copy someone else\'s exactly'], correctAnswer: 1, explanation: 'A sustainable short routine done daily transforms life; an ambitious one abandoned does not.' },
  ]),
  cq(4, 2, [
    { type: 'multiple_choice', question: 'What is stress inoculation training based on?', options: ['Avoiding stress', 'Controlled exposure to manageable stress builds resilience', 'Maximum stress exposure', 'Medication'], correctAnswer: 1, explanation: 'Like a vaccine, SIT uses controlled exposure to build capacity for handling larger stressors.' },
    { type: 'multiple_choice', question: 'What is the key difference between SIT and uncontrolled stress?', options: ['SIT is harder', 'SIT is chosen and progressive with coping tools; uncontrolled stress overwhelms', 'No difference', 'SIT only works for soldiers'], correctAnswer: 1, explanation: 'Controlled, chosen exposure with tools builds capacity; overwhelming stress causes harm.' },
    { type: 'multiple_choice', question: 'What is Phase 2 of SIT?', options: ['Application', 'Education', 'Skill Acquisition — learning coping tools', 'Recovery'], correctAnswer: 2, explanation: 'Phase 2 involves learning the tools (breathing, reappraisal, visualisation) before applying them.' },
    { type: 'multiple_choice', question: 'What does each successful stress exposure provide?', options: ['More stress', 'Evidence that you can handle hard things', 'Physical strength', 'Nothing'], correctAnswer: 1, explanation: 'Successful exposure builds experiential confidence that no theory can replicate.' },
    { type: 'multiple_choice', question: 'What is the enemy of growth in this context?', options: ['Challenge', 'Comfort', 'Other people', 'Knowledge'], correctAnswer: 1, explanation: 'Sustained comfort prevents the adaptive challenges needed for resilience growth.' },
  ]),
  cq(4, 3, [
    { type: 'multiple_choice', question: 'What is mindfulness?', options: ['Clearing your mind', 'Paying attention to the present moment without judgement', 'Meditation only', 'Thinking positive thoughts'], correctAnswer: 1, explanation: 'Mindfulness is present-moment awareness — not thought suppression or forced positivity.' },
    { type: 'multiple_choice', question: 'Where does most mental suffering come from?', options: ['The present', 'Past rumination and future worry', 'Physical pain', 'Other people'], correctAnswer: 1, explanation: 'Most suffering comes from dwelling on the past (regret) or worrying about the future (anxiety).' },
    { type: 'multiple_choice', question: 'What is the minimum effective daily mindfulness practice?', options: ['30 minutes', '3 minutes', '1 hour', '0 minutes — just think about it'], correctAnswer: 1, explanation: 'Even 3 minutes of consistent daily practice produces measurable benefits.' },
    { type: 'multiple_choice', question: 'When your mind wanders during meditation, what should you do?', options: ['Get frustrated', 'Notice it wandered and gently return to the breath', 'Give up', 'Try harder to stop thoughts'], correctAnswer: 1, explanation: 'Noticing and returning is the practice itself — each return strengthens the attention muscle.' },
    { type: 'multiple_choice', question: 'Can mindfulness be practised during daily activities?', options: ['No — only during formal meditation', 'Yes — eating, walking, or commuting mindfully counts', 'Only during yoga', 'Only in silence'], correctAnswer: 1, explanation: 'Informal mindfulness (eating, walking without distraction) is equally valuable practice.' },
  ]),
  cq(4, 4, [
    { type: 'multiple_choice', question: 'What is the minimum effective dose for a daily protocol?', options: ['Whatever you can do consistently', '2 hours', '90 minutes', '30 seconds'], correctAnswer: 0, explanation: 'The minimum effective dose is the shortest practice you can maintain every single day.' },
    { type: 'multiple_choice', question: 'How often should you adjust your resilience protocol?', options: ['Daily', 'Monthly', 'Never', 'Every hour'], correctAnswer: 1, explanation: 'Monthly reviews allow assessment of what works while keeping the protocol evolving.' },
    { type: 'multiple_choice', question: 'What is the ultimate goal of resilience training?', options: ['Following a strict protocol forever', 'Integration — practices feel as natural as brushing your teeth', 'Becoming invincible', 'Eliminating all emotions'], correctAnswer: 1, explanation: 'The goal is for practices to become automatic parts of your identity, not forced routines.' },
    { type: 'multiple_choice', question: 'When should you progress to harder challenges?', options: ['Immediately', 'When the current level feels manageable and consistent', 'After reading more theory', 'Never'], correctAnswer: 1, explanation: 'Only progress when the current level is consistent — rushing leads to burnout.' },
    { type: 'multiple_choice', question: 'What matters more than the specific practices chosen?', options: ['The equipment used', 'Consistency of doing them', 'How impressive they sound', 'How long each takes'], correctAnswer: 1, explanation: 'Consistent small practices beat sporadic impressive ones — always.' },
  ]),
];
